/// The SSH retry state machine that owns a generated backoff.
public enum SSHRetryBackoffContext: Sendable {
    /// The initial SSH startup wrapper generated by the CLI.
    case startup

    /// The persistent PTY attach wrapper shared by CLI and restored terminals.
    case attach
}
