// Generated by scripts/generate-claude-launch-environment-policy.py.
// Source: scripts/claude-launch-environment-policy.json. Do not edit by hand.

export const inheritedClaudeLaunchStateKeys = [
  "CLAUDECODE",
  "CLAUDE_CODE",
  "CLAUDE_CODE_CHILD_SESSION",
  "CLAUDE_CODE_BRIDGE_SESSION_ID",
  "CLAUDE_CODE_PARENT_SESSION_ID",
  "CLAUDE_CODE_SESSION_ID",
  "CLAUDE_CODE_ENTRYPOINT",
  "CLAUDE_CODE_EXECPATH",
  "CLAUDE_CODE_SSE_PORT",
  "CLAUDE_CODE_SANDBOXED",
  "CMUX_CLAUDE_TEAMS_SANDBOXED",
] as const;
