import CmuxControlSocket
import CmuxRemoteWorkspace
import Foundation

/// Discovery responses for local callers and authenticated remote relays.
extension TerminalController {
    nonisolated func v2CapabilitiesWithBrowserDesignMode(params: [String: Any]) -> [String: Any] {
        var capabilities = v2Capabilities()
        if params[WorkspaceRemoteRelayCommandRewriter.remoteWorkspaceIDKey] != nil {
            // A capability name is discovery, never a grant. Do not return the
            // local socket, access mode, or unrelated mobile capabilities.
            return [
                "protocol": "cmux-socket", "version": 2, "scope": "remote_workspace",
                "methods": RemoteRelayCommandPolicy().permittedMethods(
                    from: capabilities["methods"] as? [String] ?? []
                )
            ]
        }
        var methods = capabilities["methods"] as? [String] ?? []
        for method in ["browser.design_mode.set", "browser.design_mode.status"]
            where !methods.contains(method)
        {
            methods.append(method)
        }
        capabilities["methods"] = methods.sorted()
        return capabilities
    }

    private nonisolated func v2Capabilities() -> [String: Any] {
        var methods: [String] = [
            "system.ping",
            "system.capabilities",
            "system.identify",
            "system.tree",
            "sidebar.custom.open",
            "system.top",
            "system.memory",
            "automation.list",
            "automation.show",
            "automation.test",
            "automation.enable",
            "automation.disable",
            "automation.logs",
            "automation.reload",
            "vault.sessions",
            "vault.search",
            "vault.checkpoints",
            "vault.checkpoint",
            "vault.fork",
            "caffeine.status",
            "caffeine.set",
            "comments.list",
            "mobile.host.status",
            "mobile.attach_ticket.create",
            "mobile.terminal.set_font",
            "mobile.compatible_tags.get",
            "mobile.compatible_tags.set",
            "mobile.task.attachment.upload",
            "mobile.task.models.list",
            "mobile.chat.send",
            "mobile.chat.interrupt",
            // Socket-reachable panel artifact reads (worker lane); fetch stays
            // behind the authenticated mobile execution context.
            "mobile.panel.artifact.stat",
            "mobile.panel.artifact.thumbnail",
            "mobile.workspace.list",
            "mobile.workspace.changes.files",
            "mobile.workspace.changes.file_diff",
            "mobile.workspace.changes.file_stat",
            "mobile.workspace.changes.file_fetch",
            "mobile.terminal.create",
            "mobile.terminal.input",
            "mobile.terminal.paste",
            "mobile.terminal.paste_image",
            "mobile.terminal.replay",
            "mobile.browser.list",
            "mobile.browser.create",
            "mobile.browser.stream.start",
            "mobile.browser.stream.stop",
            "mobile.browser.viewport",
            "mobile.browser.frame.ack",
            "mobile.browser.dialog.respond",
            "mobile.browser.input.pointer",
            "mobile.browser.input.scroll",
            "mobile.browser.input.key",
            "mobile.browser.input.text",
            "mobile.browser.navigate",
            "mobile.browser.back",
            "mobile.browser.forward",
            "mobile.browser.reload",
            "mobile.terminal.viewport", "mobile.terminal.scroll", "mobile.terminal.mouse",
            "mobile.events.subscribe", "mobile.events.unsubscribe",
            "mobile.status.cycle",
            "terminal.create",
            "terminal.input",
            "terminal.paste",
            "terminal.paste_image",
            "terminal.replay",
            "terminal.viewport", "terminal.scroll", "terminal.mouse",
            "auth.login",
            "auth.status",
            "auth.sign_in_url",
            "auth.begin_sign_in",
            "auth.sign_out", "auth.team.list", "auth.team.use",
            "auth.team.create", "auth.team.members", "auth.team.invite",
            "auth.team.invite_link", "auth.team.revoke_invite",
            "auth.team.remove_member", "auth.team.open_members",
            "auth.team.invitations", "auth.team.accept_invite", "auth.team.decline_invite",
            "vm.billing_checkout",
            "vm.list", "vm.diagnostics", "vm.file_transfer_failure",
            "vm.publication_list",
            "vm.publication_create",
            "vm.publication_verify",
            "vm.publication_update",
            "vm.publication_delete",
            "vm.publication_grants",
            "vm.publication_grant",
            "vm.publication_ungrant",
            "vm.domain_list",
            "vm.domain_verify",
            "vm.create",
            "vm.base_open",
            "vm.base_reset",
            "vm.status",
            "vm.stats",
            "vm.resize",
            "vm.network_get",
            "vm.network_update",
            "vm.agent_updates_get",
            "vm.agent_updates_set",
            "vm.rename",
            "vm.pause",
            "vm.resume",
            "vm.snapshot",
            "vm.snapshot_list",
            "vm.snapshot_delete",
            "vm.fork",
            "vm.restore",
            "vm.destroy",
            "vm.exec",
            "vm.env_set",
            "vm.file_put",
            "vm.reflection",
            "vm.open_port",
            "vm.attach_info",
            "vm.cmux_remote_info",
            "vm.ssh_info",
            "vm.scp_info",
            "vm.sessions",
            "vm.session_attach_info",
            "vm.tree",
            "vm.terminal_open",
            "vm.terminal_new",
            "vm.terminal_rename",
            "vm.tab_rename",
            "vm.workspace_new",
            "vm.workspace_open",
            "vm.workspace_close",
            "vm.workspace_delete",
            "vm.workspace_rename",
            "vm.terminal_close",
            "vm.terminal_write",
            "vm.terminal_read",
            "vm.terminal_wait",
            "vm.terminal_output",
            "vm.terminal_wait_exit",
            "vm.desktop_open",
            "vm.port_open",
            "vm.link_socket",
            "vm.cloud_agent_open",
            "vm.cloud_prompt",
            "vm.tunnel_config",
            "vm.tunnel_status",
            "vm.tunnel_revoke",
            "vm.tunnel_up",
            "vm.tunnel_down",
            "vm.tunnel_wait",
            "surface.catalog",
            "current.list",
            "surface.project",
            "surface.new_terminal",
            "surface.ssh_session_attach.resolve",
            "aiAccounts.list",
            "aiAccounts.upload",
            "aiAccounts.remove",
            "coderouter.claude_upstream.get",
            "coderouter.claude_upstream.set",
            "coderouter.claude_upstream.add",
            "coderouter.claude_upstream.update",
            "coderouter.claude_upstream.remove",
            "coderouter.claude_upstream.clear",
            "coderouter.machines",
            "window.list",
            "window.current",
            "window.focus",
            "window.create",
            "window.close",
            "window.displays",
            "window.display",
            "window.record.start",
            "window.record.stop",
            "window.record.status",
            "window.record.note",
            "window.record.list",
            "window.screenshot",
            "workspace.list",
            "workspace.create",
            "workspace.cloud_vm_open",
            "workspace.cloud_vm_terminal_ready",
            "workspace.cloud_vm_bind",
            "workspace.env",
            "workspace.select",
            "workspace.current",
            "workspace.close",
            "workspace.move",
            "workspace.move_to_window",
            "workspace.status.get",
            "workspace.status.set",
            "workspace.status.cycle",
            "workspace.todo.list",
            "workspace.todo.add",
            "workspace.todo.edit",
            "workspace.todo.remove",
            "workspace.todo.move",
            "workspace.todo.open",
            "workspace.todo.set",
            "workspace.todo.set_state",
            "workspace.todo.clear",
            "workspace.reorder",
            "workspace.reorder_many",
            "workspace.prompt_submit",
            "workspace.rename",
            "workspace.set_auto_title",
            "surface.sync_codex_native_title",
            "workspace.group.list",
            "workspace.group.create",
            "workspace.group.ungroup",
            "workspace.group.delete",
            "workspace.group.rename",
            "workspace.group.collapse",
            "workspace.group.expand",
            "workspace.group.pin",
            "workspace.group.unpin",
            "workspace.group.add",
            "workspace.group.remove",
            "workspace.group.set_anchor",
            "workspace.group.new_workspace",
            "workspace.group.set_color",
            "workspace.group.set_icon",
            "workspace.group.move",
            "workspace.group.focus",
            "workspace.group.action",
            "workspace.action",
            "extension.sidebar.snapshot",
            "workspace.next",
            "workspace.previous",
            "workspace.last",
            "workspace.equalize_splits",
            "workspace.remote.configure",
            "workspace.ssh.open",
            "workspace.remote.foreground_auth_ready",
            "workspace.remote.reconnect",
            "workspace.remote.disconnect",
            "workspace.remote.status",
            "workspace.remote.pty_sessions", "workspace.remote.pty_close", "workspace.remote.pty_detach",
            "workspace.remote.pty_bridge", "workspace.remote.pty_resize", "workspace.remote.pty_attach_end",
            "workspace.remote.terminal_session_launching",
            "workspace.remote.terminal_session_connected", "workspace.remote.terminal_session_end",
            "remote.tmux.sessions", "remote.tmux.attach", "remote.tmux.detach", "remote.tmux.state", "remote.tmux.mirror", "remote.tmux.window", "remote.tmux.pane_grids", "remote.tmux.pane_surfaces",
            "remotes.list", "remotes.add", "remotes.remove",
            "layout.save", "layout.list", "layout.get", "layout.open", "layout.delete",
            "canvas.align", "canvas.break", "canvas.info", "canvas.join", "canvas.new_pane",
            "canvas.overview", "canvas.reveal", "canvas.select_tab", "canvas.set_frame",
            "canvas.set_mode", "canvas.set_viewport", "canvas.zoom",
            "session.restore_previous",
            "session.agent_recovery.list",
            "session.agent_recovery.restore",
            "session.import",
            "session.export",
            "settings.open",
            "feedback.open",
            "feedback.submit",
            "feed.push",
            "feed.permission.reply",
            "feed.question.reply",
            "feed.exit_plan.reply",
            "feed.jump",
            "feed.list",
            "surface.list",
            "surface.current",
            "surface.focus",
            "surface.split",
            "surface.respawn",
            "surface.create",
            "surface.close",
            "surface.drag_to_split",
            "surface.split_off",
            "surface.move",
            "surface.reorder",
            "surface.action",
            "tab.action",
            "surface.refresh",
            "surface.health",
            "terminal.size_state",
            "terminal.size_policy.set",
            "terminal.size_to_me",
            "terminal.size_counts.set",
            "terminal.participant.disconnect",
            "terminal.participants.disconnect_others",
            "surface.resume.set",
            "surface.resume.get",
            "surface.resume.clear",
            "agent.restore.admit",
            "agent.restore.release",
            "agent.hibernate",
            "agent.wake",
            "agent.message.send",
            "agent.message.list",
            "agent.message.claim",
            "agent.message.ack",
            "agent.message.mark_read",
            "agent.message.poll",
            "agent.message.settings",
            "debug.terminals",
            "surface.send_text",
            "surface.send_key",
            "surface.report_tty",
            "surface.report_pwd",
            "surface.report_git_branch",
            "surface.clear_git_branch",
            "surface.report_shell_state",
            "surface.ports_kick",
            "surface.read_text",
            "surface.input_state",
            "surface.read_selection",
            "surface.clear_history",
            "surface.trigger_flash",
            "pane.list",
            "pane.focus",
            "pane.surfaces",
            "pane.create",
            "pane.resize",
            "pane.swap",
            "pane.break",
            "pane.join",
            "pane.last",
            "notification.create",
            "notification.create_for_caller", "agent.resolve_delivery_target", "agent.hibernation.session_end",
            "notification.create_for_surface",
            "notification.create_for_target",
            "notification.list",
            "notification.clear",
            "notification.dismiss",
            "notification.mark_read",
            "notification.open",
            "notification.jump_to_unread",
            "notification.feed.list",
            "notification.feed.mark_read",
            "notification.feed.mark_unread",
            "notification.feed.mark_all_read",
            "app.focus_override.set",
            "app.simulate_active",
            "file.open",
            "markdown.open",
            "browser.open_split",
            "browser.navigate",
            "browser.back",
            "browser.forward",
            "browser.reload",
            "browser.react_grab.toggle",
            "browser.devtools.toggle",
            "browser.console.show",
            "browser.focus_mode.set",
            "browser.zoom.set",
            "browser.history.clear",
            "browser.url.get",
            "browser.snapshot",
            "browser.eval",
            "browser.repl.eval",
            "browser.repl.reset",
            "browser.repl.list",
            "browser.wait",
            "browser.click",
            "browser.dblclick",
            "browser.hover",
            "browser.focus",
            "browser.type",
            "browser.fill",
            "browser.set_input_files",
            "browser.press",
            "browser.keydown",
            "browser.keyup",
            "browser.check",
            "browser.uncheck",
            "browser.select",
            "browser.scroll",
            "browser.scroll_into_view",
            "browser.screenshot",
            "browser.get.text",
            "browser.get.html",
            "browser.get.value",
            "browser.get.attr",
            "browser.get.title",
            "browser.get.count",
            "browser.get.box",
            "browser.get.styles",
            "browser.is.visible",
            "browser.is.enabled",
            "browser.is.checked",
            "browser.focus_webview",
            "browser.is_webview_focused",
            "browser.find.role",
            "browser.find.text",
            "browser.find.label",
            "browser.find.placeholder",
            "browser.find.alt",
            "browser.find.title",
            "browser.find.testid",
            "browser.find.first",
            "browser.find.last",
            "browser.find.nth",
            "browser.frame.select",
            "browser.frame.main",
            "browser.dialog.accept",
            "browser.dialog.dismiss",
            "browser.download.list", "browser.download.wait",
            "browser.cookies.get",
            "browser.cookies.set",
            "browser.cookies.clear",
            "browser.storage.get",
            "browser.storage.set",
            "browser.storage.clear",
            "browser.profiles.list",
            "browser.profiles.create",
            "browser.profiles.rename",
            "browser.profiles.clear",
            "browser.profiles.delete",
            "browser.import.cookies",
            "browser.import.dialog",
            "browser.tab.new",
            "browser.tab.list",
            "browser.tab.switch",
            "browser.tab.close",
            "browser.console.list",
            "browser.console.clear",
            "browser.errors.list",
            "browser.highlight",
            "browser.state.save",
            "browser.state.load",
            "browser.addinitscript",
            "browser.addscript",
            "browser.addstyle",
            "browser.viewport.set",
            "browser.geolocation.set",
            "browser.offline.set",
            "browser.trace.start",
            "browser.trace.stop",
            "browser.network.route",
            "browser.network.unroute",
            "browser.network.requests",
            "browser.screencast.start",
            "browser.screencast.stop",
            "browser.input_mouse",
            "browser.input_keyboard",
            "browser.input_touch",
        ]
        if !Self.mobileTaskComposerFeatureEnabled {
            let taskComposerMethods: Set<String> = [
                "mobile.task.attachment.upload",
                "mobile.task.models.list",
            ]
            methods.removeAll { taskComposerMethods.contains($0) }
        }
        // Discovery runs off-main; read the same flag snapshot as mobile host
        // capabilities rather than crossing to the main-actor flag store.
        if !CmuxFeatureFlags.offMainEffectiveValue(for: CmuxFeatureFlags.mobileWorkspaceChangesFlag) {
            let workspaceChangesMethods: Set<String> = [
                "mobile.workspace.changes.files",
                "mobile.workspace.changes.file_diff",
                "mobile.workspace.changes.file_stat",
                "mobile.workspace.changes.file_fetch",
            ]
            methods.removeAll { workspaceChangesMethods.contains($0) }
        }
        methods.append(contentsOf: ControlCommandExecutionPolicy.simulatorMethods)
#if DEBUG
        methods.append(contentsOf: Self.v2DebugMethodNames)
#endif

        return [
            "protocol": "cmux-socket",
            "version": 2,
            "socket_path": socketServer.currentSocketPath,
            "access_mode": socketServer.accessMode.rawValue,
            "capabilities": MobileHostService.mobileHostCapabilities,
            "methods": methods.sorted()
        ]
    }

}
