#!/usr/bin/env python3
"""Generate a self-contained HTML gallery of the framed App Store screenshots.

Writes <screenshots>/preview/index.html referencing the framed PNGs in place
(../<locale>/<name>_framed.png), grouped by locale + device with locale tabs.
Run by the fastlane `frame` lane so CI uploads the gallery in the screenshots
artifact; also runnable locally.

Usage: generate_preview.py <screenshots_dir>
"""
import html
import urllib.parse
import os
import re
import sys

PRIO = ["en-US", "ja"]


def main():
    ss = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else "."
    data = {}
    for loc in sorted(os.listdir(ss)):
        d = os.path.join(ss, loc)
        if not os.path.isdir(d) or loc == "preview":
            continue
        shots = []
        for f in sorted(os.listdir(d)):
            if not f.endswith("_framed.png"):
                continue
            m = re.match(r"(.+?)-(\d+)-(.+?)_framed\.png", f)
            dev, order, name = (m.group(1), m.group(2), m.group(3)) if m else ("Device", "00", f)
            shots.append((dev, order, name, f))
        if shots:
            data[loc] = sorted(shots, key=lambda s: (s[0], s[1]))

    if not data:
        print("no framed screenshots found; skipping preview")
        return

    locales = sorted(data, key=lambda l: (PRIO.index(l) if l in PRIO else 99, l))
    total = sum(len(v) for v in data.values())

    def section(loc):
        shots = data[loc]
        devices = []
        for dev, *_ in shots:
            if dev not in devices:
                devices.append(dev)
        blocks = []
        for dev in devices:
            cards = "".join(
                f'<figure>'
                f'<img loading="lazy" '
                f'data-framed="{urllib.parse.quote(loc)}/{urllib.parse.quote(f)}" '
                f'data-raw="{urllib.parse.quote(loc)}/{urllib.parse.quote(f.replace("_framed.png", ".png"))}" '
                f'src="{urllib.parse.quote(loc)}/{urllib.parse.quote(f)}" '
                f'alt="{html.escape(name)}"><figcaption>{html.escape(order)} · '
                f'{html.escape(name)}</figcaption></figure>'
                for d2, order, name, f in shots if d2 == dev
            )
            blocks.append(f'<h3>{html.escape(dev)}</h3><div class="grid">{cards}</div>')
        return (f'<section data-loc="{html.escape(loc)}" class="locale">'
                f'<h2>{html.escape(loc)}</h2>{"".join(blocks)}</section>')

    tabs = "".join(
        f'<button class="tab{" active" if i == 0 else ""}" data-loc="{html.escape(l)}">'
        f'{html.escape(l)}</button>' for i, l in enumerate(locales))
    sections = "".join(section(l) for l in locales)

    doc = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>cmux iOS App Store screenshots</title>
<style>
 :root {{ color-scheme: dark; }} * {{ box-sizing: border-box; }}
 body {{ margin:0; font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color:#e9e9f2; background:#15131f;
  background-image:radial-gradient(1200px 800px at 20% 110%,rgba(255,170,120,.10),transparent 60%),
   radial-gradient(1000px 700px at 90% -10%,rgba(120,200,235,.10),transparent 60%),
   linear-gradient(180deg,#1a1836,#262656 55%,#26566a); background-attachment:fixed; }}
 header {{ padding:28px 24px 8px; }} h1 {{ margin:0 0 4px; font-size:22px; }}
 .sub {{ color:#b9bce0; font-size:13px; }}
 .tabs {{ display:flex; flex-wrap:wrap; gap:6px; padding:14px 24px; position:sticky; top:0;
  backdrop-filter:blur(12px); background:rgba(21,19,31,.6); z-index:5; }}
 .tab {{ border:1px solid rgba(255,255,255,.14); background:rgba(255,255,255,.04); color:#cfd2f4;
  border-radius:999px; padding:6px 12px; font-size:13px; cursor:pointer; }}
 .tab.active {{ background:#6b6bff; border-color:#6b6bff; color:#fff; }}
 .toggle {{ margin-left:auto; display:flex; align-items:center; gap:7px; color:#cfd2f4; font-size:13px; }}
 main {{ padding:8px 24px 60px; }} .locale {{ display:none; }} .locale.active {{ display:block; }}
 h2 {{ font-size:15px; color:#9fb4ff; letter-spacing:.04em; text-transform:uppercase; margin:18px 0 0; }}
 h3 {{ font-size:14px; color:#b9bce0; margin:22px 0 10px; }}
 .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:18px; }}
 figure {{ margin:0; }} img {{ width:100%; border-radius:14px; box-shadow:0 10px 30px rgba(0,0,0,.35); display:block; }}
 figcaption {{ margin-top:8px; font-size:12px; color:#9a9cc4; }}
</style></head><body>
<header><h1>cmux iOS — App Store screenshots</h1>
<div class="sub">{total} framed screenshots · {len(locales)} locales · generated by the CI frameit pipeline</div></header>
<div class="tabs">{tabs}
 <label class="toggle"><input type="checkbox" id="rawToggle"> Show original (unframed) captures</label></div>
<main>{sections}</main>
<script>
 const tabs=[...document.querySelectorAll('.tab')],secs=[...document.querySelectorAll('.locale')];
 function show(l){{tabs.forEach(t=>t.classList.toggle('active',t.dataset.loc===l));
  secs.forEach(s=>s.classList.toggle('active',s.dataset.loc===l));}}
 tabs.forEach(t=>t.addEventListener('click',()=>show(t.dataset.loc)));
 if(secs[0])show(secs[0].dataset.loc);
 const raw=document.getElementById('rawToggle');
 raw.addEventListener('change',()=>{{for(const i of document.images){{
  const u=raw.checked?i.dataset.raw:i.dataset.framed; if(u)i.src=u;}}}});
</script></body></html>"""
    # Write at the screenshots root so img src uses <locale>/<file> (a subdir):
    # browsers block file:// access to parent dirs (../), which broke the gallery.
    with open(os.path.join(ss, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(doc)
    print(f"wrote {ss}/index.html ({total} screenshots, {len(locales)} locales)")


if __name__ == "__main__":
    main()
