# Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
# Source: cmux-tui/spec/sdk-schema.json

from __future__ import annotations

import base64
from typing import Any, Dict, List, Literal, Union

from .metadata import COMMANDS
from .models import *


class GeneratedClientMixin:

    def apply_layout(self, layout: DeclarativeLayout, *, workspace: Union[Id, None, MissingType] = MISSING, name: Union[str, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> ApplyLayoutResult:
        return self._invoke_command('apply-layout', ApplyLayoutRequest(layout=layout, workspace=workspace, name=name, cols=cols, rows=rows))

    def attach_surface(self, surface: Id, *, cols: Union[int, None, MissingType] = MISSING, mode: Union[Literal['bytes', 'render'], None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> Any:
        return self._open_command_stream('attach-surface', AttachSurfaceRequest(surface=surface, cols=cols, mode=mode, rows=rows))

    def browser_activate(self, surface: Id) -> EmptyResult:
        return self._invoke_command('browser-activate', BrowserActivateRequest(surface=surface))

    def browser_back(self, surface: Id) -> EmptyResult:
        return self._invoke_command('browser-back', BrowserBackRequest(surface=surface))

    def browser_forward(self, surface: Id) -> EmptyResult:
        return self._invoke_command('browser-forward', BrowserForwardRequest(surface=surface))

    def browser_frame_presented(self, surface: Id, frame_seq: int) -> EmptyResult:
        return self._invoke_command('browser-frame-presented', BrowserFramePresentedRequest(surface=surface, frame_seq=frame_seq))

    def browser_insert_text(self, surface: Id, text: str) -> EmptyResult:
        return self._invoke_command('browser-insert-text', BrowserInsertTextRequest(surface=surface, text=text))

    def browser_key(self, surface: Id, kind: Literal['down', 'up'], key: str, code: str, windows_virtual_key_code: int, modifiers: int, *, text: Union[str, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('browser-key', BrowserKeyRequest(surface=surface, kind=kind, key=key, code=code, windows_virtual_key_code=windows_virtual_key_code, modifiers=modifiers, text=text))

    def browser_key_press(self, surface: Id, code: str, key: str, modifiers: int, windows_virtual_key_code: int, *, text: Union[str, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('browser-key-press', BrowserKeyPressRequest(surface=surface, code=code, key=key, modifiers=modifiers, windows_virtual_key_code=windows_virtual_key_code, text=text))

    def browser_mouse(self, surface: Id, kind: Literal['down', 'up', 'move'], x_px: float, y_px: float, *, button: Union[str, None, MissingType] = MISSING, click_count: Union[int, None, MissingType] = MISSING, frame_seq: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('browser-mouse', BrowserMouseRequest(surface=surface, kind=kind, x_px=x_px, y_px=y_px, button=button, click_count=click_count, frame_seq=frame_seq))

    def browser_mouse_guarded(self, surface: Id, frame_seq: int, kind: Literal['down', 'up', 'move'], x_px: float, y_px: float, *, button: Union[str, None, MissingType] = MISSING, click_count: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('browser-mouse-guarded', BrowserMouseGuardedRequest(surface=surface, frame_seq=frame_seq, kind=kind, x_px=x_px, y_px=y_px, button=button, click_count=click_count))

    def browser_navigate(self, surface: Id, url: str) -> EmptyResult:
        return self._invoke_command('browser-navigate', BrowserNavigateRequest(surface=surface, url=url))

    def browser_reload(self, surface: Id) -> EmptyResult:
        return self._invoke_command('browser-reload', BrowserReloadRequest(surface=surface))

    def browser_wheel(self, surface: Id, x_px: float, y_px: float, delta_y_px: float, *, frame_seq: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('browser-wheel', BrowserWheelRequest(surface=surface, x_px=x_px, y_px=y_px, delta_y_px=delta_y_px, frame_seq=frame_seq))

    def browser_wheel_guarded(self, surface: Id, delta_y_px: float, frame_seq: int, x_px: float, y_px: float) -> EmptyResult:
        return self._invoke_command('browser-wheel-guarded', BrowserWheelGuardedRequest(surface=surface, delta_y_px=delta_y_px, frame_seq=frame_seq, x_px=x_px, y_px=y_px))

    def clear_history(self, surface: Id, *, fallback_key: Union[TerminalKeyInput, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('clear-history', ClearHistoryRequest(surface=surface, fallback_key=fallback_key))

    def clear_window_title(self) -> EmptyResult:
        return self._invoke_command('clear-window-title', ClearWindowTitleRequest())

    def client_focus(self, client_id: str) -> ClientFocusResult:
        return self._invoke_command('client-focus', ClientFocusRequest(client_id=client_id))

    def close_pane(self, pane: Id) -> EmptyResult:
        return self._invoke_command('close-pane', ClosePaneRequest(pane=pane))

    def close_provider_managed_workspace(self, workspace: Id, key: str, authority: str) -> ProviderWorkspaceMutationResult:
        return self._invoke_command('close-provider-managed-workspace', CloseProviderManagedWorkspaceRequest(workspace=workspace, key=key, authority=authority))

    def close_screen(self, screen: Id) -> EmptyResult:
        return self._invoke_command('close-screen', CloseScreenRequest(screen=screen))

    def close_surface(self, surface: Id) -> EmptyResult:
        return self._invoke_command('close-surface', CloseSurfaceRequest(surface=surface))

    def close_terminal(self, terminal_id: str, *, expected_generation: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, terminal_incarnation: Union[str, None, MissingType] = MISSING) -> CloseTerminalResult:
        return self._invoke_command('close-terminal', CloseTerminalRequest(terminal_id=terminal_id, expected_generation=expected_generation, expected_revision=expected_revision, mutation_id=mutation_id, origin=origin, terminal_incarnation=terminal_incarnation))

    def close_workspace(self, workspace: Union[Id, None, MissingType] = MISSING, *, key: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> WorkspaceMutationResult:
        return self._invoke_command('close-workspace', CloseWorkspaceRequest(workspace=workspace, key=key, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def copy(self, surface: Id, mode: Literal['screen', 'selection', 'scrollback']) -> CopyResult:
        return self._invoke_command('copy', CopyRequest(surface=surface, mode=mode))

    def create_surface_with_receipt(self, operation: str, origin: str, receipt: str, *, pane: Union[Id, None, MissingType] = MISSING, workspace: Union[Id, None, MissingType] = MISSING, argv: Union[List[str], None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, cwd: Union[str, None, MissingType] = MISSING, idempotency_key: Union[str, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING, selector_fallbacks: Union[List[ResourceSelectors], MissingType] = MISSING, selectors: Union[ResourceSelectors, None, MissingType] = MISSING, url: Union[str, None, MissingType] = MISSING, width: Union[float, None, MissingType] = MISSING) -> JsonValue:
        return self._invoke_command('create-surface-with-receipt', CreateSurfaceWithReceiptRequest(operation=operation, origin=origin, receipt=receipt, pane=pane, workspace=workspace, argv=argv, cols=cols, cwd=cwd, idempotency_key=idempotency_key, rows=rows, selector_fallbacks=selector_fallbacks, selectors=selectors, url=url, width=width))

    def create_terminal(self, workspace: Union[Id, None, MissingType] = MISSING, *, key: Union[str, None, MissingType] = MISSING, argv: Union[List[str], None, MissingType] = MISSING, command: Union[str, None, MissingType] = MISSING, cwd: Union[str, None, MissingType] = MISSING, name: Union[str, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING, terminal_id: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> TerminalPlacement:
        return self._invoke_command('create-terminal', CreateTerminalRequest(workspace=workspace, key=key, argv=argv, command=command, cwd=cwd, name=name, cols=cols, rows=rows, terminal_id=terminal_id, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def create_workspace(self, *, name: Union[str, None, MissingType] = MISSING, key: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> WorkspaceMutationResult:
        return self._invoke_command('create-workspace', CreateWorkspaceRequest(name=name, key=key, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def detach_attached_view(self, surface: Id, lease: str) -> AttachedViewOutcomeResult:
        return self._invoke_command('detach-attached-view', DetachAttachedViewRequest(surface=surface, lease=lease))

    def detach_client(self, client: int) -> EmptyResult:
        return self._invoke_command('detach-client', DetachClientRequest(client=client))

    def export_layout(self, screen: Union[Id, None, MissingType] = MISSING) -> ExportLayoutResult:
        return self._invoke_command('export-layout', ExportLayoutRequest(screen=screen))

    def focus_direction(self, dir: PaneDirection, *, pane: Union[Id, None, MissingType] = MISSING) -> FocusDirectionResult:
        return self._invoke_command('focus-direction', FocusDirectionRequest(dir=dir, pane=pane))

    def focus_pane(self, pane: Id) -> EmptyResult:
        return self._invoke_command('focus-pane', FocusPaneRequest(pane=pane))

    def get_browser_provider(self) -> BrowserProviderSnapshot:
        return self._invoke_command('get-browser-provider', GetBrowserProviderRequest())

    def get_cell_pixels(self) -> GetCellPixelsResult:
        return self._invoke_command('get-cell-pixels', GetCellPixelsRequest())

    def get_frontend_projection(self, frontend: str, scope: str, subject_key: str) -> FrontendProjection:
        return self._invoke_command('get-frontend-projection', GetFrontendProjectionRequest(frontend=frontend, scope=scope, subject_key=subject_key))

    def identify(self) -> IdentifyResult:
        return self._invoke_command('identify', IdentifyRequest())

    def ids(self, *, kind: Union[Literal['workspace', 'screen', 'pane', 'surface'], None, MissingType] = MISSING) -> IdsResult:
        return self._invoke_command('ids', IdsRequest(kind=kind))

    def journal_frontend_event(self, event: FrontendJournalEvent) -> JournalFrontendEventResult:
        return self._invoke_command('journal-frontend-event', JournalFrontendEventRequest(event=event))

    def list_agents(self, surface: Union[Id, None, MissingType] = MISSING, *, state: Union[AgentState, None, MissingType] = MISSING) -> ListAgentsResult:
        return self._invoke_command('list-agents', ListAgentsRequest(surface=surface, state=state))

    def list_clients(self) -> List[ClientInfo]:
        return self._invoke_command('list-clients', ListClientsRequest())

    def list_terminals(self) -> ListTerminalsResult:
        return self._invoke_command('list-terminals', ListTerminalsRequest())

    def list_workspaces(self) -> Tree:
        return self._invoke_command('list-workspaces', ListWorkspacesRequest())

    def mark_workspaces_provider_managed(self, authority: str) -> EmptyResult:
        return self._invoke_command('mark-workspaces-provider-managed', MarkWorkspacesProviderManagedRequest(authority=authority))

    def mint_terminal_renderer(self, surface: Id, *, ttl_ms: Union[int, MissingType] = MISSING) -> MintTerminalRendererResult:
        return self._invoke_command('mint-terminal-renderer', MintTerminalRendererRequest(surface=surface, ttl_ms=ttl_ms))

    def mint_terminal_renderer_by_terminal(self, terminal: str, *, ttl_ms: Union[int, MissingType] = MISSING) -> MintTerminalRendererResult:
        return self._invoke_command('mint-terminal-renderer-by-terminal', MintTerminalRendererByTerminalRequest(terminal=terminal, ttl_ms=ttl_ms))

    def move_tab(self, surface: Id, pane: Id, index: int) -> EmptyResult:
        return self._invoke_command('move-tab', MoveTabRequest(surface=surface, pane=pane, index=index))

    def move_terminal(self, terminal_id: str, workspace_key: str, *, terminal_incarnation: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> MoveTerminalResult:
        return self._invoke_command('move-terminal', MoveTerminalRequest(terminal_id=terminal_id, workspace_key=workspace_key, terminal_incarnation=terminal_incarnation, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def move_workspace(self, index: int, *, workspace: Union[Id, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, key: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING) -> WorkspaceMutationResult:
        return self._invoke_command('move-workspace', MoveWorkspaceRequest(index=index, workspace=workspace, expected_generation=expected_generation, expected_revision=expected_revision, key=key, mutation_id=mutation_id, origin=origin))

    def new_browser_tab(self, url: str, *, pane: Union[Id, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-browser-tab', NewBrowserTabRequest(url=url, pane=pane, cols=cols, rows=rows))

    def new_pane(self, pane: Id, *, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-pane', NewPaneRequest(pane=pane, cols=cols, rows=rows))

    def new_pane_right(self, pane: Id, *, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING, width: Union[float, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-pane-right', NewPaneRightRequest(pane=pane, cols=cols, rows=rows, width=width))

    def new_screen(self, workspace: Union[Id, None, MissingType] = MISSING, *, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-screen', NewScreenRequest(workspace=workspace, cols=cols, rows=rows))

    def new_tab(self, pane: Union[Id, None, MissingType] = MISSING, *, cwd: Union[str, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-tab', NewTabRequest(pane=pane, cwd=cwd, cols=cols, rows=rows))

    def new_workspace(self, *, name: Union[str, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('new-workspace', NewWorkspaceRequest(name=name, cols=cols, rows=rows))

    def notify(self, title: str, body: str, *, level: Union[NotificationLevel, None, MissingType] = MISSING, surface: Union[Id, None, MissingType] = MISSING) -> NotifyResult:
        return self._invoke_command('notify', NotifyRequest(title=title, body=body, level=level, surface=surface))

    def pairing_response(self, request: int, approve: bool) -> EmptyResult:
        return self._invoke_command('pairing-response', PairingResponseRequest(request=request, approve=approve))

    def pane_neighbor(self, pane: Id, dir: PaneDirection) -> PaneNeighborResult:
        return self._invoke_command('pane-neighbor', PaneNeighborRequest(pane=pane, dir=dir))

    def ping(self) -> PingResult:
        return self._invoke_command('ping', PingRequest())

    def process_info(self, surface: Id) -> ProcessInfoResult:
        return self._invoke_command('process-info', ProcessInfoRequest(surface=surface))

    def put_frontend_projection(self, frontend: str, scope: str, subject_key: str, schema_version: int, projection: Union[JsonValue, None], *, expected_projection_revision: Union[int, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> FrontendProjection:
        return self._invoke_command('put-frontend-projection', PutFrontendProjectionRequest(frontend=frontend, scope=scope, subject_key=subject_key, schema_version=schema_version, projection=projection, expected_projection_revision=expected_projection_revision, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def read_screen(self, surface: Id) -> ReadScreenResult:
        return self._invoke_command('read-screen', ReadScreenRequest(surface=surface))

    def read_scrollback(self, surface: Id, start: int, count: int) -> ReadScrollbackResult:
        return self._invoke_command('read-scrollback', ReadScrollbackRequest(surface=surface, start=start, count=count))

    def register_browser_provider(self, authentication: BrowserProviderAuthentication, endpoint: str, provider_id: str, targets: List[BrowserProviderTarget], *, bearer_token: Union[str, None, MissingType] = MISSING) -> BrowserProviderSnapshot:
        return self._invoke_command('register-browser-provider', RegisterBrowserProviderRequest(authentication=authentication, endpoint=endpoint, provider_id=provider_id, targets=targets, bearer_token=bearer_token))

    def release_attached_view_size(self, surface: Id, lease: str) -> AttachedViewOutcomeResult:
        return self._invoke_command('release-attached-view-size', ReleaseAttachedViewSizeRequest(surface=surface, lease=lease))

    def release_surface_size(self, surface: Id) -> EmptyResult:
        return self._invoke_command('release-surface-size', ReleaseSurfaceSizeRequest(surface=surface))

    def reload_config(self) -> ReloadConfigResult:
        return self._invoke_command('reload-config', ReloadConfigRequest())

    def rename_pane(self, pane: Id, name: str) -> EmptyResult:
        return self._invoke_command('rename-pane', RenamePaneRequest(pane=pane, name=name))

    def rename_provider_managed_workspace(self, workspace: Id, key: str, name: str, authority: str) -> ProviderWorkspaceMutationResult:
        return self._invoke_command('rename-provider-managed-workspace', RenameProviderManagedWorkspaceRequest(workspace=workspace, key=key, name=name, authority=authority))

    def rename_screen(self, screen: Id, name: str) -> EmptyResult:
        return self._invoke_command('rename-screen', RenameScreenRequest(screen=screen, name=name))

    def rename_surface(self, surface: Id, name: str) -> EmptyResult:
        return self._invoke_command('rename-surface', RenameSurfaceRequest(surface=surface, name=name))

    def rename_workspace(self, name: str, *, workspace: Union[Id, None, MissingType] = MISSING, key: Union[str, None, MissingType] = MISSING, expected_revision: Union[int, None, MissingType] = MISSING, expected_generation: Union[str, None, MissingType] = MISSING, origin: Union[str, None, MissingType] = MISSING, mutation_id: Union[str, None, MissingType] = MISSING) -> WorkspaceMutationResult:
        return self._invoke_command('rename-workspace', RenameWorkspaceRequest(name=name, workspace=workspace, key=key, expected_revision=expected_revision, expected_generation=expected_generation, origin=origin, mutation_id=mutation_id))

    def report_agent(self, surface: Id, state: AgentState, source: AgentReportSource, *, session: Union[str, None, MissingType] = MISSING) -> ReportAgentResult:
        return self._invoke_command('report-agent', ReportAgentRequest(surface=surface, state=state, source=source, session=session))

    def report_focus(self, pane: Id, client_id: str, *, tab: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('report-focus', ReportFocusRequest(pane=pane, client_id=client_id, tab=tab))

    def resize_attached_view(self, surface: Id, cols: int, lease: str, rows: int) -> AttachedViewResizeResult:
        return self._invoke_command('resize-attached-view', ResizeAttachedViewRequest(surface=surface, cols=cols, lease=lease, rows=rows))

    def resize_surface(self, surface: Id, cols: int, rows: int) -> ResizeSurfaceResult:
        return self._invoke_command('resize-surface', ResizeSurfaceRequest(surface=surface, cols=cols, rows=rows))

    def resolve_terminal(self, terminal_id: str) -> ResolveTerminalResult:
        return self._invoke_command('resolve-terminal', ResolveTerminalRequest(terminal_id=terminal_id))

    def run(self, pane: Union[Id, None, MissingType] = MISSING, *, argv: Union[List[str], None, MissingType] = MISSING, command: Union[str, None, MissingType] = MISSING, cwd: Union[str, None, MissingType] = MISSING, new_workspace: Union[bool, MissingType] = MISSING, key: Union[str, None, MissingType] = MISSING, name: Union[str, None, MissingType] = MISSING, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> RunResult:
        return self._invoke_command('run', RunRequest(pane=pane, argv=argv, command=command, cwd=cwd, new_workspace=new_workspace, key=key, name=name, cols=cols, rows=rows))

    def scroll_surface(self, surface: Id, delta: int) -> EmptyResult:
        return self._invoke_command('scroll-surface', ScrollSurfaceRequest(surface=surface, delta=delta))

    def select_screen(self, index: Union[int, None, MissingType] = MISSING, *, delta: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('select-screen', SelectScreenRequest(index=index, delta=delta))

    def select_tab(self, pane: Union[Id, None, MissingType] = MISSING, *, index: Union[int, None, MissingType] = MISSING, delta: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('select-tab', SelectTabRequest(pane=pane, index=index, delta=delta))

    def select_workspace(self, index: Union[int, None, MissingType] = MISSING, *, delta: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('select-workspace', SelectWorkspaceRequest(index=index, delta=delta))

    def send(self, surface: Id, *, text: Union[str, None, MissingType] = MISSING, bytes_data: Union[Union[Base64, None, MissingType], bytes] = MISSING, paste: Union[bool, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('send', SendRequest(surface=surface, text=text, bytes_data=(base64.b64encode(bytes_data).decode('ascii') if isinstance(bytes_data, bytes) else bytes_data), paste=paste))

    def send_key(self, surface: Id, keys: List[str]) -> EmptyResult:
        return self._invoke_command('send-key', SendKeyRequest(surface=surface, keys=keys))

    def set_cell_pixels(self, width_px: int, height_px: int) -> SetCellPixelsResult:
        return self._invoke_command('set-cell-pixels', SetCellPixelsRequest(width_px=width_px, height_px=height_px))

    def set_client_info(self, *, name: Union[str, None, MissingType] = MISSING, kind: Union[str, None, MissingType] = MISSING, capabilities: Union[List[str], None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('set-client-info', SetClientInfoRequest(name=name, kind=kind, capabilities=capabilities))

    def set_client_sizing(self, surface: Id, enabled: bool, *, client: Union[int, None, MissingType] = MISSING, exclusive: Union[bool, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('set-client-sizing', SetClientSizingRequest(surface=surface, enabled=enabled, client=client, exclusive=exclusive))

    def set_default_colors(self, fg: Union[ColorHex, None, MissingType] = MISSING, *, bg: Union[ColorHex, None, MissingType] = MISSING, cursor: Union[ColorHex, None, MissingType] = MISSING, selection_bg: Union[ColorHex, None, MissingType] = MISSING, selection_fg: Union[ColorHex, None, MissingType] = MISSING, cursor_style: Union[CursorStyle, None, MissingType] = MISSING, cursor_blink: Union[bool, None, MissingType] = MISSING, palette: Union[Dict[str, ColorHex], None, MissingType] = MISSING, complete: Union[bool, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('set-default-colors', SetDefaultColorsRequest(fg=fg, bg=bg, cursor=cursor, selection_bg=selection_bg, selection_fg=selection_fg, cursor_style=cursor_style, cursor_blink=cursor_blink, palette=palette, complete=complete))

    def set_ratio(self, pane: Id, dir: SplitDirection, ratio: float) -> EmptyResult:
        return self._invoke_command('set-ratio', SetRatioRequest(pane=pane, dir=dir, ratio=ratio))

    def set_split_ratio(self, split: Id, ratio: float, *, transaction: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('set-split-ratio', SetSplitRatioRequest(split=split, ratio=ratio, transaction=transaction))

    def set_viewport_pane_width(self, pane: Id, width: float, *, transaction: Union[int, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('set-viewport-pane-width', SetViewportPaneWidthRequest(pane=pane, width=width, transaction=transaction))

    def set_window_title(self, title: str) -> EmptyResult:
        return self._invoke_command('set-window-title', SetWindowTitleRequest(title=title))

    def shutdown_daemon(self, pid: int, generation: str, *, force: Union[bool, MissingType] = MISSING) -> ShutdownDaemonResult:
        return self._invoke_command('shutdown-daemon', ShutdownDaemonRequest(pid=pid, generation=generation, force=force))

    def sidebar_plugin(self, cols: int, rows: int, *, relaunch: Union[bool, MissingType] = MISSING) -> SidebarPluginResult:
        return self._invoke_command('sidebar-plugin', SidebarPluginRequest(cols=cols, rows=rows, relaunch=relaunch))

    def split(self, pane: Id, dir: SplitDirection, *, cols: Union[int, None, MissingType] = MISSING, rows: Union[int, None, MissingType] = MISSING) -> SurfaceResult:
        return self._invoke_command('split', SplitRequest(pane=pane, dir=dir, cols=cols, rows=rows))

    def subscribe(self, surface: Union[Id, None, MissingType] = MISSING, *, tree_events: Union[Literal['coarse', 'deltas'], None, MissingType] = MISSING) -> Any:
        return self._open_command_stream('subscribe', SubscribeRequest(surface=surface, tree_events=tree_events))

    def swap_pane(self, pane: Id, *, dir: Union[PaneDirection, None, MissingType] = MISSING, target: Union[Id, None, MissingType] = MISSING) -> EmptyResult:
        return self._invoke_command('swap-pane', SwapPaneRequest(pane=pane, dir=dir, target=target))

    def terminal_events(self, *, after_revision: Union[int, MissingType] = MISSING) -> TerminalEventsResult:
        return self._invoke_command('terminal-events', TerminalEventsRequest(after_revision=after_revision))

    def undo_layout(self, pane: Id, *, confirm_close: Union[bool, MissingType] = MISSING, revision: Union[int, None, MissingType] = MISSING) -> LayoutUndoResult:
        return self._invoke_command('undo-layout', UndoLayoutRequest(pane=pane, confirm_close=confirm_close, revision=revision))

    def unregister_browser_provider(self) -> BrowserProviderUnregisterResult:
        return self._invoke_command('unregister-browser-provider', UnregisterBrowserProviderRequest())

    def vt_state(self, surface: Id) -> VtStateResult:
        return self._invoke_command('vt-state', VtStateRequest(surface=surface))

    def wait_for(self, surface: Id, pattern: str, timeout_ms: int) -> WaitForResult:
        return self._invoke_command('wait-for', WaitForRequest(surface=surface, pattern=pattern, timeout_ms=timeout_ms))

    def zoom_pane(self, pane: Union[Id, None, MissingType] = MISSING, *, mode: Union[Literal['toggle', 'on', 'off'], None, MissingType] = MISSING) -> ZoomPaneResult:
        return self._invoke_command('zoom-pane', ZoomPaneRequest(pane=pane, mode=mode))


GeneratedClientMixin.apply_layout.__cmux_command__ = COMMANDS['apply-layout']
GeneratedClientMixin.attach_surface.__cmux_command__ = COMMANDS['attach-surface']
GeneratedClientMixin.browser_activate.__cmux_command__ = COMMANDS['browser-activate']
GeneratedClientMixin.browser_back.__cmux_command__ = COMMANDS['browser-back']
GeneratedClientMixin.browser_forward.__cmux_command__ = COMMANDS['browser-forward']
GeneratedClientMixin.browser_frame_presented.__cmux_command__ = COMMANDS['browser-frame-presented']
GeneratedClientMixin.browser_insert_text.__cmux_command__ = COMMANDS['browser-insert-text']
GeneratedClientMixin.browser_key.__cmux_command__ = COMMANDS['browser-key']
GeneratedClientMixin.browser_key_press.__cmux_command__ = COMMANDS['browser-key-press']
GeneratedClientMixin.browser_mouse.__cmux_command__ = COMMANDS['browser-mouse']
GeneratedClientMixin.browser_mouse_guarded.__cmux_command__ = COMMANDS['browser-mouse-guarded']
GeneratedClientMixin.browser_navigate.__cmux_command__ = COMMANDS['browser-navigate']
GeneratedClientMixin.browser_reload.__cmux_command__ = COMMANDS['browser-reload']
GeneratedClientMixin.browser_wheel.__cmux_command__ = COMMANDS['browser-wheel']
GeneratedClientMixin.browser_wheel_guarded.__cmux_command__ = COMMANDS['browser-wheel-guarded']
GeneratedClientMixin.clear_history.__cmux_command__ = COMMANDS['clear-history']
GeneratedClientMixin.clear_window_title.__cmux_command__ = COMMANDS['clear-window-title']
GeneratedClientMixin.client_focus.__cmux_command__ = COMMANDS['client-focus']
GeneratedClientMixin.close_pane.__cmux_command__ = COMMANDS['close-pane']
GeneratedClientMixin.close_provider_managed_workspace.__cmux_command__ = COMMANDS['close-provider-managed-workspace']
GeneratedClientMixin.close_screen.__cmux_command__ = COMMANDS['close-screen']
GeneratedClientMixin.close_surface.__cmux_command__ = COMMANDS['close-surface']
GeneratedClientMixin.close_terminal.__cmux_command__ = COMMANDS['close-terminal']
GeneratedClientMixin.close_workspace.__cmux_command__ = COMMANDS['close-workspace']
GeneratedClientMixin.copy.__cmux_command__ = COMMANDS['copy']
GeneratedClientMixin.create_surface_with_receipt.__cmux_command__ = COMMANDS['create-surface-with-receipt']
GeneratedClientMixin.create_terminal.__cmux_command__ = COMMANDS['create-terminal']
GeneratedClientMixin.create_workspace.__cmux_command__ = COMMANDS['create-workspace']
GeneratedClientMixin.detach_attached_view.__cmux_command__ = COMMANDS['detach-attached-view']
GeneratedClientMixin.detach_client.__cmux_command__ = COMMANDS['detach-client']
GeneratedClientMixin.export_layout.__cmux_command__ = COMMANDS['export-layout']
GeneratedClientMixin.focus_direction.__cmux_command__ = COMMANDS['focus-direction']
GeneratedClientMixin.focus_pane.__cmux_command__ = COMMANDS['focus-pane']
GeneratedClientMixin.get_browser_provider.__cmux_command__ = COMMANDS['get-browser-provider']
GeneratedClientMixin.get_cell_pixels.__cmux_command__ = COMMANDS['get-cell-pixels']
GeneratedClientMixin.get_frontend_projection.__cmux_command__ = COMMANDS['get-frontend-projection']
GeneratedClientMixin.identify.__cmux_command__ = COMMANDS['identify']
GeneratedClientMixin.ids.__cmux_command__ = COMMANDS['ids']
GeneratedClientMixin.journal_frontend_event.__cmux_command__ = COMMANDS['journal-frontend-event']
GeneratedClientMixin.list_agents.__cmux_command__ = COMMANDS['list-agents']
GeneratedClientMixin.list_clients.__cmux_command__ = COMMANDS['list-clients']
GeneratedClientMixin.list_terminals.__cmux_command__ = COMMANDS['list-terminals']
GeneratedClientMixin.list_workspaces.__cmux_command__ = COMMANDS['list-workspaces']
GeneratedClientMixin.mark_workspaces_provider_managed.__cmux_command__ = COMMANDS['mark-workspaces-provider-managed']
GeneratedClientMixin.mint_terminal_renderer.__cmux_command__ = COMMANDS['mint-terminal-renderer']
GeneratedClientMixin.mint_terminal_renderer_by_terminal.__cmux_command__ = COMMANDS['mint-terminal-renderer-by-terminal']
GeneratedClientMixin.move_tab.__cmux_command__ = COMMANDS['move-tab']
GeneratedClientMixin.move_terminal.__cmux_command__ = COMMANDS['move-terminal']
GeneratedClientMixin.move_workspace.__cmux_command__ = COMMANDS['move-workspace']
GeneratedClientMixin.new_browser_tab.__cmux_command__ = COMMANDS['new-browser-tab']
GeneratedClientMixin.new_pane.__cmux_command__ = COMMANDS['new-pane']
GeneratedClientMixin.new_pane_right.__cmux_command__ = COMMANDS['new-pane-right']
GeneratedClientMixin.new_screen.__cmux_command__ = COMMANDS['new-screen']
GeneratedClientMixin.new_tab.__cmux_command__ = COMMANDS['new-tab']
GeneratedClientMixin.new_workspace.__cmux_command__ = COMMANDS['new-workspace']
GeneratedClientMixin.notify.__cmux_command__ = COMMANDS['notify']
GeneratedClientMixin.pairing_response.__cmux_command__ = COMMANDS['pairing-response']
GeneratedClientMixin.pane_neighbor.__cmux_command__ = COMMANDS['pane-neighbor']
GeneratedClientMixin.ping.__cmux_command__ = COMMANDS['ping']
GeneratedClientMixin.process_info.__cmux_command__ = COMMANDS['process-info']
GeneratedClientMixin.put_frontend_projection.__cmux_command__ = COMMANDS['put-frontend-projection']
GeneratedClientMixin.read_screen.__cmux_command__ = COMMANDS['read-screen']
GeneratedClientMixin.read_scrollback.__cmux_command__ = COMMANDS['read-scrollback']
GeneratedClientMixin.register_browser_provider.__cmux_command__ = COMMANDS['register-browser-provider']
GeneratedClientMixin.release_attached_view_size.__cmux_command__ = COMMANDS['release-attached-view-size']
GeneratedClientMixin.release_surface_size.__cmux_command__ = COMMANDS['release-surface-size']
GeneratedClientMixin.reload_config.__cmux_command__ = COMMANDS['reload-config']
GeneratedClientMixin.rename_pane.__cmux_command__ = COMMANDS['rename-pane']
GeneratedClientMixin.rename_provider_managed_workspace.__cmux_command__ = COMMANDS['rename-provider-managed-workspace']
GeneratedClientMixin.rename_screen.__cmux_command__ = COMMANDS['rename-screen']
GeneratedClientMixin.rename_surface.__cmux_command__ = COMMANDS['rename-surface']
GeneratedClientMixin.rename_workspace.__cmux_command__ = COMMANDS['rename-workspace']
GeneratedClientMixin.report_agent.__cmux_command__ = COMMANDS['report-agent']
GeneratedClientMixin.report_focus.__cmux_command__ = COMMANDS['report-focus']
GeneratedClientMixin.resize_attached_view.__cmux_command__ = COMMANDS['resize-attached-view']
GeneratedClientMixin.resize_surface.__cmux_command__ = COMMANDS['resize-surface']
GeneratedClientMixin.resolve_terminal.__cmux_command__ = COMMANDS['resolve-terminal']
GeneratedClientMixin.run.__cmux_command__ = COMMANDS['run']
GeneratedClientMixin.scroll_surface.__cmux_command__ = COMMANDS['scroll-surface']
GeneratedClientMixin.select_screen.__cmux_command__ = COMMANDS['select-screen']
GeneratedClientMixin.select_tab.__cmux_command__ = COMMANDS['select-tab']
GeneratedClientMixin.select_workspace.__cmux_command__ = COMMANDS['select-workspace']
GeneratedClientMixin.send.__cmux_command__ = COMMANDS['send']
GeneratedClientMixin.send_key.__cmux_command__ = COMMANDS['send-key']
GeneratedClientMixin.set_cell_pixels.__cmux_command__ = COMMANDS['set-cell-pixels']
GeneratedClientMixin.set_client_info.__cmux_command__ = COMMANDS['set-client-info']
GeneratedClientMixin.set_client_sizing.__cmux_command__ = COMMANDS['set-client-sizing']
GeneratedClientMixin.set_default_colors.__cmux_command__ = COMMANDS['set-default-colors']
GeneratedClientMixin.set_ratio.__cmux_command__ = COMMANDS['set-ratio']
GeneratedClientMixin.set_split_ratio.__cmux_command__ = COMMANDS['set-split-ratio']
GeneratedClientMixin.set_viewport_pane_width.__cmux_command__ = COMMANDS['set-viewport-pane-width']
GeneratedClientMixin.set_window_title.__cmux_command__ = COMMANDS['set-window-title']
GeneratedClientMixin.shutdown_daemon.__cmux_command__ = COMMANDS['shutdown-daemon']
GeneratedClientMixin.sidebar_plugin.__cmux_command__ = COMMANDS['sidebar-plugin']
GeneratedClientMixin.split.__cmux_command__ = COMMANDS['split']
GeneratedClientMixin.subscribe.__cmux_command__ = COMMANDS['subscribe']
GeneratedClientMixin.swap_pane.__cmux_command__ = COMMANDS['swap-pane']
GeneratedClientMixin.terminal_events.__cmux_command__ = COMMANDS['terminal-events']
GeneratedClientMixin.undo_layout.__cmux_command__ = COMMANDS['undo-layout']
GeneratedClientMixin.unregister_browser_provider.__cmux_command__ = COMMANDS['unregister-browser-provider']
GeneratedClientMixin.vt_state.__cmux_command__ = COMMANDS['vt-state']
GeneratedClientMixin.wait_for.__cmux_command__ = COMMANDS['wait-for']
GeneratedClientMixin.zoom_pane.__cmux_command__ = COMMANDS['zoom-pane']

__all__ = ["GeneratedClientMixin"]
