# Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
# Source: cmux-tui/spec/sdk-schema.json
from __future__ import annotations

import dataclasses
from enum import Enum
from typing import Any, Dict, Mapping

from . import models
from ._schema import SCHEMA


class ProtocolDecodeError(ValueError):
    pass


MODEL_BY_PATH = {
    'types/AgentRecord': models.AgentRecord,
    'types/AppliedPane': models.AppliedPane,
    'types/ApplyLayoutResult': models.ApplyLayoutResult,
    'types/AttachedViewOutcomeResult': models.AttachedViewOutcomeResult,
    'types/AttachedViewResizeResult': models.AttachedViewResizeResult,
    'types/BrowserFrame': models.BrowserFrame,
    'types/BrowserProviderSnapshot': models.BrowserProviderSnapshot,
    'types/BrowserProviderTarget': models.BrowserProviderTarget,
    'types/BrowserProviderUnregisterResult': models.BrowserProviderUnregisterResult,
    'types/CellPixelFailure': models.CellPixelFailure,
    'types/CellPixelResize': models.CellPixelResize,
    'types/CellPixelSurface': models.CellPixelSurface,
    'types/ClientInfo': models.ClientInfo,
    'types/ClientSize': models.ClientSize,
    'types/CloseTerminalResult': models.CloseTerminalResult,
    'types/CopyResult': models.CopyResult,
    'types/DeadPane': models.DeadPane,
    'types/DeclarativeLayout/variants/leaf': models.DeclarativeLayoutLeaf,
    'types/DeclarativeLayout/variants/split': models.DeclarativeLayoutSplit,
    'types/DeclarativeLayout/variants/stack': models.DeclarativeLayoutStack,
    'types/EmptyResult': models.EmptyResult,
    'types/ExportLayoutResult': models.ExportLayoutResult,
    'types/ExportedPane': models.ExportedPane,
    'types/FocusDirectionResult': models.FocusDirectionResult,
    'types/FrontendJournalEvent/variants/focus': models.FrontendJournalEventFocus,
    'types/FrontendJournalEvent/variants/resize': models.FrontendJournalEventResize,
    'types/FrontendJournalEvent/variants/viewport': models.FrontendJournalEventViewport,
    'types/FrontendProjection': models.FrontendProjection,
    'types/GetCellPixelsResult': models.GetCellPixelsResult,
    'types/IdMapping': models.IdMapping,
    'types/IdentifyResult': models.IdentifyResult,
    'types/IdsResult': models.IdsResult,
    'types/KittyGraphicsState': models.KittyGraphicsState,
    'types/KittyImageAlias': models.KittyImageAlias,
    'types/Layout/variants/leaf': models.LayoutLeaf,
    'types/Layout/variants/split': models.LayoutSplit,
    'types/Layout/variants/stack': models.LayoutStack,
    'types/LayoutUndoConfirmationRequired': models.LayoutUndoConfirmationRequired,
    'types/LayoutUndoUndone': models.LayoutUndoUndone,
    'types/ListAgentsResult': models.ListAgentsResult,
    'types/ListTerminalsResult': models.ListTerminalsResult,
    'types/LivePane': models.LivePane,
    'types/MintTerminalRendererResult': models.MintTerminalRendererResult,
    'types/MoveTerminalResult': models.MoveTerminalResult,
    'types/NotificationMarker': models.NotificationMarker,
    'types/NotifyResult': models.NotifyResult,
    'types/PaneNeighborResult': models.PaneNeighborResult,
    'types/PingResult': models.PingResult,
    'types/ProcessInfoResult': models.ProcessInfoResult,
    'types/ProviderWorkspaceMutationResult': models.ProviderWorkspaceMutationResult,
    'types/ReadScreenResult': models.ReadScreenResult,
    'types/ReadScrollbackResult': models.ReadScrollbackResult,
    'types/RenderCursor': models.RenderCursor,
    'types/RenderGraphicImage': models.RenderGraphicImage,
    'types/RenderGraphicPlacement': models.RenderGraphicPlacement,
    'types/RenderGraphics': models.RenderGraphics,
    'types/RenderGraphicsDelta': models.RenderGraphicsDelta,
    'types/RenderRow': models.RenderRow,
    'types/RenderRun': models.RenderRun,
    'types/ReportAgentResult': models.ReportAgentResult,
    'types/ResizeSurfaceResult': models.ResizeSurfaceResult,
    'types/ResolveTerminalResult': models.ResolveTerminalResult,
    'types/ResourceSelectors': models.ResourceSelectors,
    'types/RunResult': models.RunResult,
    'types/Screen': models.Screen,
    'types/SetCellPixelsResult': models.SetCellPixelsResult,
    'types/ShutdownDaemonResult': models.ShutdownDaemonResult,
    'types/SidebarPluginResult': models.SidebarPluginResult,
    'types/Size': models.Size,
    'types/SurfaceResult': models.SurfaceResult,
    'types/Tab': models.Tab,
    'types/TerminalColors': models.TerminalColors,
    'types/TerminalEventsResult': models.TerminalEventsResult,
    'types/TerminalExit': models.TerminalExit,
    'types/TerminalExitOutcome/variants/exit': models.TerminalExitOutcomeExit,
    'types/TerminalExitOutcome/variants/signal': models.TerminalExitOutcomeSignal,
    'types/TerminalExitOutcome/variants/unknown': models.TerminalExitOutcomeUnknown,
    'types/TerminalKeyInput': models.TerminalKeyInput,
    'types/TerminalModifiers': models.TerminalModifiers,
    'types/TerminalPlacement': models.TerminalPlacement,
    'types/TerminalRecord': models.TerminalRecord,
    'types/TerminalRegistryEvent': models.TerminalRegistryEvent,
    'types/Tree': models.Tree,
    'types/VtStateResult': models.VtStateResult,
    'types/WaitForResult': models.WaitForResult,
    'types/Workspace': models.Workspace,
    'types/WorkspaceMutationResult': models.WorkspaceMutationResult,
    'types/ZoomPaneResult': models.ZoomPaneResult,
    'commands/apply-layout/request': models.ApplyLayoutRequest,
    'commands/attach-surface/request': models.AttachSurfaceRequest,
    'commands/browser-activate/request': models.BrowserActivateRequest,
    'commands/browser-back/request': models.BrowserBackRequest,
    'commands/browser-forward/request': models.BrowserForwardRequest,
    'commands/browser-frame-presented/request': models.BrowserFramePresentedRequest,
    'commands/browser-insert-text/request': models.BrowserInsertTextRequest,
    'commands/browser-key/request': models.BrowserKeyRequest,
    'commands/browser-key-press/request': models.BrowserKeyPressRequest,
    'commands/browser-mouse/request': models.BrowserMouseRequest,
    'commands/browser-mouse-guarded/request': models.BrowserMouseGuardedRequest,
    'commands/browser-navigate/request': models.BrowserNavigateRequest,
    'commands/browser-reload/request': models.BrowserReloadRequest,
    'commands/browser-wheel/request': models.BrowserWheelRequest,
    'commands/browser-wheel-guarded/request': models.BrowserWheelGuardedRequest,
    'commands/clear-history/request': models.ClearHistoryRequest,
    'commands/clear-window-title/request': models.ClearWindowTitleRequest,
    'commands/client-focus/request': models.ClientFocusRequest,
    'commands/client-focus/result': models.ClientFocusResult,
    'commands/close-pane/request': models.ClosePaneRequest,
    'commands/close-provider-managed-workspace/request': models.CloseProviderManagedWorkspaceRequest,
    'commands/close-screen/request': models.CloseScreenRequest,
    'commands/close-surface/request': models.CloseSurfaceRequest,
    'commands/close-terminal/request': models.CloseTerminalRequest,
    'commands/close-workspace/request': models.CloseWorkspaceRequest,
    'commands/copy/request': models.CopyRequest,
    'commands/create-surface-with-receipt/request': models.CreateSurfaceWithReceiptRequest,
    'commands/create-terminal/request': models.CreateTerminalRequest,
    'commands/create-workspace/request': models.CreateWorkspaceRequest,
    'commands/detach-attached-view/request': models.DetachAttachedViewRequest,
    'commands/detach-client/request': models.DetachClientRequest,
    'commands/export-layout/request': models.ExportLayoutRequest,
    'commands/focus-direction/request': models.FocusDirectionRequest,
    'commands/focus-pane/request': models.FocusPaneRequest,
    'commands/get-browser-provider/request': models.GetBrowserProviderRequest,
    'commands/get-cell-pixels/request': models.GetCellPixelsRequest,
    'commands/get-frontend-projection/request': models.GetFrontendProjectionRequest,
    'commands/identify/request': models.IdentifyRequest,
    'commands/ids/request': models.IdsRequest,
    'commands/journal-frontend-event/request': models.JournalFrontendEventRequest,
    'commands/journal-frontend-event/result': models.JournalFrontendEventResult,
    'commands/list-agents/request': models.ListAgentsRequest,
    'commands/list-clients/request': models.ListClientsRequest,
    'commands/list-terminals/request': models.ListTerminalsRequest,
    'commands/list-workspaces/request': models.ListWorkspacesRequest,
    'commands/mark-workspaces-provider-managed/request': models.MarkWorkspacesProviderManagedRequest,
    'commands/mint-terminal-renderer/request': models.MintTerminalRendererRequest,
    'commands/mint-terminal-renderer-by-terminal/request': models.MintTerminalRendererByTerminalRequest,
    'commands/move-tab/request': models.MoveTabRequest,
    'commands/move-terminal/request': models.MoveTerminalRequest,
    'commands/move-workspace/request': models.MoveWorkspaceRequest,
    'commands/new-browser-tab/request': models.NewBrowserTabRequest,
    'commands/new-pane/request': models.NewPaneRequest,
    'commands/new-pane-right/request': models.NewPaneRightRequest,
    'commands/new-screen/request': models.NewScreenRequest,
    'commands/new-tab/request': models.NewTabRequest,
    'commands/new-workspace/request': models.NewWorkspaceRequest,
    'commands/notify/request': models.NotifyRequest,
    'commands/pairing-response/request': models.PairingResponseRequest,
    'commands/pane-neighbor/request': models.PaneNeighborRequest,
    'commands/ping/request': models.PingRequest,
    'commands/process-info/request': models.ProcessInfoRequest,
    'commands/put-frontend-projection/request': models.PutFrontendProjectionRequest,
    'commands/read-screen/request': models.ReadScreenRequest,
    'commands/read-scrollback/request': models.ReadScrollbackRequest,
    'commands/register-browser-provider/request': models.RegisterBrowserProviderRequest,
    'commands/release-attached-view-size/request': models.ReleaseAttachedViewSizeRequest,
    'commands/release-surface-size/request': models.ReleaseSurfaceSizeRequest,
    'commands/reload-config/request': models.ReloadConfigRequest,
    'commands/reload-config/result': models.ReloadConfigResult,
    'commands/rename-pane/request': models.RenamePaneRequest,
    'commands/rename-provider-managed-workspace/request': models.RenameProviderManagedWorkspaceRequest,
    'commands/rename-screen/request': models.RenameScreenRequest,
    'commands/rename-surface/request': models.RenameSurfaceRequest,
    'commands/rename-workspace/request': models.RenameWorkspaceRequest,
    'commands/report-agent/request': models.ReportAgentRequest,
    'commands/report-focus/request': models.ReportFocusRequest,
    'commands/resize-attached-view/request': models.ResizeAttachedViewRequest,
    'commands/resize-surface/request': models.ResizeSurfaceRequest,
    'commands/resolve-terminal/request': models.ResolveTerminalRequest,
    'commands/run/request': models.RunRequest,
    'commands/scroll-surface/request': models.ScrollSurfaceRequest,
    'commands/select-screen/request': models.SelectScreenRequest,
    'commands/select-tab/request': models.SelectTabRequest,
    'commands/select-workspace/request': models.SelectWorkspaceRequest,
    'commands/send/request': models.SendRequest,
    'commands/send-key/request': models.SendKeyRequest,
    'commands/set-cell-pixels/request': models.SetCellPixelsRequest,
    'commands/set-client-info/request': models.SetClientInfoRequest,
    'commands/set-client-sizing/request': models.SetClientSizingRequest,
    'commands/set-default-colors/request': models.SetDefaultColorsRequest,
    'commands/set-ratio/request': models.SetRatioRequest,
    'commands/set-split-ratio/request': models.SetSplitRatioRequest,
    'commands/set-viewport-pane-width/request': models.SetViewportPaneWidthRequest,
    'commands/set-window-title/request': models.SetWindowTitleRequest,
    'commands/shutdown-daemon/request': models.ShutdownDaemonRequest,
    'commands/sidebar-plugin/request': models.SidebarPluginRequest,
    'commands/split/request': models.SplitRequest,
    'commands/subscribe/request': models.SubscribeRequest,
    'commands/swap-pane/request': models.SwapPaneRequest,
    'commands/terminal-events/request': models.TerminalEventsRequest,
    'commands/undo-layout/request': models.UndoLayoutRequest,
    'commands/unregister-browser-provider/request': models.UnregisterBrowserProviderRequest,
    'commands/vt-state/request': models.VtStateRequest,
    'commands/wait-for/request': models.WaitForRequest,
    'commands/zoom-pane/request': models.ZoomPaneRequest,
    'events/agent-changed/payload': models.AgentChangedEvent,
    'events/bell/payload': models.BellEvent,
    'events/browser-state/payload': models.BrowserStateEvent,
    'events/client-attached/payload': models.ClientAttachedEvent,
    'events/client-changed/payload': models.ClientChangedEvent,
    'events/client-detached/payload': models.ClientDetachedEvent,
    'events/client-list-invalidated/payload': models.ClientListInvalidatedEvent,
    'events/colors-changed/payload': models.ColorsChangedEvent,
    'events/config-reload-requested/payload': models.ConfigReloadRequestedEvent,
    'events/detached/payload': models.DetachedEvent,
    'events/empty/payload': models.EmptyEvent,
    'events/frame/payload': models.FrameEvent,
    'events/frontend-projection-changed/payload': models.FrontendProjectionChangedEvent,
    'events/graphics-status/payload': models.GraphicsStatusEvent,
    'events/layout-changed/payload': models.LayoutChangedEvent,
    'events/notification/payload': models.NotificationEvent,
    'events/output/payload': models.OutputEvent,
    'events/overflow/payload': models.OverflowEvent,
    'events/pairing-requested/payload': models.PairingRequestedEvent,
    'events/pairing-resolved/payload': models.PairingResolvedEvent,
    'events/pane-added/payload': models.PaneAddedEvent,
    'events/pane-closed/payload': models.PaneClosedEvent,
    'events/render-delta/payload': models.RenderDeltaEvent,
    'events/render-state/payload': models.RenderStateEvent,
    'events/resized/payload': models.ResizedEvent,
    'events/screen-added/payload': models.ScreenAddedEvent,
    'events/screen-closed/payload': models.ScreenClosedEvent,
    'events/screen-renamed/payload': models.ScreenRenamedEvent,
    'events/scroll-changed/payload': models.ScrollChangedEvent,
    'events/status/payload': models.StatusEvent,
    'events/surface-exited/payload': models.SurfaceExitedEvent,
    'events/surface-output/payload': models.SurfaceOutputEvent,
    'events/surface-resize-failed/payload': models.SurfaceResizeFailedEvent,
    'events/surface-resized/payload': models.SurfaceResizedEvent,
    'events/tab-added/payload': models.TabAddedEvent,
    'events/tab-closed/payload': models.TabClosedEvent,
    'events/tab-renamed/payload': models.TabRenamedEvent,
    'events/terminal-registry-changed/payload': models.TerminalRegistryChangedEvent,
    'events/title-changed/payload': models.TitleChangedEvent,
    'events/tree-changed/payload': models.TreeChangedEvent,
    'events/vt-state/payload': models.VtStateEvent,
    'events/window-title-requested/payload': models.WindowTitleRequestedEvent,
    'events/workspace-added/payload': models.WorkspaceAddedEvent,
    'events/workspace-closed/payload': models.WorkspaceClosedEvent,
    'events/workspace-moved/payload': models.WorkspaceMovedEvent,
    'events/workspace-renamed/payload': models.WorkspaceRenamedEvent
}

ENUM_BY_PATH = {
    'types/AgentReportSource': models.AgentReportSource,
    'types/AgentSource': models.AgentSource,
    'types/AgentState': models.AgentState,
    'types/BrowserProviderAuthentication': models.BrowserProviderAuthentication,
    'types/ClientTransport': models.ClientTransport,
    'types/CursorStyle': models.CursorStyle,
    'types/FrontendFocusTarget': models.FrontendFocusTarget,
    'types/NotificationLevel': models.NotificationLevel,
    'types/PaneDirection': models.PaneDirection,
    'types/RenderGraphicFormat': models.RenderGraphicFormat,
    'types/RenderUnderline': models.RenderUnderline,
    'types/SplitDirection': models.SplitDirection,
    'types/TerminalKey': models.TerminalKey,
    'types/TerminalKeyAction': models.TerminalKeyAction,
    'types/TerminalLifecycle': models.TerminalLifecycle,
    'types/ViewAttachmentOutcome': models.ViewAttachmentOutcome
}

PYTHON_FIELD_NAMES = {
    'bytes': 'bytes_data',
    'self': 'is_self'
}


def _at(path: str) -> Mapping[str, Any]:
    value: Any = SCHEMA
    for part in path.split("/"):
        value = value[int(part)] if isinstance(value, list) else value[part]
    return value


def _validate_scalar(name: str, value: Any) -> Any:
    if name == "string":
        if not isinstance(value, str):
            raise ProtocolDecodeError("expected string")
        return value
    if name == "boolean":
        if not isinstance(value, bool):
            raise ProtocolDecodeError("expected boolean")
        return value
    if name.startswith("float"):
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ProtocolDecodeError("expected number")
        return float(value)
    if isinstance(value, bool) or not isinstance(value, int):
        raise ProtocolDecodeError("expected integer")
    bounds = {
        "int32": (-(2**31), 2**31 - 1),
        "uint16": (0, 2**16 - 1),
        "uint32": (0, 2**32 - 1),
        "int64": (-(2**63), 2**63 - 1),
        "uint64": (0, 2**64 - 1),
    }
    low, high = bounds[name]
    if not low <= value <= high:
        raise ProtocolDecodeError(f"{name} value is out of range")
    return value


def _validate_constraints(value: Any, constraints: Any) -> None:
    for constraint in constraints or ():
        if not isinstance(constraint, Mapping):
            continue
        if "minimum" in constraint and value < constraint["minimum"]:
            raise ProtocolDecodeError(f"value is below minimum {constraint['minimum']}")
        if "maximum" in constraint and value > constraint["maximum"]:
            raise ProtocolDecodeError(f"value exceeds maximum {constraint['maximum']}")
        if "min_length" in constraint and len(value) < constraint["min_length"]:
            raise ProtocolDecodeError("value is too short")
        if "max_length" in constraint and len(value) > constraint["max_length"]:
            raise ProtocolDecodeError("value is too long")


def _decode_field(field: Mapping[str, Any], value: Any, path: str) -> Any:
    if value is None:
        if field["nullable"]:
            return None
        raise ProtocolDecodeError(f"{path} cannot be null")
    decoded = _decode(field["type"], value, path)
    _validate_constraints(decoded, field.get("constraints"))
    return decoded


def _decode(expression: Mapping[str, Any], value: Any, path: str) -> Any:
    kind = expression["kind"]
    if kind == "scalar":
        return _validate_scalar(expression["name"], value)
    if kind == "literal":
        if value != expression["value"]:
            raise ProtocolDecodeError(f"expected literal {expression['value']!r}")
        return value
    if kind == "enum":
        if value not in expression["values"]:
            raise ProtocolDecodeError(f"unknown enum value {value!r}")
        enum_type = ENUM_BY_PATH.get(path)
        return enum_type(value) if enum_type is not None else value
    if kind == "ref":
        return _decode(SCHEMA["types"][expression["name"]], value, f"types/{expression['name']}")
    if kind == "alias":
        return _decode(expression["target"], value, f"{path}/target")
    if kind == "array":
        if not isinstance(value, list):
            raise ProtocolDecodeError("expected array")
        result = [
            _decode(expression["items"], item, f"{path}/items")
            for item in value
        ]
        if "min_items" in expression and len(result) < expression["min_items"]:
            raise ProtocolDecodeError("array has too few items")
        if "max_items" in expression and len(result) > expression["max_items"]:
            raise ProtocolDecodeError("array has too many items")
        return result
    if kind == "map":
        if not isinstance(value, Mapping) or not all(isinstance(key, str) for key in value):
            raise ProtocolDecodeError("expected string-keyed object")
        return {
            key: _decode(expression["values"], item, f"{path}/values")
            for key, item in value.items()
        }
    if kind == "opaque_json":
        return value
    if kind == "tagged_union":
        if not isinstance(value, Mapping):
            raise ProtocolDecodeError("expected tagged object")
        variant = value.get(expression["tag"])
        if variant not in expression["variants"]:
            raise ProtocolDecodeError(f"unknown {expression['tag']} variant {variant!r}")
        return _decode(
            expression["variants"][variant],
            value,
            f"{path}/variants/{variant}",
        )
    if kind == "untagged_union":
        failures = []
        for index, variant in enumerate(expression["variants"]):
            try:
                return _decode(variant, value, f"{path}/variants/{index}")
            except (ProtocolDecodeError, TypeError, ValueError) as error:
                failures.append(str(error))
        raise ProtocolDecodeError("value did not match union: " + "; ".join(failures))
    if kind != "object":
        raise ProtocolDecodeError(f"unsupported schema kind {kind!r}")
    if not isinstance(value, Mapping):
        raise ProtocolDecodeError("expected object")
    kwargs: Dict[str, Any] = {}
    known = set()
    for wire_name, field in expression["fields"].items():
        candidates = (wire_name, *field.get("aliases", ()))
        present = next((candidate for candidate in candidates if candidate in value), None)
        known.update(candidate for candidate in candidates if candidate in value)
        if present is None:
            if field["presence"] == "required":
                raise ProtocolDecodeError(f"missing required field {wire_name!r}")
            continue
        python_name = PYTHON_FIELD_NAMES.get(wire_name, wire_name.replace("-", "_"))
        kwargs[python_name] = _decode_field(
            field, value[present], f"{path}/fields/{wire_name}/type"
        )
    extras = {key: item for key, item in value.items() if key not in known}
    if extras and not expression["additional_properties"]:
        raise ProtocolDecodeError(f"unexpected fields: {', '.join(sorted(extras))}")
    model = MODEL_BY_PATH.get(path)
    if model is None:
        result = dict(kwargs)
        result.update(extras)
        return result
    field_names = {item.name for item in dataclasses.fields(model)}
    if "extra" in field_names:
        kwargs["extra"] = extras
    if "raw" in field_names:
        kwargs["raw"] = dict(value)
    return model(**kwargs)


def _encode(expression: Mapping[str, Any], value: Any, path: str) -> Any:
    if value is models.MISSING:
        return models.MISSING
    kind = expression["kind"]
    if isinstance(value, Enum):
        value = value.value
    if kind == "ref":
        return _encode(SCHEMA["types"][expression["name"]], value, f"types/{expression['name']}")
    if kind == "alias":
        return _encode(expression["target"], value, f"{path}/target")
    if kind == "enum":
        if value not in expression["values"]:
            raise ProtocolDecodeError(f"unknown enum value {value!r}")
        return value
    if kind in {"scalar", "literal"}:
        return _decode(expression, value, path)
    if kind == "array":
        if not isinstance(value, (list, tuple)):
            raise ProtocolDecodeError("expected array")
        return [
            _encode(expression["items"], item, f"{path}/items")
            for item in value
        ]
    if kind == "map":
        if not isinstance(value, Mapping):
            raise ProtocolDecodeError("expected map")
        return {
            str(key): _encode(expression["values"], item, f"{path}/values")
            for key, item in value.items()
        }
    if kind == "opaque_json":
        return value
    if kind == "tagged_union":
        if dataclasses.is_dataclass(value):
            raw = _encode(_at(value.__cmux_schema_path__), value, value.__cmux_schema_path__)
        elif isinstance(value, Mapping):
            raw = dict(value)
        else:
            raise ProtocolDecodeError("expected tagged object")
        variant = raw.get(expression["tag"])
        if variant not in expression["variants"]:
            raise ProtocolDecodeError(f"unknown {expression['tag']} variant {variant!r}")
        return _encode(
            expression["variants"][variant], value, f"{path}/variants/{variant}"
        )
    if kind == "untagged_union":
        for index, variant in enumerate(expression["variants"]):
            try:
                return _encode(variant, value, f"{path}/variants/{index}")
            except (ProtocolDecodeError, TypeError, ValueError):
                pass
        raise ProtocolDecodeError("value did not match union")
    if kind != "object":
        raise ProtocolDecodeError(f"unsupported schema kind {kind!r}")
    if dataclasses.is_dataclass(value):
        raw: Dict[str, Any] = {}
        for item in dataclasses.fields(value):
            if item.metadata.get("cmux_skip"):
                continue
            item_value = getattr(value, item.name)
            if item.metadata.get("cmux_extra"):
                raw.update(item_value)
                continue
            if item_value is models.MISSING:
                continue
            wire_name = item.metadata.get("wire_name", item.name)
            field = expression["fields"][wire_name]
            if item_value is None:
                if not field["nullable"]:
                    raise ProtocolDecodeError(f"{wire_name} cannot be null")
                raw[wire_name] = None
            else:
                _validate_constraints(item_value, field.get("constraints"))
                raw[wire_name] = _encode(
                    field["type"], item_value, f"{path}/fields/{wire_name}/type"
                )
        value = raw
    if not isinstance(value, Mapping):
        raise ProtocolDecodeError("expected object")
    result: Dict[str, Any] = {}
    for wire_name, field in expression["fields"].items():
        if wire_name not in value:
            if field["presence"] == "required":
                raise ProtocolDecodeError(f"missing required field {wire_name!r}")
            continue
        item = value[wire_name]
        if item is models.MISSING:
            continue
        if item is None:
            if not field["nullable"]:
                raise ProtocolDecodeError(f"{wire_name} cannot be null")
            result[wire_name] = None
        else:
            _validate_constraints(item, field.get("constraints"))
            result[wire_name] = _encode(
                field["type"], item, f"{path}/fields/{wire_name}/type"
            )
    if expression["additional_properties"]:
        result.update({key: item for key, item in value.items() if key not in result})
    return result


def encode_request(command: str, request: Any) -> Dict[str, Any]:
    expression = SCHEMA["commands"][command]["request"]
    encoded = _encode(expression, request, f"commands/{command}/request")
    if not isinstance(encoded, dict):
        raise ProtocolDecodeError("command request must encode to an object")
    return encoded


def decode_command_result(command: str, value: Any) -> Any:
    expression = SCHEMA["commands"][command]["result"]
    return _decode(expression, value, f"commands/{command}/result")


def decode_event(value: Mapping[str, Any]) -> models.AnyEvent:
    event_name = value.get("event")
    if not isinstance(event_name, str):
        raise ProtocolDecodeError("event frame has no string event name")
    event = SCHEMA["events"].get(event_name)
    if event is None:
        return models.UnknownEvent(event=event_name, raw=dict(value))
    return _decode(event["payload"], value, f"events/{event_name}/payload")


__all__ = [
    "ProtocolDecodeError",
    "encode_request",
    "decode_command_result",
    "decode_event",
]
