# Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
# Source: cmux-tui/spec/sdk-schema.json

from __future__ import annotations

import base64
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, ClassVar, Dict, List, Literal, Mapping, Optional, Union


class MissingType:
    __slots__ = ()

    def __repr__(self) -> str:
        return "MISSING"

    def __bool__(self) -> bool:
        return False


MISSING = MissingType()


class EventBase:
    @property
    def bytes_data(self) -> Optional[bytes]:
        for name in ("data", "replay", "png"):
            value = getattr(self, name, MISSING)
            if value is not MISSING and value is not None:
                return base64.b64decode(value, validate=True)
        return None


@dataclass(frozen=True)
class UnknownEvent(EventBase):
    event: str
    raw: Mapping[str, Any]

class AgentReportSource(str, Enum):
    SOCKET = 'socket'
    HOOK = 'hook'

class AgentSource(str, Enum):
    DETECTED = 'detected'
    SOCKET = 'socket'
    HOOK = 'hook'

class AgentState(str, Enum):
    WORKING = 'working'
    BLOCKED = 'blocked'
    IDLE = 'idle'
    DONE = 'done'
    UNKNOWN = 'unknown'

class BrowserProviderAuthentication(str, Enum):
    NONE = 'none'
    BEARER = 'bearer'

class ClientTransport(str, Enum):
    LOCAL = 'local'
    UNIX = 'unix'
    WS = 'ws'

class CursorStyle(str, Enum):
    BLOCK = 'block'
    UNDERLINE = 'underline'
    BAR = 'bar'

class FrontendFocusTarget(str, Enum):
    PANE = 'pane'
    MACHINE_RAIL = 'machine_rail'
    WORKSPACE_RAIL = 'workspace_rail'
    TABS_RAIL = 'tabs_rail'
    PROJECTION_RAIL = 'projection_rail'

class NotificationLevel(str, Enum):
    INFO = 'info'
    WARNING = 'warning'
    ERROR = 'error'

class PaneDirection(str, Enum):
    LEFT = 'left'
    RIGHT = 'right'
    UP = 'up'
    DOWN = 'down'

class RenderGraphicFormat(str, Enum):
    RGB = 'rgb'
    RGBA = 'rgba'

class RenderUnderline(str, Enum):
    SINGLE = 'single'
    DOUBLE = 'double'
    CURLY = 'curly'
    DOTTED = 'dotted'
    DASHED = 'dashed'

class SplitDirection(str, Enum):
    RIGHT = 'right'
    DOWN = 'down'

class TerminalKey(str, Enum):
    UNIDENTIFIED = 'unidentified'
    BACKQUOTE = 'backquote'
    BACKSLASH = 'backslash'
    BRACKET_LEFT = 'bracket-left'
    BRACKET_RIGHT = 'bracket-right'
    COMMA = 'comma'
    DIGIT0 = 'digit0'
    DIGIT1 = 'digit1'
    DIGIT2 = 'digit2'
    DIGIT3 = 'digit3'
    DIGIT4 = 'digit4'
    DIGIT5 = 'digit5'
    DIGIT6 = 'digit6'
    DIGIT7 = 'digit7'
    DIGIT8 = 'digit8'
    DIGIT9 = 'digit9'
    EQUAL = 'equal'
    A = 'a'
    B = 'b'
    C = 'c'
    D = 'd'
    E = 'e'
    F = 'f'
    G = 'g'
    H = 'h'
    I = 'i'
    J = 'j'
    K = 'k'
    L = 'l'
    M = 'm'
    N = 'n'
    O = 'o'
    P = 'p'
    Q = 'q'
    R = 'r'
    S = 's'
    T = 't'
    U = 'u'
    V = 'v'
    W = 'w'
    X = 'x'
    Y = 'y'
    Z = 'z'
    MINUS = 'minus'
    PERIOD = 'period'
    QUOTE = 'quote'
    SEMICOLON = 'semicolon'
    SLASH = 'slash'
    BACKSPACE = 'backspace'
    ENTER = 'enter'
    SPACE = 'space'
    TAB = 'tab'
    DELETE = 'delete'
    END = 'end'
    HOME = 'home'
    INSERT = 'insert'
    PAGE_DOWN = 'page-down'
    PAGE_UP = 'page-up'
    ARROW_DOWN = 'arrow-down'
    ARROW_LEFT = 'arrow-left'
    ARROW_RIGHT = 'arrow-right'
    ARROW_UP = 'arrow-up'
    NUMPAD0 = 'numpad0'
    NUMPAD1 = 'numpad1'
    NUMPAD2 = 'numpad2'
    NUMPAD3 = 'numpad3'
    NUMPAD4 = 'numpad4'
    NUMPAD5 = 'numpad5'
    NUMPAD6 = 'numpad6'
    NUMPAD7 = 'numpad7'
    NUMPAD8 = 'numpad8'
    NUMPAD9 = 'numpad9'
    NUMPAD_ADD = 'numpad-add'
    NUMPAD_BACKSPACE = 'numpad-backspace'
    NUMPAD_COMMA = 'numpad-comma'
    NUMPAD_DECIMAL = 'numpad-decimal'
    NUMPAD_DIVIDE = 'numpad-divide'
    NUMPAD_ENTER = 'numpad-enter'
    NUMPAD_EQUAL = 'numpad-equal'
    NUMPAD_MULTIPLY = 'numpad-multiply'
    NUMPAD_SUBTRACT = 'numpad-subtract'
    NUMPAD_UP = 'numpad-up'
    NUMPAD_DOWN = 'numpad-down'
    NUMPAD_RIGHT = 'numpad-right'
    NUMPAD_LEFT = 'numpad-left'
    NUMPAD_BEGIN = 'numpad-begin'
    NUMPAD_HOME = 'numpad-home'
    NUMPAD_END = 'numpad-end'
    NUMPAD_INSERT = 'numpad-insert'
    NUMPAD_DELETE = 'numpad-delete'
    NUMPAD_PAGE_UP = 'numpad-page-up'
    NUMPAD_PAGE_DOWN = 'numpad-page-down'
    ESCAPE = 'escape'
    F1 = 'f1'
    F2 = 'f2'
    F3 = 'f3'
    F4 = 'f4'
    F5 = 'f5'
    F6 = 'f6'
    F7 = 'f7'
    F8 = 'f8'
    F9 = 'f9'
    F10 = 'f10'
    F11 = 'f11'
    F12 = 'f12'
    F13 = 'f13'
    F14 = 'f14'
    F15 = 'f15'
    F16 = 'f16'
    F17 = 'f17'
    F18 = 'f18'
    F19 = 'f19'
    F20 = 'f20'

class TerminalKeyAction(str, Enum):
    PRESS = 'press'
    RELEASE = 'release'
    REPEAT = 'repeat'

class TerminalLifecycle(str, Enum):
    LAUNCHING = 'launching'
    ADOPTING = 'adopting'
    RUNNING = 'running'
    EXITED = 'exited'
    TOMBSTONED = 'tombstoned'

class ViewAttachmentOutcome(str, Enum):
    APPLIED = 'applied'
    PASSIVE = 'passive'
    SUPERSEDED = 'superseded'


@dataclass(frozen=True)
class AgentRecord:
    __cmux_schema_path__: ClassVar[str] = 'types/AgentRecord'
    surface: Id
    session: Union[str, None]
    source: AgentSource
    state: AgentState
    updated_at_ms: int


@dataclass(frozen=True)
class AppliedPane:
    __cmux_schema_path__: ClassVar[str] = 'types/AppliedPane'
    surface: Id
    pane: Id


@dataclass(frozen=True)
class ApplyLayoutResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ApplyLayoutResult'
    screen: Id
    panes: List[AppliedPane]


@dataclass(frozen=True)
class AttachedViewOutcomeResult:
    __cmux_schema_path__: ClassVar[str] = 'types/AttachedViewOutcomeResult'
    outcome: ViewAttachmentOutcome


@dataclass(frozen=True)
class AttachedViewResizeResult:
    __cmux_schema_path__: ClassVar[str] = 'types/AttachedViewResizeResult'
    accepted: bool
    outcome: ViewAttachmentOutcome
    reservation_id: Union[int, None]


@dataclass(frozen=True)
class BrowserFrame:
    __cmux_schema_path__: ClassVar[str] = 'types/BrowserFrame'
    data: Base64
    height: int
    seq: int
    width: int


@dataclass(frozen=True)
class BrowserProviderSnapshot:
    __cmux_schema_path__: ClassVar[str] = 'types/BrowserProviderSnapshot'
    available: bool
    revision: int
    targets: List[BrowserProviderTarget]
    authentication: Union[BrowserProviderAuthentication, MissingType] = field(default=MISSING)
    clients: Union[int, MissingType] = field(default=MISSING)
    endpoint: Union[str, MissingType] = field(default=MISSING)
    provider_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserProviderTarget:
    __cmux_schema_path__: ClassVar[str] = 'types/BrowserProviderTarget'
    tab_id: str
    target_id: str


@dataclass(frozen=True)
class BrowserProviderUnregisterResult:
    __cmux_schema_path__: ClassVar[str] = 'types/BrowserProviderUnregisterResult'
    removed: bool


@dataclass(frozen=True)
class CellPixelFailure:
    __cmux_schema_path__: ClassVar[str] = 'types/CellPixelFailure'
    surface: Id
    error: str


@dataclass(frozen=True)
class CellPixelResize:
    __cmux_schema_path__: ClassVar[str] = 'types/CellPixelResize'
    surface: Id
    cols: int
    reservation_id: int
    rows: int


@dataclass(frozen=True)
class CellPixelSurface:
    __cmux_schema_path__: ClassVar[str] = 'types/CellPixelSurface'
    surface: Id
    height_px: int
    width_px: int


@dataclass(frozen=True)
class ClientInfo:
    __cmux_schema_path__: ClassVar[str] = 'types/ClientInfo'
    client: int
    attached: List[Id]
    connected_seconds: int
    kind: Union[str, None]
    name: Union[str, None]
    is_self: bool = field(metadata={'wire_name': 'self'})
    sizes: List[ClientSize]
    transport: ClientTransport


@dataclass(frozen=True)
class ClientSize:
    __cmux_schema_path__: ClassVar[str] = 'types/ClientSize'
    surface: Id
    cols: Union[int, None]
    rows: Union[int, None]
    size_participating: bool


@dataclass(frozen=True)
class CloseTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/CloseTerminalResult'
    surface: Union[Id, None]
    terminal_id: str
    already_closed: bool
    closed: Literal[True]
    generation: str
    registry_id: str
    terminal_incarnation: Union[str, None]
    terminal_revision: int


@dataclass(frozen=True)
class CopyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/CopyResult'
    mode: Literal['screen', 'selection', 'scrollback']
    text: str


@dataclass(frozen=True)
class DeadPane:
    __cmux_schema_path__: ClassVar[str] = 'types/DeadPane'
    dead: Literal[True]
    id: Id


@dataclass(frozen=True)
class DeclarativeLayoutLeaf:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/leaf'
    type: Literal['leaf']
    command: Union[List[str], None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class DeclarativeLayoutSplit:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/split'
    a: DeclarativeLayout
    b: DeclarativeLayout
    dir: SplitDirection
    ratio: float
    type: Literal['split']


@dataclass(frozen=True)
class DeclarativeLayoutStack:
    __cmux_schema_path__: ClassVar[str] = 'types/DeclarativeLayout/variants/stack'
    expanded: Id
    panes: List[Id]
    type: Literal['stack']


@dataclass(frozen=True)
class EmptyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/EmptyResult'
    pass


@dataclass(frozen=True)
class ExportLayoutResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ExportLayoutResult'
    layout: Layout
    panes: List[ExportedPane]


@dataclass(frozen=True)
class ExportedPane:
    __cmux_schema_path__: ClassVar[str] = 'types/ExportedPane'
    pane: Id
    surfaces: List[Id]


@dataclass(frozen=True)
class FocusDirectionResult:
    __cmux_schema_path__: ClassVar[str] = 'types/FocusDirectionResult'
    pane: Id


@dataclass(frozen=True)
class FrontendJournalEventFocus:
    __cmux_schema_path__: ClassVar[str] = 'types/FrontendJournalEvent/variants/focus'
    event_id: str
    frontend_projection_id: str
    generation: str
    kind: Literal['focus']
    target: FrontendFocusTarget
    content_id: Union[str, None, MissingType] = field(default=MISSING)
    pane_id: Union[str, None, MissingType] = field(default=MISSING)
    screen_id: Union[str, None, MissingType] = field(default=MISSING)
    tab_id: Union[str, None, MissingType] = field(default=MISSING)
    workspace_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FrontendJournalEventResize:
    __cmux_schema_path__: ClassVar[str] = 'types/FrontendJournalEvent/variants/resize'
    cell_height: int
    cell_width: int
    cols: int
    event_id: str
    frontend_projection_id: str
    generation: str
    kind: Literal['resize']
    rows: int


@dataclass(frozen=True)
class FrontendJournalEventViewport:
    __cmux_schema_path__: ClassVar[str] = 'types/FrontendJournalEvent/variants/viewport'
    event_id: str
    frontend_projection_id: str
    generation: str
    kind: Literal['viewport']
    offset: int
    settled: bool
    target: int
    screen_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FrontendProjection:
    __cmux_schema_path__: ClassVar[str] = 'types/FrontendProjection'
    frontend: str
    projection: Union[JsonValue, None]
    projection_revision: int
    schema_version: int
    scope: str
    subject_key: str
    replayed: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class GetCellPixelsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/GetCellPixelsResult'
    height_px: int
    surfaces: List[CellPixelSurface]
    width_px: int


@dataclass(frozen=True)
class IdMapping:
    __cmux_schema_path__: ClassVar[str] = 'types/IdMapping'
    id: Id
    kind: Literal['workspace', 'screen', 'pane', 'surface']
    short_id: str


@dataclass(frozen=True)
class IdentifyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/IdentifyResult'
    app: Literal['cmux-tui']
    daemon_handoff: Literal[1]
    generation: str
    pid: int
    protocol: int
    registry_id: str
    session: str
    terminal_revision: int
    version: str
    workspace_revision: int
    build_commit: Union[str, None, MissingType] = field(default=MISSING)
    capabilities: Union[List[str], MissingType] = field(default=MISSING)
    ghostty_commit: Union[str, None, MissingType] = field(default=MISSING)
    lifecycle_ready: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class IdsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/IdsResult'
    ids: List[IdMapping]


@dataclass(frozen=True)
class KittyGraphicsState:
    __cmux_schema_path__: ClassVar[str] = 'types/KittyGraphicsState'
    alternate_next_image_id: int
    alternate_replay_next_image_id: int
    image_bytes: int
    images: int
    inflight_bytes: int
    placements: int
    primary_next_image_id: int
    primary_replay_next_image_id: int
    replay_cursor_offset: int


@dataclass(frozen=True)
class KittyImageAlias:
    __cmux_schema_path__: ClassVar[str] = 'types/KittyImageAlias'
    image_id: int
    image_number: int


@dataclass(frozen=True)
class LayoutLeaf:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/leaf'
    pane: Id
    type: Literal['leaf']


@dataclass(frozen=True)
class LayoutSplit:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/split'
    a: Layout
    b: Layout
    dir: SplitDirection
    ratio: float
    type: Literal['split']
    split: Union[Id, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class LayoutStack:
    __cmux_schema_path__: ClassVar[str] = 'types/Layout/variants/stack'
    expanded: Id
    panes: List[Id]
    type: Literal['stack']


@dataclass(frozen=True)
class LayoutUndoConfirmationRequired:
    __cmux_schema_path__: ClassVar[str] = 'types/LayoutUndoConfirmationRequired'
    screen: Id
    closes_panes: List[Id]
    confirmation_required: Literal[True]
    revision: int
    undone: Literal[False]


@dataclass(frozen=True)
class LayoutUndoUndone:
    __cmux_schema_path__: ClassVar[str] = 'types/LayoutUndoUndone'
    screen: Id
    revision: int
    undone: Literal[True]
    confirmation_required: Union[Literal[False], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ListAgentsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ListAgentsResult'
    agents: List[AgentRecord]


@dataclass(frozen=True)
class ListTerminalsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ListTerminalsResult'
    generation: str
    registry_id: str
    terminal_revision: int
    terminals: List[TerminalRecord]


@dataclass(frozen=True)
class LivePane:
    __cmux_schema_path__: ClassVar[str] = 'types/LivePane'
    active_tab: int
    id: Id
    name: Union[str, None]
    tabs: List[Tab]
    focused_at: Union[int, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MintTerminalRendererResult:
    __cmux_schema_path__: ClassVar[str] = 'types/MintTerminalRendererResult'
    terminal_id: str
    endpoint: str
    incarnation: str
    protocol_version: int
    rights: int
    token: str
    ttl_ms: int


@dataclass(frozen=True)
class MoveTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/MoveTerminalResult'
    surface: Union[Id, None]
    pane: Union[Id, None]
    screen: Union[Id, None]
    workspace: Union[Id, None]
    terminal_id: str
    changed: bool
    generation: str
    lifecycle: TerminalLifecycle
    registry_id: str
    replayed: bool
    terminal_incarnation: Union[str, None]
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class NotificationMarker:
    __cmux_schema_path__: ClassVar[str] = 'types/NotificationMarker'
    level: NotificationLevel
    notification: Id
    unread: bool


@dataclass(frozen=True)
class NotifyResult:
    __cmux_schema_path__: ClassVar[str] = 'types/NotifyResult'
    notification: Id


@dataclass(frozen=True)
class PaneNeighborResult:
    __cmux_schema_path__: ClassVar[str] = 'types/PaneNeighborResult'
    pane: Union[Id, None]


@dataclass(frozen=True)
class PingResult:
    __cmux_schema_path__: ClassVar[str] = 'types/PingResult'
    ok: Literal[True]
    protocol: int
    version: str
    build_commit: Union[str, None, MissingType] = field(default=MISSING)
    ghostty_commit: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ProcessInfoResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ProcessInfoResult'
    command: Union[str, None]
    cwd: Union[str, None]
    pid: Union[int, None]
    foreground_cwd: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ProviderWorkspaceMutationResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ProviderWorkspaceMutationResult'
    workspace: Id
    key: str
    workspace_revision: int


@dataclass(frozen=True)
class ReadScreenResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReadScreenResult'
    text: str


@dataclass(frozen=True)
class ReadScrollbackResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReadScrollbackResult'
    epoch: int
    rows: List[RenderRow]
    start: int
    total: int


@dataclass(frozen=True)
class RenderCursor:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderCursor'
    blink: bool
    color: Union[ColorHex, None]
    style: CursorStyle
    visible: bool
    x: int
    y: int


@dataclass(frozen=True)
class RenderGraphicImage:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderGraphicImage'
    data: Base64
    format: RenderGraphicFormat
    generation: int
    height: int
    id: int
    width: int


@dataclass(frozen=True)
class RenderGraphicPlacement:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderGraphicPlacement'
    columns: int
    grid_cols: int
    grid_rows: int
    image_id: int
    ordinal: int
    pixel_height: int
    pixel_width: int
    placement_id: int
    rows: int
    source_height: int
    source_width: int
    source_x: int
    source_y: int
    viewport_col: int
    viewport_row: int
    viewport_visible: bool
    x_offset: int
    y_offset: int
    z: int
    anchor_col: Union[int, MissingType] = field(default=MISSING)
    anchor_row: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class RenderGraphics:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderGraphics'
    generation: int
    placements: List[RenderGraphicPlacement]
    images: Union[List[RenderGraphicImage], MissingType] = field(default=MISSING)
    removed_image_ids: Union[List[int], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class RenderGraphicsDelta:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderGraphicsDelta'
    generation: int
    images: Union[List[RenderGraphicImage], MissingType] = field(default=MISSING)
    placements: Union[List[RenderGraphicPlacement], MissingType] = field(default=MISSING)
    removed_image_ids: Union[List[int], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class RenderRow:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderRow'
    row: int
    runs: List[RenderRun]


@dataclass(frozen=True)
class RenderRun:
    __cmux_schema_path__: ClassVar[str] = 'types/RenderRun'
    attrs: int
    bg: Union[ColorHex, None]
    fg: Union[ColorHex, None]
    text: str
    underline: Union[RenderUnderline, MissingType] = field(default=MISSING)
    width_hint: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReportAgentResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ReportAgentResult'
    surface: Id
    session: Union[str, None]
    source: AgentReportSource
    state: AgentState


@dataclass(frozen=True)
class ResizeSurfaceResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ResizeSurfaceResult'
    accepted: bool
    reservation_id: Union[int, None]


@dataclass(frozen=True)
class ResolveTerminalResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ResolveTerminalResult'
    surface: Union[Id, None]
    terminal_id: str
    exit: Union[TerminalExit, None]
    generation: str
    launch_spec: JsonValue
    lifecycle: TerminalLifecycle
    registry_id: str
    terminal_incarnation: Union[str, None]
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class ResourceSelectors:
    __cmux_schema_path__: ClassVar[str] = 'types/ResourceSelectors'
    pane: Union[str, None, MissingType] = field(default=MISSING)
    screen: Union[str, None, MissingType] = field(default=MISSING)
    workspace: Union[str, None, MissingType] = field(default=MISSING)
    split: Union[str, None, MissingType] = field(default=MISSING)
    client: Union[str, None, MissingType] = field(default=MISSING)
    agent: Union[str, None, MissingType] = field(default=MISSING)
    browser: Union[str, None, MissingType] = field(default=MISSING)
    frontend_projection: Union[str, None, MissingType] = field(default=MISSING)
    machine: Union[str, None, MissingType] = field(default=MISSING)
    notification: Union[str, None, MissingType] = field(default=MISSING)
    pairing_request: Union[str, None, MissingType] = field(default=MISSING)
    session: Union[str, None, MissingType] = field(default=MISSING)
    sidebar_view: Union[str, None, MissingType] = field(default=MISSING)
    stream: Union[str, None, MissingType] = field(default=MISSING)
    tab: Union[str, None, MissingType] = field(default=MISSING)
    terminal: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class RunResult:
    __cmux_schema_path__: ClassVar[str] = 'types/RunResult'
    surface: Union[Id, None]
    pane: Union[Id, None]
    screen: Union[Id, None]
    workspace: Union[Id, None]
    terminal_id: str
    already_exited: bool
    exit: Union[TerminalExit, None]
    lifecycle: TerminalLifecycle
    terminal_incarnation: Union[str, None]
    terminal_revision: int


@dataclass(frozen=True)
class Screen:
    __cmux_schema_path__: ClassVar[str] = 'types/Screen'
    active: bool
    active_pane: Id
    id: Id
    layout: Layout
    name: Union[str, None]
    panes: List[Pane]
    zoomed_pane: Union[Id, None]
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetCellPixelsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SetCellPixelsResult'
    failures: List[CellPixelFailure]
    resizes: List[CellPixelResize]


@dataclass(frozen=True)
class ShutdownDaemonResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ShutdownDaemonResult'
    accepted: Literal[True]
    generation: str
    pid: int


@dataclass(frozen=True)
class SidebarPluginResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SidebarPluginResult'
    surface: Union[Id, None]
    error: Union[str, None]
    retry_after_ms: Union[int, None]


@dataclass(frozen=True)
class Size:
    __cmux_schema_path__: ClassVar[str] = 'types/Size'
    cols: int
    rows: int


@dataclass(frozen=True)
class SurfaceResult:
    __cmux_schema_path__: ClassVar[str] = 'types/SurfaceResult'
    surface: Id
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class Tab:
    __cmux_schema_path__: ClassVar[str] = 'types/Tab'
    surface: Id
    browser_source: Union[Literal['external', 'launched'], None]
    dead: bool
    kind: Literal['pty', 'browser']
    name: Union[str, None]
    size: Union[Size, None]
    title: str
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    browser_error: Union[str, None, MissingType] = field(default=MISSING)
    browser_frames_stalled: Union[bool, None, MissingType] = field(default=MISSING)
    browser_status: Union[Literal['starting', 'live', 'failed'], None, MissingType] = field(default=MISSING)
    notification: Union[NotificationMarker, None, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)
    supports_clear_history_key_fallback: Union[bool, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)
    terminal_resource_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalColors:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalColors'
    bg: Union[ColorHex, None]
    fg: Union[ColorHex, None]
    selection_bg: Union[ColorHex, None]
    selection_fg: Union[ColorHex, None]
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalEventsResult:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalEventsResult'
    events: List[TerminalRegistryEvent]
    generation: str
    registry_id: str
    terminal_revision: int


@dataclass(frozen=True)
class TerminalExit:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalExit'
    exited_at_ms: int
    outcome: TerminalExitOutcome


@dataclass(frozen=True)
class TerminalExitOutcomeExit:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalExitOutcome/variants/exit'
    code: int
    kind: Literal['exit']


@dataclass(frozen=True)
class TerminalExitOutcomeSignal:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalExitOutcome/variants/signal'
    core_dumped: bool
    kind: Literal['signal']
    signal: int


@dataclass(frozen=True)
class TerminalExitOutcomeUnknown:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalExitOutcome/variants/unknown'
    kind: Literal['unknown']
    reason: str


@dataclass(frozen=True)
class TerminalKeyInput:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalKeyInput'
    consumed_mods: TerminalModifiers
    key: TerminalKey
    macos_option_as_alt: bool
    mods: TerminalModifiers
    utf8: str
    action: Union[TerminalKeyAction, None, MissingType] = field(default=MISSING)
    base_layout_codepoint: Union[str, None, MissingType] = field(default=MISSING)
    composing: Union[bool, MissingType] = field(default=MISSING)
    shifted_codepoint: Union[str, None, MissingType] = field(default=MISSING)
    unshifted_codepoint: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalModifiers:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalModifiers'
    alt: bool
    caps_lock: bool
    control: bool
    num_lock: bool
    shift: bool
    super: bool


@dataclass(frozen=True)
class TerminalPlacement:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalPlacement'
    surface: Union[Id, None]
    pane: Union[Id, None]
    screen: Union[Id, None]
    workspace: Union[Id, None]
    terminal_id: str
    already_exited: bool
    exit: Union[TerminalExit, None]
    generation: str
    key: str
    lifecycle: TerminalLifecycle
    registry_id: str
    replayed: bool
    terminal_incarnation: Union[str, None]
    terminal_revision: int


@dataclass(frozen=True)
class TerminalRecord:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalRecord'
    terminal_id: str
    exit: Union[TerminalExit, None]
    launch_spec: JsonValue
    lifecycle: TerminalLifecycle
    terminal_incarnation: Union[str, None]
    workspace_key: str


@dataclass(frozen=True)
class TerminalRegistryEvent:
    __cmux_schema_path__: ClassVar[str] = 'types/TerminalRegistryEvent'
    terminal_id: str
    kind: str
    mutation_id: str
    origin: str
    result: JsonValue
    terminal_revision: int
    workspace_key: str


@dataclass(frozen=True)
class Tree:
    __cmux_schema_path__: ClassVar[str] = 'types/Tree'
    workspaces: List[Workspace]
    generation: Union[str, MissingType] = field(default=MISSING)
    pane_revision: Union[int, MissingType] = field(default=MISSING)
    registry_id: Union[str, MissingType] = field(default=MISSING)
    terminal_revision: Union[int, MissingType] = field(default=MISSING)
    workspace_revision: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class VtStateResult:
    __cmux_schema_path__: ClassVar[str] = 'types/VtStateResult'
    cols: int
    data: Base64
    rows: int
    kitty_graphics_state: Union[KittyGraphicsState, MissingType] = field(default=MISSING)
    kitty_image_aliases: Union[List[KittyImageAlias], MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class WaitForResult:
    __cmux_schema_path__: ClassVar[str] = 'types/WaitForResult'
    elapsed_ms: int
    matched: Literal[True]
    text: str


@dataclass(frozen=True)
class Workspace:
    __cmux_schema_path__: ClassVar[str] = 'types/Workspace'
    active: bool
    id: Id
    name: str
    screens: List[Screen]
    key: Union[str, MissingType] = field(default=MISSING)
    short_id: Union[str, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class WorkspaceMutationResult:
    __cmux_schema_path__: ClassVar[str] = 'types/WorkspaceMutationResult'
    workspace: Id
    generation: str
    index: int
    key: str
    registry_id: str
    replayed: bool
    workspace_revision: int
    changed: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ZoomPaneResult:
    __cmux_schema_path__: ClassVar[str] = 'types/ZoomPaneResult'
    pane: Id
    zoomed: bool
    zoomed_pane: Union[Id, None]


@dataclass(frozen=True)
class ApplyLayoutRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/apply-layout/request'
    layout: DeclarativeLayout
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class AttachSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/attach-surface/request'
    surface: Id
    cols: Union[int, None, MissingType] = field(default=MISSING)
    mode: Union[Literal['bytes', 'render'], None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserActivateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-activate/request'
    surface: Id


@dataclass(frozen=True)
class BrowserBackRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-back/request'
    surface: Id


@dataclass(frozen=True)
class BrowserForwardRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-forward/request'
    surface: Id


@dataclass(frozen=True)
class BrowserFramePresentedRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-frame-presented/request'
    surface: Id
    frame_seq: int


@dataclass(frozen=True)
class BrowserInsertTextRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-insert-text/request'
    surface: Id
    text: str


@dataclass(frozen=True)
class BrowserKeyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-key/request'
    surface: Id
    kind: Literal['down', 'up']
    key: str
    code: str
    windows_virtual_key_code: int
    modifiers: int
    text: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserKeyPressRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-key-press/request'
    surface: Id
    code: str
    key: str
    modifiers: int
    windows_virtual_key_code: int
    text: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserMouseRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-mouse/request'
    surface: Id
    kind: Literal['down', 'up', 'move']
    x_px: float
    y_px: float
    button: Union[str, None, MissingType] = field(default=MISSING)
    click_count: Union[int, None, MissingType] = field(default=MISSING)
    frame_seq: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserMouseGuardedRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-mouse-guarded/request'
    surface: Id
    frame_seq: int
    kind: Literal['down', 'up', 'move']
    x_px: float
    y_px: float
    button: Union[str, None, MissingType] = field(default=MISSING)
    click_count: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserNavigateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-navigate/request'
    surface: Id
    url: str


@dataclass(frozen=True)
class BrowserReloadRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-reload/request'
    surface: Id


@dataclass(frozen=True)
class BrowserWheelRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-wheel/request'
    surface: Id
    x_px: float
    y_px: float
    delta_y_px: float
    frame_seq: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class BrowserWheelGuardedRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/browser-wheel-guarded/request'
    surface: Id
    delta_y_px: float
    frame_seq: int
    x_px: float
    y_px: float


@dataclass(frozen=True)
class ClearHistoryRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/clear-history/request'
    surface: Id
    fallback_key: Union[TerminalKeyInput, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ClearWindowTitleRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/clear-window-title/request'
    pass


@dataclass(frozen=True)
class ClientFocusRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/client-focus/request'
    client_id: str


@dataclass(frozen=True)
class ClientFocusResult:
    __cmux_schema_path__: ClassVar[str] = 'commands/client-focus/result'
    pane: Union[Id, None]
    tab: Union[int, None]


@dataclass(frozen=True)
class ClosePaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-pane/request'
    pane: Id


@dataclass(frozen=True)
class CloseProviderManagedWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-provider-managed-workspace/request'
    workspace: Id
    key: str
    authority: str


@dataclass(frozen=True)
class CloseScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-screen/request'
    screen: Id


@dataclass(frozen=True)
class CloseSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-surface/request'
    surface: Id


@dataclass(frozen=True)
class CloseTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-terminal/request'
    terminal_id: str
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CloseWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/close-workspace/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CopyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/copy/request'
    surface: Id
    mode: Literal['screen', 'selection', 'scrollback']


@dataclass(frozen=True)
class CreateSurfaceWithReceiptRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/create-surface-with-receipt/request'
    operation: str
    origin: str
    receipt: str
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    argv: Union[List[str], None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    idempotency_key: Union[str, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)
    selector_fallbacks: Union[List[ResourceSelectors], MissingType] = field(default=MISSING)
    selectors: Union[ResourceSelectors, None, MissingType] = field(default=MISSING)
    url: Union[str, None, MissingType] = field(default=MISSING)
    width: Union[float, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CreateTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/create-terminal/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    argv: Union[List[str], None, MissingType] = field(default=MISSING)
    command: Union[str, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)
    terminal_id: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class CreateWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/create-workspace/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class DetachAttachedViewRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/detach-attached-view/request'
    surface: Id
    lease: str


@dataclass(frozen=True)
class DetachClientRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/detach-client/request'
    client: int


@dataclass(frozen=True)
class ExportLayoutRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/export-layout/request'
    screen: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FocusDirectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/focus-direction/request'
    dir: PaneDirection
    pane: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class FocusPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/focus-pane/request'
    pane: Id


@dataclass(frozen=True)
class GetBrowserProviderRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/get-browser-provider/request'
    pass


@dataclass(frozen=True)
class GetCellPixelsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/get-cell-pixels/request'
    pass


@dataclass(frozen=True)
class GetFrontendProjectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/get-frontend-projection/request'
    frontend: str
    scope: str
    subject_key: str


@dataclass(frozen=True)
class IdentifyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/identify/request'
    pass


@dataclass(frozen=True)
class IdsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/ids/request'
    kind: Union[Literal['workspace', 'screen', 'pane', 'surface'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class JournalFrontendEventRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/journal-frontend-event/request'
    event: FrontendJournalEvent


@dataclass(frozen=True)
class JournalFrontendEventResult:
    __cmux_schema_path__: ClassVar[str] = 'commands/journal-frontend-event/result'
    committed: Literal[True]


@dataclass(frozen=True)
class ListAgentsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-agents/request'
    surface: Union[Id, None, MissingType] = field(default=MISSING)
    state: Union[AgentState, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ListClientsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-clients/request'
    pass


@dataclass(frozen=True)
class ListTerminalsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-terminals/request'
    pass


@dataclass(frozen=True)
class ListWorkspacesRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/list-workspaces/request'
    pass


@dataclass(frozen=True)
class MarkWorkspacesProviderManagedRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/mark-workspaces-provider-managed/request'
    authority: str


@dataclass(frozen=True)
class MintTerminalRendererRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/mint-terminal-renderer/request'
    surface: Id
    ttl_ms: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MintTerminalRendererByTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/mint-terminal-renderer-by-terminal/request'
    terminal: str
    ttl_ms: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MoveTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-tab/request'
    surface: Id
    pane: Id
    index: int


@dataclass(frozen=True)
class MoveTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-terminal/request'
    terminal_id: str
    workspace_key: str
    terminal_incarnation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class MoveWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/move-workspace/request'
    index: int
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewBrowserTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-browser-tab/request'
    url: str
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-pane/request'
    pane: Id
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewPaneRightRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-pane-right/request'
    pane: Id
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)
    width: Union[float, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-screen/request'
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-tab/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NewWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/new-workspace/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class NotifyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/notify/request'
    title: str
    body: str
    level: Union[NotificationLevel, None, MissingType] = field(default=MISSING)
    surface: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class PairingResponseRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/pairing-response/request'
    request: int
    approve: bool


@dataclass(frozen=True)
class PaneNeighborRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/pane-neighbor/request'
    pane: Id
    dir: PaneDirection


@dataclass(frozen=True)
class PingRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/ping/request'
    pass


@dataclass(frozen=True)
class ProcessInfoRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/process-info/request'
    surface: Id


@dataclass(frozen=True)
class PutFrontendProjectionRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/put-frontend-projection/request'
    frontend: str
    scope: str
    subject_key: str
    schema_version: int
    projection: Union[JsonValue, None]
    expected_projection_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReadScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/read-screen/request'
    surface: Id


@dataclass(frozen=True)
class ReadScrollbackRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/read-scrollback/request'
    surface: Id
    start: int
    count: int


@dataclass(frozen=True)
class RegisterBrowserProviderRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/register-browser-provider/request'
    authentication: BrowserProviderAuthentication
    endpoint: str
    provider_id: str
    targets: List[BrowserProviderTarget]
    bearer_token: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReleaseAttachedViewSizeRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/release-attached-view-size/request'
    surface: Id
    lease: str


@dataclass(frozen=True)
class ReleaseSurfaceSizeRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/release-surface-size/request'
    surface: Id


@dataclass(frozen=True)
class ReloadConfigRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/reload-config/request'
    pass


@dataclass(frozen=True)
class ReloadConfigResult:
    __cmux_schema_path__: ClassVar[str] = 'commands/reload-config/result'
    path: Union[str, None]
    reloaded: Literal[True]


@dataclass(frozen=True)
class RenamePaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-pane/request'
    pane: Id
    name: str


@dataclass(frozen=True)
class RenameProviderManagedWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-provider-managed-workspace/request'
    workspace: Id
    key: str
    name: str
    authority: str


@dataclass(frozen=True)
class RenameScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-screen/request'
    screen: Id
    name: str


@dataclass(frozen=True)
class RenameSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-surface/request'
    surface: Id
    name: str


@dataclass(frozen=True)
class RenameWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/rename-workspace/request'
    name: str
    workspace: Union[Id, None, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    expected_revision: Union[int, None, MissingType] = field(default=MISSING)
    expected_generation: Union[str, None, MissingType] = field(default=MISSING)
    origin: Union[str, None, MissingType] = field(default=MISSING)
    mutation_id: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReportAgentRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/report-agent/request'
    surface: Id
    state: AgentState
    source: AgentReportSource
    session: Union[str, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ReportFocusRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/report-focus/request'
    pane: Id
    client_id: str
    tab: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ResizeAttachedViewRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/resize-attached-view/request'
    surface: Id
    cols: int
    lease: str
    rows: int


@dataclass(frozen=True)
class ResizeSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/resize-surface/request'
    surface: Id
    cols: int
    rows: int


@dataclass(frozen=True)
class ResolveTerminalRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/resolve-terminal/request'
    terminal_id: str


@dataclass(frozen=True)
class RunRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/run/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    argv: Union[List[str], None, MissingType] = field(default=MISSING)
    command: Union[str, None, MissingType] = field(default=MISSING)
    cwd: Union[str, None, MissingType] = field(default=MISSING)
    new_workspace: Union[bool, MissingType] = field(default=MISSING)
    key: Union[str, None, MissingType] = field(default=MISSING)
    name: Union[str, None, MissingType] = field(default=MISSING)
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class ScrollSurfaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/scroll-surface/request'
    surface: Id
    delta: int


@dataclass(frozen=True)
class SelectScreenRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-screen/request'
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SelectTabRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-tab/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SelectWorkspaceRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/select-workspace/request'
    index: Union[int, None, MissingType] = field(default=MISSING)
    delta: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SendRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/send/request'
    surface: Id
    text: Union[str, None, MissingType] = field(default=MISSING)
    bytes_data: Union[Base64, None, MissingType] = field(default=MISSING, metadata={'wire_name': 'bytes'})
    paste: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SendKeyRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/send-key/request'
    surface: Id
    keys: List[str]


@dataclass(frozen=True)
class SetCellPixelsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-cell-pixels/request'
    width_px: int
    height_px: int


@dataclass(frozen=True)
class SetClientInfoRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-client-info/request'
    name: Union[str, None, MissingType] = field(default=MISSING)
    kind: Union[str, None, MissingType] = field(default=MISSING)
    capabilities: Union[List[str], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetClientSizingRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-client-sizing/request'
    surface: Id
    enabled: bool
    client: Union[int, None, MissingType] = field(default=MISSING)
    exclusive: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetDefaultColorsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-default-colors/request'
    fg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    bg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    selection_bg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    selection_fg: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], None, MissingType] = field(default=MISSING)
    complete: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetRatioRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-ratio/request'
    pane: Id
    dir: SplitDirection
    ratio: float


@dataclass(frozen=True)
class SetSplitRatioRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-split-ratio/request'
    split: Id
    ratio: float
    transaction: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetViewportPaneWidthRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-viewport-pane-width/request'
    pane: Id
    width: float
    transaction: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SetWindowTitleRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/set-window-title/request'
    title: str


@dataclass(frozen=True)
class ShutdownDaemonRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/shutdown-daemon/request'
    pid: int
    generation: str
    force: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SidebarPluginRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/sidebar-plugin/request'
    cols: int
    rows: int
    relaunch: Union[bool, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SplitRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/split/request'
    pane: Id
    dir: SplitDirection
    cols: Union[int, None, MissingType] = field(default=MISSING)
    rows: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SubscribeRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/subscribe/request'
    surface: Union[Id, None, MissingType] = field(default=MISSING)
    tree_events: Union[Literal['coarse', 'deltas'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class SwapPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/swap-pane/request'
    pane: Id
    dir: Union[PaneDirection, None, MissingType] = field(default=MISSING)
    target: Union[Id, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class TerminalEventsRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/terminal-events/request'
    after_revision: Union[int, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class UndoLayoutRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/undo-layout/request'
    pane: Id
    confirm_close: Union[bool, MissingType] = field(default=MISSING)
    revision: Union[int, None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class UnregisterBrowserProviderRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/unregister-browser-provider/request'
    pass


@dataclass(frozen=True)
class VtStateRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/vt-state/request'
    surface: Id


@dataclass(frozen=True)
class WaitForRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/wait-for/request'
    surface: Id
    pattern: str
    timeout_ms: int


@dataclass(frozen=True)
class ZoomPaneRequest:
    __cmux_schema_path__: ClassVar[str] = 'commands/zoom-pane/request'
    pane: Union[Id, None, MissingType] = field(default=MISSING)
    mode: Union[Literal['toggle', 'on', 'off'], None, MissingType] = field(default=MISSING)


@dataclass(frozen=True)
class AgentChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/agent-changed/payload'
    surface: Id
    event: Literal['agent-changed']
    session: Union[str, None]
    source: AgentSource
    state: AgentState
    updated_at_ms: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class BellEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/bell/payload'
    surface: Id
    event: Literal['bell']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class BrowserStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/browser-state/payload'
    surface: Id
    cols: int
    error: Union[str, None]
    event: Literal['browser-state']
    frames_stalled: bool
    rows: int
    status: Literal['starting', 'live', 'failed']
    title: str
    url: str
    frame: Union[BrowserFrame, None, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientAttachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-attached/payload'
    client: int
    event: Literal['client-attached']
    kind: Union[str, None]
    name: Union[str, None]
    transport: Literal['unix', 'ws']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-changed/payload'
    client: int
    event: Literal['client-changed']
    kind: Union[str, None]
    name: Union[str, None]
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientDetachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-detached/payload'
    client: int
    event: Literal['client-detached']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ClientListInvalidatedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/client-list-invalidated/payload'
    event: Literal['client-list-invalidated']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ColorsChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/colors-changed/payload'
    bg: Union[ColorHex, None]
    event: Literal['colors-changed']
    fg: Union[ColorHex, None]
    selection_bg: Union[ColorHex, None]
    selection_fg: Union[ColorHex, None]
    surface: Union[Id, MissingType] = field(default=MISSING)
    cursor: Union[ColorHex, None, MissingType] = field(default=MISSING)
    cursor_blink: Union[bool, None, MissingType] = field(default=MISSING)
    cursor_style: Union[CursorStyle, None, MissingType] = field(default=MISSING)
    palette: Union[Dict[str, ColorHex], MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ConfigReloadRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/config-reload-requested/payload'
    event: Literal['config-reload-requested']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class DetachedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/detached/payload'
    surface: Id
    event: Literal['detached']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class EmptyEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/empty/payload'
    event: Literal['empty']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class FrameEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/frame/payload'
    surface: Id
    data: Base64
    event: Literal['frame']
    height: int
    seq: int
    width: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class FrontendProjectionChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/frontend-projection-changed/payload'
    event: Literal['frontend-projection-changed']
    frontend: str
    mutation_id: str
    origin: str
    projection_revision: int
    scope: str
    subject_key: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class GraphicsStatusEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/graphics-status/payload'
    event: Literal['graphics-status']
    kind: Literal['kitty-image-budget-worker-start-failed', 'kitty-image-budget-update-failed', 'cell-pixel-update-retries-exhausted']
    attempts: Union[int, MissingType] = field(default=MISSING)
    cell_height: Union[int, MissingType] = field(default=MISSING)
    cell_width: Union[int, MissingType] = field(default=MISSING)
    error: Union[str, MissingType] = field(default=MISSING)
    remaining: Union[int, MissingType] = field(default=MISSING)
    retry_exhausted: Union[bool, MissingType] = field(default=MISSING)
    summary: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class LayoutChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/layout-changed/payload'
    screen: Id
    event: Literal['layout-changed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class NotificationEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/notification/payload'
    surface: Union[Id, None]
    body: str
    event: Literal['notification']
    level: NotificationLevel
    notification: Id
    title: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class OutputEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/output/payload'
    surface: Id
    data: Base64
    event: Literal['output']
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class OverflowEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/overflow/payload'
    error: str
    event: Literal['overflow']
    surface: Union[Id, MissingType] = field(default=MISSING)
    scope: Union[Literal['surface'], MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PairingRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pairing-requested/payload'
    request: int
    code: str
    event: Literal['pairing-requested']
    expires_in: int
    peer: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PairingResolvedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pairing-resolved/payload'
    request: int
    event: Literal['pairing-resolved']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PaneAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pane-added/payload'
    pane: Id
    screen: Id
    workspace: Id
    entity: Pane
    event: Literal['pane-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class PaneClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/pane-closed/payload'
    pane: Id
    screen: Id
    workspace: Id
    entity: Pane
    event: Literal['pane-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class RenderDeltaEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/render-delta/payload'
    surface: Id
    cursor: RenderCursor
    event: Literal['render-delta']
    full: bool
    rows: List[RenderRow]
    default_bg: Union[ColorHex, MissingType] = field(default=MISSING)
    default_fg: Union[ColorHex, MissingType] = field(default=MISSING)
    graphics: Union[RenderGraphicsDelta, MissingType] = field(default=MISSING)
    history_epoch: Union[int, MissingType] = field(default=MISSING)
    scrollback_rows: Union[int, MissingType] = field(default=MISSING)
    size: Union[Size, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class RenderStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/render-state/payload'
    surface: Id
    cursor: RenderCursor
    default_bg: ColorHex
    default_fg: ColorHex
    event: Literal['render-state']
    history_epoch: int
    rows: List[RenderRow]
    scrollback_rows: int
    size: Size
    graphics: Union[RenderGraphics, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ResizedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/resized/payload'
    surface: Id
    cols: int
    event: Literal['resized']
    rows: int
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    data: Union[Base64, MissingType] = field(default=MISSING)
    kitty_graphics_state: Union[KittyGraphicsState, MissingType] = field(default=MISSING)
    kitty_image_aliases: Union[List[KittyImageAlias], MissingType] = field(default=MISSING)
    replay: Union[Base64, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-added/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-closed/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScreenRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/screen-renamed/payload'
    screen: Id
    workspace: Id
    entity: Screen
    event: Literal['screen-renamed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class ScrollChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/scroll-changed/payload'
    surface: Id
    at_bottom: bool
    event: Literal['scroll-changed']
    offset: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class StatusEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/status/payload'
    event: Literal['status']
    message: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceExitedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-exited/payload'
    surface: Id
    event: Literal['surface-exited']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceOutputEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-output/payload'
    surface: Id
    event: Literal['surface-output']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceResizeFailedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-resize-failed/payload'
    surface: Id
    cols: int
    error: str
    event: Literal['surface-resize-failed']
    reservation_id: Union[int, None]
    retry_after_ms: Union[int, None]
    rows: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class SurfaceResizedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/surface-resized/payload'
    surface: Id
    cols: int
    event: Literal['surface-resized']
    reservation_id: Union[int, None]
    rows: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-added/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-added']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-closed/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-closed']
    index: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TabRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tab-renamed/payload'
    surface: Id
    pane: Id
    screen: Id
    workspace: Id
    entity: Tab
    event: Literal['tab-renamed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TerminalRegistryChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/terminal-registry-changed/payload'
    event: Literal['terminal-registry-changed']
    generation: str
    refetch: Literal['terminal-events-or-list-terminals']
    registry_id: str
    terminal_revision: int
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TitleChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/title-changed/payload'
    surface: Id
    event: Literal['title-changed']
    title: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class TreeChangedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/tree-changed/payload'
    event: Literal['tree-changed']
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class VtStateEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/vt-state/payload'
    surface: Id
    cols: int
    data: Base64
    event: Literal['vt-state']
    rows: int
    colors: Union[TerminalColors, MissingType] = field(default=MISSING)
    kitty_graphics_state: Union[KittyGraphicsState, MissingType] = field(default=MISSING)
    kitty_image_aliases: Union[List[KittyImageAlias], MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WindowTitleRequestedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/window-title-requested/payload'
    event: Literal['window-title-requested']
    title: str
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceAddedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-added/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-added']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceClosedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-closed/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-closed']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceMovedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-moved/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-moved']
    generation: str
    index: int
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


@dataclass(frozen=True)
class WorkspaceRenamedEvent(EventBase):
    __cmux_schema_path__: ClassVar[str] = 'events/workspace-renamed/payload'
    workspace: Id
    entity: Workspace
    event: Literal['workspace-renamed']
    generation: str
    registry_id: str
    workspace_revision: int
    mutation_id: Union[str, MissingType] = field(default=MISSING)
    origin: Union[str, MissingType] = field(default=MISSING)
    raw: Mapping[str, Any] = field(default_factory=dict, repr=False, compare=False, metadata={'cmux_skip': True})


# Named protocol aliases.
Base64 = str
ColorHex = str
DeclarativeLayout = Union[DeclarativeLayoutLeaf, DeclarativeLayoutSplit, DeclarativeLayoutStack]
FrontendJournalEvent = Union[FrontendJournalEventFocus, FrontendJournalEventResize, FrontendJournalEventViewport]
Id = int
JsonValue = Any
Layout = Union[LayoutLeaf, LayoutSplit, LayoutStack]
LayoutUndoResult = Union[LayoutUndoUndone, LayoutUndoConfirmationRequired]
Pane = Union[LivePane, DeadPane]
TerminalExitOutcome = Union[TerminalExitOutcomeExit, TerminalExitOutcomeSignal, TerminalExitOutcomeUnknown]

KnownEvent = Union[AgentChangedEvent, BellEvent, BrowserStateEvent, ClientAttachedEvent, ClientChangedEvent, ClientDetachedEvent, ClientListInvalidatedEvent, ColorsChangedEvent, ConfigReloadRequestedEvent, DetachedEvent, EmptyEvent, FrameEvent, FrontendProjectionChangedEvent, GraphicsStatusEvent, LayoutChangedEvent, NotificationEvent, OutputEvent, OverflowEvent, PairingRequestedEvent, PairingResolvedEvent, PaneAddedEvent, PaneClosedEvent, RenderDeltaEvent, RenderStateEvent, ResizedEvent, ScreenAddedEvent, ScreenClosedEvent, ScreenRenamedEvent, ScrollChangedEvent, StatusEvent, SurfaceExitedEvent, SurfaceOutputEvent, SurfaceResizeFailedEvent, SurfaceResizedEvent, TabAddedEvent, TabClosedEvent, TabRenamedEvent, TerminalRegistryChangedEvent, TitleChangedEvent, TreeChangedEvent, VtStateEvent, WindowTitleRequestedEvent, WorkspaceAddedEvent, WorkspaceClosedEvent, WorkspaceMovedEvent, WorkspaceRenamedEvent]
AnyEvent = Union[KnownEvent, UnknownEvent]

__all__ = [
    'MISSING',
    'MissingType',
    'EventBase',
    'UnknownEvent',
    'KnownEvent',
    'AnyEvent',
    'AgentReportSource',
    'AgentSource',
    'AgentState',
    'BrowserProviderAuthentication',
    'ClientTransport',
    'CursorStyle',
    'FrontendFocusTarget',
    'NotificationLevel',
    'PaneDirection',
    'RenderGraphicFormat',
    'RenderUnderline',
    'SplitDirection',
    'TerminalKey',
    'TerminalKeyAction',
    'TerminalLifecycle',
    'ViewAttachmentOutcome',
    'AgentRecord',
    'AppliedPane',
    'ApplyLayoutResult',
    'AttachedViewOutcomeResult',
    'AttachedViewResizeResult',
    'BrowserFrame',
    'BrowserProviderSnapshot',
    'BrowserProviderTarget',
    'BrowserProviderUnregisterResult',
    'CellPixelFailure',
    'CellPixelResize',
    'CellPixelSurface',
    'ClientInfo',
    'ClientSize',
    'CloseTerminalResult',
    'CopyResult',
    'DeadPane',
    'DeclarativeLayoutLeaf',
    'DeclarativeLayoutSplit',
    'DeclarativeLayoutStack',
    'EmptyResult',
    'ExportLayoutResult',
    'ExportedPane',
    'FocusDirectionResult',
    'FrontendJournalEventFocus',
    'FrontendJournalEventResize',
    'FrontendJournalEventViewport',
    'FrontendProjection',
    'GetCellPixelsResult',
    'IdMapping',
    'IdentifyResult',
    'IdsResult',
    'KittyGraphicsState',
    'KittyImageAlias',
    'LayoutLeaf',
    'LayoutSplit',
    'LayoutStack',
    'LayoutUndoConfirmationRequired',
    'LayoutUndoUndone',
    'ListAgentsResult',
    'ListTerminalsResult',
    'LivePane',
    'MintTerminalRendererResult',
    'MoveTerminalResult',
    'NotificationMarker',
    'NotifyResult',
    'PaneNeighborResult',
    'PingResult',
    'ProcessInfoResult',
    'ProviderWorkspaceMutationResult',
    'ReadScreenResult',
    'ReadScrollbackResult',
    'RenderCursor',
    'RenderGraphicImage',
    'RenderGraphicPlacement',
    'RenderGraphics',
    'RenderGraphicsDelta',
    'RenderRow',
    'RenderRun',
    'ReportAgentResult',
    'ResizeSurfaceResult',
    'ResolveTerminalResult',
    'ResourceSelectors',
    'RunResult',
    'Screen',
    'SetCellPixelsResult',
    'ShutdownDaemonResult',
    'SidebarPluginResult',
    'Size',
    'SurfaceResult',
    'Tab',
    'TerminalColors',
    'TerminalEventsResult',
    'TerminalExit',
    'TerminalExitOutcomeExit',
    'TerminalExitOutcomeSignal',
    'TerminalExitOutcomeUnknown',
    'TerminalKeyInput',
    'TerminalModifiers',
    'TerminalPlacement',
    'TerminalRecord',
    'TerminalRegistryEvent',
    'Tree',
    'VtStateResult',
    'WaitForResult',
    'Workspace',
    'WorkspaceMutationResult',
    'ZoomPaneResult',
    'ApplyLayoutRequest',
    'AttachSurfaceRequest',
    'BrowserActivateRequest',
    'BrowserBackRequest',
    'BrowserForwardRequest',
    'BrowserFramePresentedRequest',
    'BrowserInsertTextRequest',
    'BrowserKeyRequest',
    'BrowserKeyPressRequest',
    'BrowserMouseRequest',
    'BrowserMouseGuardedRequest',
    'BrowserNavigateRequest',
    'BrowserReloadRequest',
    'BrowserWheelRequest',
    'BrowserWheelGuardedRequest',
    'ClearHistoryRequest',
    'ClearWindowTitleRequest',
    'ClientFocusRequest',
    'ClientFocusResult',
    'ClosePaneRequest',
    'CloseProviderManagedWorkspaceRequest',
    'CloseScreenRequest',
    'CloseSurfaceRequest',
    'CloseTerminalRequest',
    'CloseWorkspaceRequest',
    'CopyRequest',
    'CreateSurfaceWithReceiptRequest',
    'CreateTerminalRequest',
    'CreateWorkspaceRequest',
    'DetachAttachedViewRequest',
    'DetachClientRequest',
    'ExportLayoutRequest',
    'FocusDirectionRequest',
    'FocusPaneRequest',
    'GetBrowserProviderRequest',
    'GetCellPixelsRequest',
    'GetFrontendProjectionRequest',
    'IdentifyRequest',
    'IdsRequest',
    'JournalFrontendEventRequest',
    'JournalFrontendEventResult',
    'ListAgentsRequest',
    'ListClientsRequest',
    'ListTerminalsRequest',
    'ListWorkspacesRequest',
    'MarkWorkspacesProviderManagedRequest',
    'MintTerminalRendererRequest',
    'MintTerminalRendererByTerminalRequest',
    'MoveTabRequest',
    'MoveTerminalRequest',
    'MoveWorkspaceRequest',
    'NewBrowserTabRequest',
    'NewPaneRequest',
    'NewPaneRightRequest',
    'NewScreenRequest',
    'NewTabRequest',
    'NewWorkspaceRequest',
    'NotifyRequest',
    'PairingResponseRequest',
    'PaneNeighborRequest',
    'PingRequest',
    'ProcessInfoRequest',
    'PutFrontendProjectionRequest',
    'ReadScreenRequest',
    'ReadScrollbackRequest',
    'RegisterBrowserProviderRequest',
    'ReleaseAttachedViewSizeRequest',
    'ReleaseSurfaceSizeRequest',
    'ReloadConfigRequest',
    'ReloadConfigResult',
    'RenamePaneRequest',
    'RenameProviderManagedWorkspaceRequest',
    'RenameScreenRequest',
    'RenameSurfaceRequest',
    'RenameWorkspaceRequest',
    'ReportAgentRequest',
    'ReportFocusRequest',
    'ResizeAttachedViewRequest',
    'ResizeSurfaceRequest',
    'ResolveTerminalRequest',
    'RunRequest',
    'ScrollSurfaceRequest',
    'SelectScreenRequest',
    'SelectTabRequest',
    'SelectWorkspaceRequest',
    'SendRequest',
    'SendKeyRequest',
    'SetCellPixelsRequest',
    'SetClientInfoRequest',
    'SetClientSizingRequest',
    'SetDefaultColorsRequest',
    'SetRatioRequest',
    'SetSplitRatioRequest',
    'SetViewportPaneWidthRequest',
    'SetWindowTitleRequest',
    'ShutdownDaemonRequest',
    'SidebarPluginRequest',
    'SplitRequest',
    'SubscribeRequest',
    'SwapPaneRequest',
    'TerminalEventsRequest',
    'UndoLayoutRequest',
    'UnregisterBrowserProviderRequest',
    'VtStateRequest',
    'WaitForRequest',
    'ZoomPaneRequest',
    'AgentChangedEvent',
    'BellEvent',
    'BrowserStateEvent',
    'ClientAttachedEvent',
    'ClientChangedEvent',
    'ClientDetachedEvent',
    'ClientListInvalidatedEvent',
    'ColorsChangedEvent',
    'ConfigReloadRequestedEvent',
    'DetachedEvent',
    'EmptyEvent',
    'FrameEvent',
    'FrontendProjectionChangedEvent',
    'GraphicsStatusEvent',
    'LayoutChangedEvent',
    'NotificationEvent',
    'OutputEvent',
    'OverflowEvent',
    'PairingRequestedEvent',
    'PairingResolvedEvent',
    'PaneAddedEvent',
    'PaneClosedEvent',
    'RenderDeltaEvent',
    'RenderStateEvent',
    'ResizedEvent',
    'ScreenAddedEvent',
    'ScreenClosedEvent',
    'ScreenRenamedEvent',
    'ScrollChangedEvent',
    'StatusEvent',
    'SurfaceExitedEvent',
    'SurfaceOutputEvent',
    'SurfaceResizeFailedEvent',
    'SurfaceResizedEvent',
    'TabAddedEvent',
    'TabClosedEvent',
    'TabRenamedEvent',
    'TerminalRegistryChangedEvent',
    'TitleChangedEvent',
    'TreeChangedEvent',
    'VtStateEvent',
    'WindowTitleRequestedEvent',
    'WorkspaceAddedEvent',
    'WorkspaceClosedEvent',
    'WorkspaceMovedEvent',
    'WorkspaceRenamedEvent',
    'Base64',
    'ColorHex',
    'DeclarativeLayout',
    'FrontendJournalEvent',
    'Id',
    'JsonValue',
    'Layout',
    'LayoutUndoResult',
    'Pane',
    'TerminalExitOutcome',
]
