import { createHash } from "node:crypto";
import { guestMessageShell } from "./guestCliMessages";

/** Installed on create/heal, independently of the immutable devbox snapshot. */
export const GUEST_BROWSER_OPENER_PATH = "/usr/local/bin/cmux-open-url";

export const GUEST_BROWSER_OPENER = `#!/bin/sh
set -eu
${guestMessageShell(["openURLUsage", "openURLInvalid", "openURLFallback"])}
[ "\${1:-}" != -- ] || shift
[ "$#" = 1 ] || { cmux_message openURLUsage >&2; exit 2; }
url="$1"
# Do not reinterpret query strings, percent escapes, or shell metacharacters.
if ! printf '%s' "$url" | jq -Rse 'length <= 16384 and test("^[Hh][Tt][Tt][Pp][Ss]?://[^/?#[:space:]]+") and (test("[[:cntrl:][:space:]]") | not)' >/dev/null 2>&1; then
  cmux_message openURLInvalid >&2
  exit 2
fi
terminal="\${CMUX_TUI_TERMINAL_ID:-}"
session="\${CMUX_TUI_SESSION:-cloud}"
binary="\${CMUX_TUI_BIN:-/usr/local/bin/cmux-tui}"
if [ -n "$terminal" ] && [ -x "$binary" ]; then
  request="$(jq -cn --arg terminal "$terminal" --arg url "$url" '{cmd:"url-open",terminal_id:$terminal,url:$url}')"
  # The daemon waits at most five seconds for the frontend acknowledgement.
  # timeout also fences a wedged/older CLI before the calling auth tool resumes.
  result="$(timeout 8 "$binary" --session "$session" --json raw command --request-json "$request" 2>/dev/null || true)"
  if printf '%s' "$result" | jq -e '.opened == true' >/dev/null 2>&1; then exit 0; fi
fi
cmux_message openURLFallback "$url"
exit 0
`;

/** PATH shims intercept web URLs only; files/options retain the distro opener. */
export const GUEST_OS_BROWSER_WRAPPER = `#!/bin/sh
name="\${0##*/}"
if [ "$#" = 1 ]; then
  case "$1" in
    [Hh][Tt][Tt][Pp]://*|[Hh][Tt][Tt][Pp][Ss]://*) exec /usr/local/bin/cmux-open-url "$1" ;;
  esac
fi
# A non-web open must not recurse through BROWSER back into this wrapper.
unset BROWSER GH_BROWSER
exec "/usr/bin/$name" "$@"
`;

export const GUEST_BROWSER_ENV = `# Human auth openers use cmux; direct Chrome/CDP/CUA retain DISPLAY.
if [ -x /usr/local/bin/cmux-open-url ]; then
  : "\${BROWSER:=/usr/local/bin/cmux-open-url}"
  : "\${GH_BROWSER:=$BROWSER}"
  export BROWSER GH_BROWSER
fi
`;

export const GUEST_BROWSER_FISH_ENV = `if test -x /usr/local/bin/cmux-open-url
  if not set -q BROWSER; or test -z "$BROWSER"
    set -gx BROWSER /usr/local/bin/cmux-open-url
  end
  if not set -q GH_BROWSER; or test -z "$GH_BROWSER"
    set -gx GH_BROWSER $BROWSER
  end
end
`;

/** Bundled/absolute xdg-open and GIO consult MIME handlers before BROWSER. */
const guestBrowserDesktopEntry = `[Desktop Entry]
Type=Application
Name=cmux Browser
Name[ja]=cmux ブラウザー
Exec=/usr/local/bin/cmux-open-url %u
Terminal=false
NoDisplay=true
MimeType=x-scheme-handler/http;x-scheme-handler/https;
`;

export const GUEST_BROWSER_FILES = [
  { path: GUEST_BROWSER_OPENER_PATH, content: GUEST_BROWSER_OPENER, mode: "0755" },
  ...["xdg-open", "x-www-browser", "sensible-browser"].map((name) => ({
    path: `/usr/local/bin/${name}`, content: GUEST_OS_BROWSER_WRAPPER, mode: "0755",
  })),
  { path: "/etc/profile.d/cmux-browser.sh", content: GUEST_BROWSER_ENV, mode: "0644" },
  { path: "/etc/fish/conf.d/cmux-browser.fish", content: GUEST_BROWSER_FISH_ENV, mode: "0644" },
  { path: "/usr/local/share/applications/cmux-browser.desktop", content: guestBrowserDesktopEntry, mode: "0644" },
] as const;

/** A version stamp covers every generated byte, including localized fallback text. */
const browserDigest = createHash("sha256").update(JSON.stringify(GUEST_BROWSER_FILES)).digest("hex");
const browserShellSource = '[ -r /etc/profile.d/cmux-browser.sh ] && . /etc/profile.d/cmux-browser.sh';
export const guestBrowserReadyCommand = [
  `test "$(cat /etc/cmux/browser-opener-version 2>/dev/null)" = '${browserDigest}'`,
  ...GUEST_BROWSER_FILES.map(({ path, content }) =>
    `test "$(sha256sum '${path}' 2>/dev/null | cut -d ' ' -f 1)" = '${createHash("sha256").update(content).digest("hex")}'`),
  `test -x ${GUEST_BROWSER_OPENER_PATH}`,
  `grep -Fqx '${browserShellSource}' /etc/bash.bashrc`,
  `grep -Fqx '${browserShellSource}' /etc/zsh/zshenv`,
].join(" && ");

/** Reconciles MIME associations without rewriting the rest of the guest integration. */
export const guestBrowserMimeReconcileCommand = `if command -v xdg-mime >/dev/null 2>&1; then for cmux_browser_user in root cmux ubuntu; do getent passwd "$cmux_browser_user" >/dev/null || continue; for cmux_browser_scheme in http https; do cmux_browser_default="$(runuser -u "$cmux_browser_user" -- xdg-mime query default x-scheme-handler/$cmux_browser_scheme 2>/dev/null || true)"; [ "$cmux_browser_default" = cmux-browser.desktop ] || runuser -u "$cmux_browser_user" -- xdg-mime default cmux-browser.desktop x-scheme-handler/$cmux_browser_scheme; done; done; fi`;

/** Generates the root-only idempotent installation used by the actual driver. */
export function guestBrowserInstallCommand(): string {
  const writes = GUEST_BROWSER_FILES.flatMap(({ path, content, mode }) => [
    `cmux_browser_tmp=$(mktemp '${path}.XXXXXX')`,
    `printf '%s' '${Buffer.from(content).toString("base64")}' | base64 -d > "$cmux_browser_tmp"`,
    `chmod ${mode} "$cmux_browser_tmp" && mv -f "$cmux_browser_tmp" '${path}'`,
  ]);
  const install = [
    "mkdir -p /usr/local/bin /usr/local/share/applications /etc/profile.d /etc/cmux /etc/fish/conf.d",
    ...writes,
    `for cmux_rc in /etc/bash.bashrc /etc/zsh/zshenv; do [ -f "$cmux_rc" ] || continue; grep -Fqx '${browserShellSource}' "$cmux_rc" || printf '\\n%s\\n' '${browserShellSource}' >> "$cmux_rc"; done`,
    guestBrowserMimeReconcileCommand,
    `printf '%s\\n' '${browserDigest}' > /etc/cmux/browser-opener-version`,
  ].join(" && ");
  // A fresh snapshot can already contain these exact files. In particular,
  // repeating xdg-mime for every user needlessly adds subprocesses to create.
  // The byte checks still repair missing, changed, or outdated integration.
  return `( ${guestBrowserReadyCommand} ) || ( ${install} )`;
}
