export const MAX_DEVICE_TOKENS_PER_USER = 200;
/** Defense-in-depth ceiling across every bundle namespace owned by one user. */
export const MAX_DEVICE_TOKENS_PER_ACCOUNT = 200;

export const MAX_PUSH_TITLE_CHARS = 120;
export const MAX_PUSH_SUBTITLE_CHARS = 120;
import { isEncryptedPushPayload } from "./encryptedPayload";

export const MAX_PUSH_BODY_CHARS = 500;
export const MAX_PUSH_ID_CHARS = 200;
export const MAX_PUSH_CORRELATION_ID_CHARS = 64;
export const MAX_PUSH_REQUEST_BYTES = 8 * 1024;
// APNs has a small provider-payload ceiling. Eight installations leaves room
// for the envelope and routing fields while keeping one request fanout safe.
export const MAX_ENCRYPTED_PUSH_PAYLOADS = MAX_DEVICE_TOKENS_PER_USER;
export const MAX_ENCRYPTED_PUSH_REQUEST_BYTES = 1024 * 1024;
/** Max dismissed-notification ids one dismiss push may carry; the Mac chunks. */
export const MAX_PUSH_DISMISS_IDS = 64;
/** Badge ceiling; iOS renders large numbers fine but a runaway count is a bug. */
export const MAX_PUSH_BADGE_COUNT = 9999;

export type ApnsBundlePolicy = {
  readonly bundleId: string;
  readonly environment: "sandbox" | "production";
};

/**
 * What a push request asks APNs to do. `notify` is the visible terminal-banner
 * mirror (the default; older Macs never send `kind`). `dismiss` is the cold
 * lane of Mac→iOS dismiss-sync: a banner-less `content-available` push carrying
 * the dismissed ids plus the authoritative badge, fanned out to every
 * registered device, or to every registered app namespace when the Mac sends
 * an account-wide fanout (idempotent on devices that got the live event).
 */
export type PushKind = "notify" | "dismiss";

export type PushPayload = {
  readonly kind: PushKind;
  readonly title: string;
  readonly subtitle: string | null;
  readonly body: string;
  readonly replyShape?: "none" | "text";
  readonly workspaceId: string | null;
  readonly surfaceId: string | null;
  /** Whether iOS may resolve the surface outside the explicit workspace. */
  readonly retargetsToLiveSurfaceOwner: boolean;
  /**
   * The Mac device UUID that owns the workspace/surface ids. Needed because
   * workspace ids are Mac-local and can collide across paired Macs.
   */
  readonly macDeviceId: string | null;
  /** The cmux app-instance tag paired with `macDeviceId`. */
  readonly macInstanceTag: string | null;
  /**
   * Stable Mac-side notification id. Sent to APNs as `apns-collapse-id` and as
   * `cmux.notificationId` so cross-device dismiss-sync can target the exact
   * delivered banner. An opaque id, never terminal content.
   */
  readonly notificationId: string | null;
  /**
   * Opaque logical-source-event id generated by the Mac. It is safe to use in
   * diagnostics and retry deduplication because it contains no notification
   * content, device token, workspace id, or account id.
   */
  readonly correlationId: string | null;
  /** Absolute APNs expiry in Unix seconds. `null` lets the route apply its TTL. */
  readonly expirationEpochSeconds: number | null;
  /** Dismissed notification ids carried by a `dismiss` push (else empty). */
  readonly dismissedIds: readonly string[];
  /**
   * Authoritative unread count computed by the Mac at send time, applied to the
   * iOS app icon as `aps.badge`. The phone never does local badge arithmetic;
   * every push sets the absolute total so drift self-heals. `null` = leave the
   * badge alone (older Macs).
   */
  readonly badgeCount: number | null;
  readonly hideContent: boolean;
  readonly encryptedPayloads?: readonly Record<string, unknown>[];
  readonly macPushPublicKey?: string | null;
};

export type PushPayloadResult =
  | { readonly ok: true; readonly value: PushPayload }
  | { readonly ok: false; readonly error: string };

export type JsonObjectResult =
  | { readonly ok: true; readonly value: Record<string, unknown> }
  | { readonly ok: false; readonly error: "invalid_json" | "request_too_large" };

const DEV_TAGGED_BUNDLE_ID = /^dev\.cmux\.ios\.[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/;
// Every TestFlight lane (beta AND internal) uses the production APNs
// environment; the internal lane's bundle id is set in
// .github/workflows/ios-testflight.yml (IOS_BETA_BUNDLE_ID).
const PROD_BUNDLE_IDS = new Set([
  "com.cmux.app",
  "com.cmuxterm.app",
  "dev.cmux.app.beta",
  "dev.cmux.app.internal",
  "dev.cmux.app.demo",
]);

function stringValue(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function boundedString(value: unknown, maxChars: number): string | null {
  const text = stringValue(value);
  if (text.length > maxChars) return null;
  return text;
}

export function normalizeApnsBundle(bundleId: string): ApnsBundlePolicy | null {
  const normalized = bundleId.trim();
  if (PROD_BUNDLE_IDS.has(normalized)) {
    return { bundleId: normalized, environment: "production" };
  }
  if (DEV_TAGGED_BUNDLE_ID.test(normalized)) {
    return { bundleId: normalized, environment: "sandbox" };
  }
  return null;
}

type ParsedPushFields = {
  kind: PushKind;
  title: string | null;
  subtitle: string | null;
  text: string | null;
  workspaceId: string | null;
  surfaceId: string | null;
  macDeviceId: string | null;
  macInstanceTag: string | null;
  notificationId: string | null;
  replyShape: "none" | "text" | undefined;
  correlationId: string | null;
  expirationEpochSeconds: number | null;
  hasExpiration: boolean;
  encryptedList: unknown[];
  macPushPublicKey: string | null;
};

export function parsePushPayload(body: Record<string, unknown>): PushPayloadResult {
  const fields = parsePushFields(body);
  if (!fields.ok) return fields;
  const dismissedIds = parseDismissedIds(body.notificationIds);
  if (!dismissedIds.ok) return { ok: false, error: dismissedIds.error };
  if (fields.value.kind === "dismiss" && dismissedIds.value.length === 0 && fields.value.encryptedList.length === 0) {
    return { ok: false, error: "missing_dismissed_ids" };
  }
  return { ok: true, value: makePushPayload(fields.value, dismissedIds.value, body) };
}

function parsePushFields(body: Record<string, unknown>): { ok: true; value: ParsedPushFields } | { ok: false; error: string } {
  const kind: PushKind = body.kind === "dismiss" ? "dismiss" : "notify";
  const encrypted = parseEncryptedPayloads(body);
  if (!encrypted.ok) return encrypted;
  const hasEncryptedPayloads = encrypted.value.length > 0;
  const fields: ParsedPushFields = {
    kind,
    title: hasEncryptedPayloads ? "" : boundedString(body.title, MAX_PUSH_TITLE_CHARS),
    subtitle: hasEncryptedPayloads ? "" : body.subtitle == null ? "" : boundedString(body.subtitle, MAX_PUSH_SUBTITLE_CHARS),
    text: hasEncryptedPayloads ? "" : boundedString(body.body, MAX_PUSH_BODY_CHARS),
    workspaceId: hasEncryptedPayloads ? "" : body.workspaceId == null ? "" : boundedString(body.workspaceId, MAX_PUSH_ID_CHARS),
    surfaceId: hasEncryptedPayloads ? "" : body.surfaceId == null ? "" : boundedString(body.surfaceId, MAX_PUSH_ID_CHARS),
    macDeviceId: body.macDeviceId == null ? "" : boundedString(body.macDeviceId, MAX_PUSH_ID_CHARS),
    macInstanceTag: body.macInstanceTag == null ? "" : boundedString(body.macInstanceTag, MAX_PUSH_ID_CHARS),
    notificationId: body.notificationId == null ? "" : boundedString(body.notificationId, MAX_PUSH_ID_CHARS),
    replyShape: body.replyShape === "none" || body.replyShape === "text" ? body.replyShape : undefined,
    correlationId: body.correlationId == null ? "" : boundedString(body.correlationId, MAX_PUSH_CORRELATION_ID_CHARS),
    hasExpiration: Object.hasOwn(body, "expirationEpochSeconds"),
    expirationEpochSeconds: Object.hasOwn(body, "expirationEpochSeconds") ? parseExpiration(body.expirationEpochSeconds) : null,
    encryptedList: encrypted.value,
    macPushPublicKey: body.macPushPublicKey == null ? "" : boundedString(body.macPushPublicKey, 128),
  };
  const error = validatePushFields(fields);
  return error ? { ok: false, error } : { ok: true, value: fields };
}

function parseEncryptedPayloads(body: Record<string, unknown>): { ok: true; value: unknown[] } | { ok: false; error: string } {
  const encryptedPayloads = body.encryptedPayloads;
  if (encryptedPayloads != null && (!Array.isArray(encryptedPayloads) || encryptedPayloads.length === 0 || encryptedPayloads.length > MAX_ENCRYPTED_PUSH_PAYLOADS)) {
    return { ok: false, error: "missing_encrypted_payloads" };
  }
  const encryptedList = encryptedPayloads ?? [];
  if (encryptedList.some((entry) => !isEncryptedPushPayload(entry))) return { ok: false, error: "invalid_encrypted_payload" };
  if (encryptedList.length > 0) {
    const identities = new Set(encryptedList.map((entry) => entry.installationID));
    if (identities.size !== encryptedList.length) return { ok: false, error: "duplicate_encrypted_recipient" };
    if (["title", "subtitle", "body", "workspaceId", "surfaceId", "notificationIds"].some((key) => Object.hasOwn(body, key))) {
      return { ok: false, error: "plaintext_push_content" };
    }
  }
  return { ok: true, value: encryptedList };
}

function validatePushFields(fields: ParsedPushFields): string | null {
  const checks: Array<[string | null, string]> = [
    [fields.title, "title_too_long"], [fields.subtitle, "subtitle_too_long"], [fields.text, "body_too_long"],
    [fields.workspaceId, "workspace_id_too_long"], [fields.surfaceId, "surface_id_too_long"],
    [fields.macDeviceId, "mac_device_id_too_long"], [fields.macInstanceTag, "mac_instance_tag_too_long"],
    [fields.notificationId, "notification_id_too_long"], [fields.correlationId, "correlation_id_too_long"],
    [fields.macPushPublicKey, "invalid_mac_push_key"],
  ];
  for (const [value, error] of checks) if (value == null) return error;
  if (fields.correlationId && !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(fields.correlationId)) return "invalid_correlation_id";
  if (fields.hasExpiration && fields.expirationEpochSeconds == null) return "invalid_expiration";
  if (fields.kind === "notify" && !fields.title && !fields.text && fields.encryptedList.length === 0) return "empty_notification";
  return null;
}

function makePushPayload(fields: ParsedPushFields, dismissedIds: readonly string[], body: Record<string, unknown>): PushPayload {
  return {
    kind: fields.kind,
    title: fields.title!,
    subtitle: fields.subtitle || null,
    body: fields.text!,
    ...(fields.kind === "notify" && fields.replyShape ? { replyShape: fields.replyShape } : {}),
    workspaceId: fields.workspaceId || null,
    surfaceId: fields.surfaceId || null,
    macDeviceId: fields.macDeviceId || null,
    macInstanceTag: fields.macInstanceTag || null,
    notificationId: fields.notificationId || null,
    correlationId: fields.correlationId ? fields.correlationId.toLowerCase() : null,
    expirationEpochSeconds: fields.expirationEpochSeconds,
    dismissedIds: fields.kind === "dismiss" ? dismissedIds : [],
    badgeCount: parseBadgeCount(body.badgeCount),
    retargetsToLiveSurfaceOwner: fields.kind === "notify" ? body.retargetsToLiveSurfaceOwner !== false : false,
    hideContent: body.hideContent === true,
    ...(fields.encryptedList.length > 0 ? { encryptedPayloads: fields.encryptedList as Record<string, unknown>[] } : {}),
    ...(fields.macPushPublicKey ? { macPushPublicKey: fields.macPushPublicKey } : {}),
  };
}

function parseExpiration(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0) {
    return null;
  }
  return value;
}

/**
 * The badge count if usable, else `null` ("leave the badge alone"). Tolerant on
 * purpose: the badge is an enhancement, and a malformed count from an old or
 * odd client must not fail the whole push. Clamped to a sane ceiling so a
 * buggy sender cannot render a runaway number.
 */
function parseBadgeCount(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) return null;
  return Math.min(value, MAX_PUSH_BADGE_COUNT);
}

function parseDismissedIds(
  value: unknown,
): { readonly ok: true; readonly value: readonly string[] } | { readonly ok: false; readonly error: string } {
  if (value == null) return { ok: true, value: [] };
  if (!Array.isArray(value)) return { ok: false, error: "bad_notification_ids" };
  if (value.length > MAX_PUSH_DISMISS_IDS) return { ok: false, error: "too_many_notification_ids" };
  const ids: string[] = [];
  for (const entry of value) {
    const id = boundedString(entry, MAX_PUSH_ID_CHARS);
    if (id == null) return { ok: false, error: "notification_id_too_long" };
    if (id) ids.push(id);
  }
  return { ok: true, value: ids };
}

export async function readBoundedJsonObject(
  request: Request,
  maxBytes: number,
): Promise<JsonObjectResult> {
  const contentLength = request.headers.get("content-length");
  if (contentLength) {
    const parsedLength = Number(contentLength);
    if (Number.isFinite(parsedLength) && parsedLength > maxBytes) {
      return { ok: false, error: "request_too_large" };
    }
  }

  const textResult = await readBoundedText(request, maxBytes);
  if (!textResult.ok) return textResult;
  const text = textResult.value;
  if (!text) return { ok: true, value: {} };

  try {
    const raw = JSON.parse(text) as unknown;
    if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
      return { ok: false, error: "invalid_json" };
    }
    return { ok: true, value: raw as Record<string, unknown> };
  } catch {
    return { ok: false, error: "invalid_json" };
  }
}

async function readBoundedText(
  request: Request,
  maxBytes: number,
): Promise<{ readonly ok: true; readonly value: string } | { readonly ok: false; readonly error: "request_too_large" }> {
  if (!request.body) {
    return { ok: true, value: "" };
  }

  const reader = request.body.getReader();
  const chunks: Uint8Array[] = [];
  let totalBytes = 0;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    totalBytes += value.byteLength;
    if (totalBytes > maxBytes) {
      await reader.cancel();
      return { ok: false, error: "request_too_large" };
    }
    chunks.push(value);
  }

  const body = new Uint8Array(totalBytes);
  let offset = 0;
  for (const chunk of chunks) {
    body.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return { ok: true, value: new TextDecoder().decode(body) };
}
