import { describe, expect, test } from "bun:test";
import {
  DEFAULT_VM_EDGE_ALIAS_DOMAIN,
  VM_PLACEHOLDER_API_KEY,
  renderVmGuestModelPlaneEnvFile,
  vmEdgeAliasDomain,
  vmReflectionAliasDomain,
  vmGuestModelPlaneEnv,
} from "../services/coderouter/vmGuestEnv";

describe("static guest model-plane env", () => {
  test("every machine gets the same env: the alias origin and the placeholder key", () => {
    expect(vmGuestModelPlaneEnv()).toEqual({
      OPENAI_BASE_URL: `https://${DEFAULT_VM_EDGE_ALIAS_DOMAIN}/v1`,
      OPENAI_API_KEY: VM_PLACEHOLDER_API_KEY,
      CMUX_CODEROUTER_URL: `https://${DEFAULT_VM_EDGE_ALIAS_DOMAIN}`,
      ANTHROPIC_BASE_URL: `https://${DEFAULT_VM_EDGE_ALIAS_DOMAIN}`,
      ANTHROPIC_API_KEY: VM_PLACEHOLDER_API_KEY,
    });
    expect(vmEdgeAliasDomain(undefined)).toBe("coderouter.cmux.internal");
    expect(vmEdgeAliasDomain(" Models.Example.Test ")).toBe("models.example.test");
    expect(() => vmEdgeAliasDomain("https://x.y")).toThrow("bare host name");
    // The reflection alias follows the same rules; the guest env never names it
    // (the shim derives the path form from CMUX_CODEROUTER_URL).
    expect(vmReflectionAliasDomain(undefined)).toBe("reflection.cmux.internal");
    expect(vmReflectionAliasDomain(" Whoami.Example.Test ")).toBe("whoami.example.test");
    expect(() => vmReflectionAliasDomain("reflection cmux")).toThrow("bare host name");
  });

  test("renders the file agent-config.sh sources, single-quoted, never a token", () => {
    expect(renderVmGuestModelPlaneEnvFile({ OPENAI_BASE_URL: "https://a.b/v1", OPENAI_API_KEY: "place'holder", EMPTY: "" })).toBe(
      [
        "# generated by cmux; the same for every machine; managed, do not edit",
        "export OPENAI_BASE_URL='https://a.b/v1'",
        `export OPENAI_API_KEY='place'\\''holder'`,
        "",
      ].join("\n"),
    );
    expect(() => renderVmGuestModelPlaneEnvFile({ OPENAI_API_KEY: "crt_secret" })).toThrow("route token");
    expect(() => renderVmGuestModelPlaneEnvFile({ "BAD-KEY": "v" })).toThrow("shell identifier");
  });
});
