package com.cmux.internal;

/** Exact protocol-v2 operation spellings and classes. */
public enum Operations {
    MACHINE_LIST("machine.list", Class.READ),
    MACHINE_GET("machine.get", Class.READ),
    SESSION_LIST("session.list", Class.READ),
    SESSION_OPEN("session.open", Class.MUTATION),
    SESSION_GET("session.get", Class.READ),
    SESSION_SNAPSHOT("session.snapshot", Class.READ),
    SESSION_CREATION_RESOLVE("session.creation.resolve", Class.READ),
    SESSION_EVENTS("session.events", Class.STREAM_OPEN),
    SESSION_JOURNAL_SUBSCRIBE("session.journal.subscribe", Class.STREAM_OPEN),
    SESSION_PING("session.ping", Class.READ),
    SESSION_SHUTDOWN("session.shutdown", Class.MUTATION),
    SESSION_RELOAD_CONFIG("session.reload_config", Class.MUTATION),
    SESSION_TERMINAL_DEFAULTS_UPDATE("session.terminal_defaults.update", Class.MUTATION),
    SESSION_WINDOW_TITLE_SET("session.window.title.set", Class.MUTATION),
    SESSION_WINDOW_TITLE_CLEAR("session.window.title.clear", Class.MUTATION),
    CLIENT_LIST("client.list", Class.READ),
    CLIENT_GET("client.get", Class.READ),
    CLIENT_METADATA_UPDATE("client.metadata.update", Class.CONNECTION_CONTROL),
    CLIENT_SIZING_SET("client.sizing.set", Class.CONNECTION_CONTROL),
    CLIENT_SIZING_RELEASE("client.sizing.release", Class.CONNECTION_CONTROL),
    CLIENT_CELL_PIXELS_SET("client.cell_pixels.set", Class.CONNECTION_CONTROL),
    CLIENT_DETACH("client.detach", Class.CONNECTION_CONTROL),
    PAIRING_REQUEST_LIST("pairing_request.list", Class.READ),
    PAIRING_REQUEST_RESOLVE("pairing_request.resolve", Class.MUTATION),
    FRONTEND_PROJECTION_GET("frontend_projection.get", Class.READ),
    FRONTEND_PROJECTION_PUT("frontend_projection.put", Class.MUTATION),
    WORKSPACE_LIST("workspace.list", Class.READ),
    WORKSPACE_GET("workspace.get", Class.READ),
    WORKSPACE_CREATE("workspace.create", Class.MUTATION),
    WORKSPACE_RENAME("workspace.rename", Class.MUTATION),
    WORKSPACE_MOVE("workspace.move", Class.MUTATION),
    WORKSPACE_FOCUS("workspace.focus", Class.MUTATION),
    WORKSPACE_CLOSE("workspace.close", Class.MUTATION),
    WORKSPACE_RUN("workspace.run", Class.MUTATION),
    WORKSPACE_LAYOUT_APPLY("workspace.layout.apply", Class.MUTATION),
    SCREEN_LIST("screen.list", Class.READ),
    SCREEN_GET("screen.get", Class.READ),
    SCREEN_CREATE("screen.create", Class.MUTATION),
    SCREEN_RENAME("screen.rename", Class.MUTATION),
    SCREEN_FOCUS("screen.focus", Class.MUTATION),
    SCREEN_CLOSE("screen.close", Class.MUTATION),
    SCREEN_LAYOUT_EXPORT("screen.layout.export", Class.READ),
    SCREEN_LAYOUT_UNDO("screen.layout.undo", Class.MUTATION),
    PANE_LIST("pane.list", Class.READ),
    PANE_GET("pane.get", Class.READ),
    PANE_CREATE("pane.create", Class.MUTATION),
    PANE_SPLIT("pane.split", Class.MUTATION),
    PANE_RENAME("pane.rename", Class.MUTATION),
    PANE_FOCUS("pane.focus", Class.MUTATION),
    PANE_FOCUS_DIRECTION("pane.focus_direction", Class.MUTATION),
    PANE_NEIGHBOR_GET("pane.neighbor.get", Class.READ),
    PANE_SWAP("pane.swap", Class.MUTATION),
    PANE_ZOOM("pane.zoom", Class.MUTATION),
    PANE_SPLIT_RATIO_SET("pane.split_ratio.set", Class.MUTATION),
    PANE_VIEWPORT_WIDTH_SET("pane.viewport_width.set", Class.MUTATION),
    PANE_CLOSE("pane.close", Class.MUTATION),
    PANE_RUN("pane.run", Class.MUTATION),
    TAB_LIST("tab.list", Class.READ),
    TAB_GET("tab.get", Class.READ),
    TAB_CREATE_TERMINAL("tab.create_terminal", Class.MUTATION),
    TAB_CREATE_BROWSER("tab.create_browser", Class.MUTATION),
    TAB_RENAME("tab.rename", Class.MUTATION),
    TAB_MOVE("tab.move", Class.MUTATION),
    TAB_FOCUS("tab.focus", Class.MUTATION),
    TAB_CLOSE("tab.close", Class.MUTATION),
    TERMINAL_LIST("terminal.list", Class.READ),
    TERMINAL_GET("terminal.get", Class.READ),
    TERMINAL_INPUT_WRITE("terminal.input.write", Class.MUTATION),
    TERMINAL_INPUT_KEYS("terminal.input.keys", Class.MUTATION),
    TERMINAL_INPUT_MOUSE("terminal.input.mouse", Class.MUTATION),
    TERMINAL_INPUT_FOCUS("terminal.input.focus", Class.MUTATION),
    TERMINAL_SCREEN_READ("terminal.screen.read", Class.READ),
    TERMINAL_STATE_READ("terminal.state.read", Class.READ),
    TERMINAL_HISTORY_READ("terminal.history.read", Class.READ),
    TERMINAL_HISTORY_CLEAR("terminal.history.clear", Class.MUTATION),
    TERMINAL_WAIT("terminal.wait", Class.READ),
    TERMINAL_WAIT_EXIT("terminal.wait_exit", Class.READ),
    TERMINAL_COPY("terminal.copy", Class.READ),
    TERMINAL_PROCESS_GET("terminal.process.get", Class.READ),
    TERMINAL_RENDERER_GRANT_CREATE("terminal.renderer_grant.create", Class.CONNECTION_CONTROL),
    TERMINAL_VIEWER_RESIZE("terminal.viewer.resize", Class.CONNECTION_CONTROL),
    TERMINAL_VIEWER_RELEASE("terminal.viewer.release", Class.CONNECTION_CONTROL),
    TERMINAL_VIEWPORT_SCROLL("terminal.viewport.scroll", Class.MUTATION),
    TERMINAL_MOVE("terminal.move", Class.MUTATION),
    TERMINAL_PROJECT("terminal.project", Class.MUTATION),
    TERMINAL_ATTACH("terminal.attach", Class.STREAM_OPEN),
    TERMINAL_CLOSE("terminal.close", Class.MUTATION),
    BROWSER_LIST("browser.list", Class.READ),
    BROWSER_GET("browser.get", Class.READ),
    BROWSER_NAVIGATE("browser.navigate", Class.MUTATION),
    BROWSER_BACK("browser.back", Class.MUTATION),
    BROWSER_FORWARD("browser.forward", Class.MUTATION),
    BROWSER_RELOAD("browser.reload", Class.MUTATION),
    BROWSER_ACTIVATE("browser.activate", Class.MUTATION),
    BROWSER_INPUT_KEY("browser.input.key", Class.MUTATION),
    BROWSER_INPUT_TEXT("browser.input.text", Class.MUTATION),
    BROWSER_INPUT_MOUSE("browser.input.mouse", Class.MUTATION),
    BROWSER_INPUT_WHEEL("browser.input.wheel", Class.MUTATION),
    BROWSER_VIEWER_RESIZE("browser.viewer.resize", Class.CONNECTION_CONTROL),
    BROWSER_VIEWER_RELEASE("browser.viewer.release", Class.CONNECTION_CONTROL),
    BROWSER_ATTACH("browser.attach", Class.STREAM_OPEN),
    BROWSER_CLOSE("browser.close", Class.MUTATION),
    NOTIFICATION_LIST("notification.list", Class.READ),
    NOTIFICATION_CREATE("notification.create", Class.MUTATION),
    AGENT_LIST("agent.list", Class.READ),
    AGENT_REPORT("agent.report", Class.MUTATION),
    SIDEBAR_VIEW_GET("sidebar_view.get", Class.READ),
    SIDEBAR_VIEW_ENSURE("sidebar_view.ensure", Class.MUTATION),
    SIDEBAR_VIEW_ATTACH("sidebar_view.attach", Class.STREAM_OPEN),
    SIDEBAR_VIEW_INPUT("sidebar_view.input", Class.MUTATION),
    SIDEBAR_VIEW_RESIZE("sidebar_view.resize", Class.MUTATION),
    SIDEBAR_VIEW_RELOAD("sidebar_view.reload", Class.MUTATION),
    REQUEST_CANCEL("request.cancel", Class.CONNECTION_CONTROL),
    STREAM_CANCEL("stream.cancel", Class.CONNECTION_CONTROL);

    public enum Class {
        READ,
        MUTATION,
        STREAM_OPEN,
        CONNECTION_CONTROL
    }

    private final String wireName;
    private final Class operationClass;

    Operations(String wireName, Class operationClass) {
        this.wireName = wireName;
        this.operationClass = operationClass;
    }

    public String wireName() {
        return wireName;
    }

    public Class operationClass() {
        return operationClass;
    }
}
