import Foundation
import Testing
@testable import CmuxTerminalImport

@Suite("Mapping imported settings to Ghostty")
struct GhosttyImportMapperTests {
    let fixtures = TestFixtures()
    let themes = URL(fileURLWithPath: "/tmp/cmux themes", isDirectory: true)

    @Test("an iTerm2 profile becomes a theme file plus config keys")
    func iTerm2Plan() throws {
        let settings = try ITerm2ProfileParser().parse(preferences: fixtures.plist("iterm2.plist"))
        let mapper = GhosttyImportMapper(fontResolver: StubFontResolver(families: ["JetBrainsMono-Regular": "JetBrains Mono"]))
        let plan = mapper.plan(for: settings, themeDirectory: themes)

        #expect(plan.themeFiles.count == 1)
        #expect(plan.themeValue == "/tmp/cmux themes/cmux-import-iterm2")
        let theme = try #require(plan.themeFiles.first?.contents)
        #expect(theme.hasPrefix("# Generated by cmux import from iTerm2 (Work)\n"))
        #expect(theme.contains("palette = 0=#0000ff\n"))
        #expect(theme.contains("background = #1a1a1a\n"))
        #expect(theme.contains("selection-foreground = #ffffff\n"))

        #expect(plan.settings == [
            .init(key: "font-family", values: ["\"\"", "\"JetBrains Mono\""]),
            .init(key: "font-size", value: "14.5"),
            .init(key: "cursor-style", value: "bar"),
            .init(key: "cursor-style-blink", value: "false"),
            .init(key: "macos-option-as-alt", value: "left"),
            .init(key: "window-padding-x", value: "10"),
            .init(key: "window-padding-y", value: "6"),
            .init(key: "background-opacity", value: "0.8"),
            .init(key: "background-blur", value: "12"),
            .init(key: "scrollback-limit", value: "200000000"),
        ])
        #expect(plan.notes.contains { $0.contains("100000 lines") })
    }

    @Test("light and dark schemes select a conditional theme pair")
    func splitThemes() throws {
        let settings = try ITerm2ProfileParser().parse(preferences: fixtures.plist("iterm2-split.plist"))
        let plan = GhosttyImportMapper(fontResolver: StubFontResolver()).plan(for: settings, themeDirectory: themes)

        #expect(plan.themeFiles.map(\.url.lastPathComponent) == ["cmux-import-iterm2-light", "cmux-import-iterm2-dark"])
        #expect(plan.themeValue == "light:/tmp/cmux themes/cmux-import-iterm2-light,dark:/tmp/cmux themes/cmux-import-iterm2-dark")
        #expect(plan.notes.contains { $0.contains("Menlo-Regular") && $0.contains("not installed") })
        #expect(!plan.settings.contains { $0.key == "font-family" })
        #expect(plan.settings.contains { $0 == .init(key: "font-size", value: "12") })
        #expect(plan.notes.contains { $0.contains("Unlimited scrollback") })
        #expect(!plan.settings.contains { $0.key == "scrollback-limit" })
    }

    @Test("small scrollback keeps Ghostty's default and says why")
    func smallScrollback() {
        var settings = ImportedTerminalSettings(source: .kitty)
        settings.scrollbackLines = 5000
        let plan = GhosttyImportMapper(fontResolver: StubFontResolver()).plan(for: settings, themeDirectory: themes)
        #expect(plan.settings.isEmpty)
        #expect(plan.themeValue == nil)
        #expect(plan.isEmpty)
        #expect(plan.notes.contains { $0.contains("5000 lines") })
    }

    @Test("uneven padding keeps both sides and rounds to whole points")
    func padding() {
        var settings = ImportedTerminalSettings(source: .kitty)
        settings.paddingLeft = 8
        settings.paddingRight = 4.6
        settings.paddingTop = 3
        let plan = GhosttyImportMapper(fontResolver: StubFontResolver()).plan(for: settings, themeDirectory: themes)
        #expect(plan.settings == [
            .init(key: "window-padding-x", value: "8,5"),
            .init(key: "window-padding-y", value: "3"),
        ])
    }
}
