/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	IMPORT_TIMEOUT_MS: "150000";
	GITHUB_ARTIFACT_TOKEN: string;
	ARTIFACT_IMPORTS: DurableObjectNamespace<import("./src/index").ArtifactImport>;
	REQUEST_ADMISSION: DurableObjectNamespace<import("./src/index").RequestAdmission>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ArtifactImport" | "RequestAdmission";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IMPORT_TIMEOUT_MS" | "GITHUB_ARTIFACT_TOKEN">> {}
}
