import Foundation

/// A JPEG thumbnail generated by the Mac for an image artifact.
public struct ChatArtifactThumbnail: Sendable, Equatable, Codable {
    /// JPEG bytes decoded from the RPC's base64 payload.
    public let data: Data
    /// Thumbnail pixel width.
    public let pixelWidth: Int
    /// Thumbnail pixel height.
    public let pixelHeight: Int

    /// Creates a thumbnail payload.
    ///
    /// - Parameters:
    ///   - data: JPEG bytes.
    ///   - pixelWidth: Thumbnail pixel width.
    ///   - pixelHeight: Thumbnail pixel height.
    public init(data: Data, pixelWidth: Int, pixelHeight: Int) {
        self.data = data
        self.pixelWidth = pixelWidth
        self.pixelHeight = pixelHeight
    }

    private enum CodingKeys: String, CodingKey {
        case data = "data_b64"
        case pixelWidth = "pixel_width"
        case pixelHeight = "pixel_height"
    }
}
