public import Foundation

/// Maps ``ImportedTerminalSettings`` onto Ghostty config keys and generated theme files.
///
/// ```swift
/// let mapper = GhosttyImportMapper(fontResolver: CoreTextFontFamilyResolver())
/// let plan = mapper.plan(for: settings, themeDirectory: themesURL)
/// ```
public struct GhosttyImportMapper: Sendable {
    /// Ghostty's default `scrollback-limit`, in bytes.
    public static let ghosttyDefaultScrollbackBytes = 50_000_000
    /// Rough bytes one scrollback line costs in Ghostty (8-byte cells on a wide window plus row overhead).
    ///
    /// Ghostty limits scrollback by memory, not lines, so line counts are converted with this estimate.
    public static let estimatedScrollbackBytesPerLine = 2_000
    /// The largest padding, in points, written for one side; larger values would hide the grid.
    public static let maximumPadding = 1_000
    /// The strongest blur written; Ghostty warns that very high intensities render badly.
    public static let maximumBlur = 100

    private let fontResolver: any FontFamilyResolving

    /// Creates a mapper.
    ///
    /// - Parameter fontResolver: Resolves PostScript font names from iTerm2 and Terminal to family names.
    public init(fontResolver: any FontFamilyResolving) {
        self.fontResolver = fontResolver
    }

    /// Builds the write plan for imported settings.
    ///
    /// - Parameters:
    ///   - settings: What a parser read from the source terminal.
    ///   - themeDirectory: The directory generated theme files go in. The theme is
    ///     selected by absolute path, so it does not need to be on Ghostty's theme search path.
    /// - Returns: The theme files, the `theme` value, config settings and notes.
    public func plan(for settings: ImportedTerminalSettings, themeDirectory: URL) -> GhosttyImportPlan {
        var plan = GhosttyImportPlan(source: settings.source)
        plan.notes = settings.unmapped

        appendTheme(for: settings, themeDirectory: themeDirectory, to: &plan)
        appendFont(for: settings, to: &plan)

        if let shape = settings.cursorShape {
            plan.settings.append(.init(key: "cursor-style", value: shape.rawValue))
        }
        if let blink = settings.cursorBlink {
            plan.settings.append(.init(key: "cursor-style-blink", value: blink ? "true" : "false"))
        }
        if let optionAsAlt = settings.optionAsAlt {
            plan.settings.append(.init(key: "macos-option-as-alt", value: optionAsAlt.rawValue))
        }
        if let value = paddingValue(settings.paddingLeft, settings.paddingRight) {
            plan.settings.append(.init(key: "window-padding-x", value: value))
        }
        if let value = paddingValue(settings.paddingTop, settings.paddingBottom) {
            plan.settings.append(.init(key: "window-padding-y", value: value))
        }
        if let opacity = settings.backgroundOpacity, opacity.isFinite {
            plan.settings.append(.init(key: "background-opacity", value: Self.number(min(max(opacity, 0), 1))))
        }
        if let blur = settings.backgroundBlur {
            let intensity = min(blur, Self.maximumBlur)
            plan.settings.append(.init(key: "background-blur", value: intensity > 0 ? "\(intensity)" : "false"))
        }
        appendScrollback(for: settings, to: &plan)
        return plan
    }

    /// The Ghostty theme file body for a color scheme.
    ///
    /// - Parameters:
    ///   - scheme: The colors to write; unset colors are omitted.
    ///   - header: A comment line naming the source.
    /// - Returns: The file contents, ending in a newline.
    public func themeContents(for scheme: TerminalColorScheme, header: String) -> String {
        var lines = ["# \(header)"]
        for index in 0..<16 {
            if let color = scheme.palette[index] {
                lines.append("palette = \(index)=\(color.hexString)")
            }
        }
        let specials: [(String, TerminalColor?)] = [
            ("background", scheme.background),
            ("foreground", scheme.foreground),
            ("cursor-color", scheme.cursor),
            ("cursor-text", scheme.cursorText),
            ("selection-background", scheme.selectionBackground),
            ("selection-foreground", scheme.selectionForeground),
        ]
        for (key, color) in specials {
            if let color {
                lines.append("\(key) = \(color.hexString)")
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func appendTheme(
        for settings: ImportedTerminalSettings,
        themeDirectory: URL,
        to plan: inout GhosttyImportPlan
    ) {
        let baseName = "cmux-import-\(settings.source.rawValue)"
        let header = "Generated by cmux import from \(settings.source.displayName)"
            + (settings.profileName.map { " (\($0))" } ?? "")
        let darkOrOnly = settings.colors
        if let light = settings.lightColors, !light.isEmpty, !darkOrOnly.isEmpty {
            let lightURL = themeDirectory.appendingPathComponent("\(baseName)-light", isDirectory: false)
            let darkURL = themeDirectory.appendingPathComponent("\(baseName)-dark", isDirectory: false)
            plan.themeFiles.append(.init(url: lightURL, contents: themeContents(for: light, header: header + ", light")))
            plan.themeFiles.append(.init(url: darkURL, contents: themeContents(for: darkOrOnly, header: header + ", dark")))
            plan.themeValue = "light:\(lightURL.path),dark:\(darkURL.path)"
            return
        }
        let scheme = darkOrOnly.isEmpty ? (settings.lightColors ?? darkOrOnly) : darkOrOnly
        guard !scheme.isEmpty else { return }
        let url = themeDirectory.appendingPathComponent(baseName, isDirectory: false)
        plan.themeFiles.append(.init(url: url, contents: themeContents(for: scheme, header: header)))
        plan.themeValue = url.path
    }

    private func appendFont(for settings: ImportedTerminalSettings, to plan: inout GhosttyImportPlan) {
        if let name = settings.fontName?.trimmingCharacters(in: .whitespacesAndNewlines), !name.isEmpty {
            if !settings.fontNameIsPostScript {
                plan.settings.append(Self.fontFamily(name))
            } else if let family = fontResolver.familyName(forPostScriptName: name) {
                plan.settings.append(Self.fontFamily(family))
            } else {
                // A name Ghostty can't find would fall back silently, so keep the current font.
                plan.notes.append("Font \"\(name)\" is not installed system-wide (it may ship inside the app), so the font family stays as is.")
            }
        }
        if let size = settings.fontSize, size.isFinite, size > 0 {
            plan.settings.append(.init(key: "font-size", value: Self.number(size)))
        }
    }

    private func appendScrollback(for settings: ImportedTerminalSettings, to plan: inout GhosttyImportPlan) {
        let defaultMegabytes = Self.ghosttyDefaultScrollbackBytes / 1_000_000
        let defaultLines = Self.ghosttyDefaultScrollbackBytes / Self.estimatedScrollbackBytesPerLine
        if settings.unlimitedScrollback {
            plan.notes.append(
                "Unlimited scrollback: Ghostty has no unlimited mode, so the \(defaultMegabytes) MB default (about \(defaultLines) lines) stays."
            )
            return
        }
        guard let lines = settings.scrollbackLines, lines > 0 else { return }
        let (product, overflow) = lines.multipliedReportingOverflow(by: Self.estimatedScrollbackBytesPerLine)
        let bytes = overflow ? Int.max : product
        if bytes > Self.ghosttyDefaultScrollbackBytes {
            plan.settings.append(.init(key: "scrollback-limit", value: "\(bytes)"))
            plan.notes.append(
                "Scrollback of \(lines) lines became scrollback-limit = \(bytes) bytes (Ghostty limits scrollback by memory; about \(Self.estimatedScrollbackBytesPerLine) bytes a line)."
            )
        } else {
            plan.notes.append(
                "Scrollback of \(lines) lines: Ghostty's \(defaultMegabytes) MB default already holds about \(defaultLines) lines, so it stays."
            )
        }
    }

    /// Ghostty padding is whole points; one known side pads both.
    private func paddingValue(_ first: Double?, _ second: Double?) -> String? {
        func points(_ value: Double) -> Int { min(max(0, ConfigValue.int(value) ?? 0), Self.maximumPadding) }
        let finiteFirst = first.flatMap { $0.isFinite ? $0 : nil }
        let finiteSecond = second.flatMap { $0.isFinite ? $0 : nil }
        switch (finiteFirst, finiteSecond) {
        case (nil, nil):
            return nil
        case let (value?, nil), let (nil, value?):
            return "\(points(value))"
        case let (a?, b?):
            return points(a) == points(b) ? "\(points(a))" : "\(points(a)),\(points(b))"
        }
    }

    /// `font-family` as a reset followed by the family, so the import replaces the
    /// user's font list rather than adding a fallback after it.
    static func fontFamily(_ family: String) -> GhosttyConfigSetting {
        GhosttyConfigSetting(key: "font-family", values: ["\"\"", "\"\(family)\""])
    }

    /// Formats a number without a trailing `.0` and with at most two decimals.
    static func number(_ value: Double) -> String {
        guard value.isFinite else { return "0" }
        let rounded = (value * 100).rounded() / 100
        if rounded == rounded.rounded(), let whole = ConfigValue.int(rounded) {
            return String(whole)
        }
        var text = String(format: "%.2f", rounded)
        while text.hasSuffix("0") { text.removeLast() }
        return text
    }
}
