/// The localized workspace-group error messages, supplied by the app
/// conformance so they resolve against the app's `Localizable.xcstrings`.
///
/// The coordinator owns the error-envelope shaping (codes, data), while these
/// messages must keep their existing keys + default values and their per-locale
/// translations. Resolving `String(localized:)` inside the package would bind to
/// the package bundle, which lacks these keys, silently dropping the non-English
/// variants — so the app passes the already-resolved strings across the seam
/// instead. (Reference pattern: ``ControlNotificationStrings``.)
public struct ControlWorkspaceGroupStrings: Sendable, Equatable {
    /// `workspaceGroup.error.allChildrenAreAnchors` — "All requested children
    /// are ineligible because they are already group anchors; ungroup them
    /// first".
    public let allChildrenAreAnchors: String
    /// `workspaceGroup.error.workspaceIsOtherGroupAnchor` — "Workspace is the
    /// anchor of another group; ungroup it first".
    public let workspaceIsOtherGroupAnchor: String
    /// `workspaceGroup.error.invalidReferenceWorkspace` — "Reference workspace
    /// must be a member of the target group".
    public let invalidReferenceWorkspace: String
    /// `workspaceGroup.error.closeWorkspacesMustBeBoolean` — explicit
    /// destructive intent must be a JSON boolean.
    public let closeWorkspacesMustBeBoolean: String
    /// An identity field must be a string.
    public let idempotencyKeyMustBeString: String
    /// The two accepted identity aliases were supplied with different values.
    public let idempotencyKeysMustMatch: String
    /// An identity field cannot be blank.
    public let idempotencyKeyMustNotBeEmpty: String
    /// Generated-anchor cleanup intent must be a JSON boolean.
    public let removeGeneratedAnchorMustBeBoolean: String
    /// Generated-anchor cleanup is limited to anchor-only groups.
    public let generatedAnchorRequiresAnchorOnly: String
    /// The current anchor is not cmux-owned.
    public let generatedAnchorNotOwned: String
    /// The generated anchor could not be removed.
    public let generatedAnchorRemovalFailed: String
    /// `workspaceGroup.error.emptyPinnedCannotUngroup` — a pinned empty group
    /// must be removed through the explicit Delete Group action.
    public let emptyPinnedCannotUngroup: String

    /// Creates the localized message bundle.
    ///
    /// - Parameters:
    ///   - allChildrenAreAnchors: The all-children-are-anchors message.
    ///   - workspaceIsOtherGroupAnchor: The workspace-is-other-group-anchor
    ///     message.
    ///   - invalidReferenceWorkspace: The invalid-reference-workspace message.
    ///   - closeWorkspacesMustBeBoolean: The malformed destructive-intent message.
    ///   - idempotencyKeyMustBeString: The malformed identity message.
    ///   - idempotencyKeysMustMatch: The conflicting identity aliases message.
    ///   - idempotencyKeyMustNotBeEmpty: The blank identity message.
    ///   - removeGeneratedAnchorMustBeBoolean: The malformed cleanup-intent message.
    ///   - generatedAnchorRequiresAnchorOnly: The non-empty-group cleanup message.
    ///   - generatedAnchorNotOwned: The non-cmux anchor message.
    ///   - generatedAnchorRemovalFailed: The cleanup failure message.
    ///   - emptyPinnedCannotUngroup: The protected empty-group message.
    public init(
        allChildrenAreAnchors: String,
        workspaceIsOtherGroupAnchor: String,
        invalidReferenceWorkspace: String,
        closeWorkspacesMustBeBoolean: String,
        idempotencyKeyMustBeString: String = "idempotency_key must be a string",
        idempotencyKeysMustMatch: String = "external_id and idempotency_key must match",
        idempotencyKeyMustNotBeEmpty: String = "idempotency_key must not be empty",
        removeGeneratedAnchorMustBeBoolean: String = "remove_generated_anchor must be a boolean",
        generatedAnchorRequiresAnchorOnly: String = "Generated-anchor cleanup requires an anchor-only group",
        generatedAnchorNotOwned: String = "The group anchor was not generated by cmux",
        generatedAnchorRemovalFailed: String = "The generated group anchor could not be removed",
        emptyPinnedCannotUngroup: String = "A pinned empty group can only be removed with Delete Group"
    ) {
        self.allChildrenAreAnchors = allChildrenAreAnchors
        self.workspaceIsOtherGroupAnchor = workspaceIsOtherGroupAnchor
        self.invalidReferenceWorkspace = invalidReferenceWorkspace
        self.closeWorkspacesMustBeBoolean = closeWorkspacesMustBeBoolean
        self.idempotencyKeyMustBeString = idempotencyKeyMustBeString
        self.idempotencyKeysMustMatch = idempotencyKeysMustMatch
        self.idempotencyKeyMustNotBeEmpty = idempotencyKeyMustNotBeEmpty
        self.removeGeneratedAnchorMustBeBoolean = removeGeneratedAnchorMustBeBoolean
        self.generatedAnchorRequiresAnchorOnly = generatedAnchorRequiresAnchorOnly
        self.generatedAnchorNotOwned = generatedAnchorNotOwned
        self.generatedAnchorRemovalFailed = generatedAnchorRemovalFailed
        self.emptyPinnedCannotUngroup = emptyPinnedCannotUngroup
    }
}
