# cmux Cloud devbox agent config generator (/etc/cmux/agent-config.sh).
# Parity sources: the chatmux devbox agent-config (byte-identical
# body below the header; vm-devbox-image.test.ts pins it) and chatmux
# infra/sandbox-images/agent-config.sh. Sourced from
# /etc/profile.d/cmux-agents.sh (login/exec shells) and the bashrc chain
# (interactive shells).
#
# Materializes per-harness model-proxy configs from the machine's boot env
# (the model-plane vars listed in cmux_model_plane_vars, delivered at VM
# create; see web/services/coderouter/vmModelPlane.ts). The env carries
# base URLs, a public placeholder API key, and the VM id only: the real
# credential (the coderouter route token) is injected by the provider's TLS
# edge into every request the guest makes to the coderouter host, so no
# secret ever lands on the machine and no config below carries one.
# Idempotent and silent: each harness config is written only when missing,
# so a user who edits or deletes one keeps control.
#
# Create-time envs are not replayed on every provider (resurrect;
# Freestyle has no VM-level create env at all), so shells that see the boot
# env persist it 0600 on disk, and shells that do not re-source the
# persisted copy. The persisted file always mirrors the newest boot env.

# The edge terminates the coderouter session with the platform CA it
# installs at boot. curl, python, bun, and codex trust the system store;
# Node (Claude Code, pi) does not, so point it at the CA when present. A
# user-set NODE_EXTRA_CA_CERTS wins.
if [ -z "${NODE_EXTRA_CA_CERTS-}" ] && [ -f /usr/local/share/ca-certificates/freestyle-tls.crt ]; then
  NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/freestyle-tls.crt
  export NODE_EXTRA_CA_CERTS
fi

cmux_write_agent_configs() {
  # Every model-plane var, persisted generically; OPENAI_BASE_URL is the
  # anchor: its presence means a boot env is present.
  cmux_model_plane_vars="OPENAI_BASE_URL OPENAI_API_KEY CMUX_CODEROUTER_URL ANTHROPIC_BASE_URL ANTHROPIC_API_KEY CMUX_VM_ID"
  if [ -n "${OPENAI_BASE_URL-}" ]; then
    mkdir -p "$HOME/.config/cmux" 2>/dev/null && (
      umask 077
      {
        echo "# generated by cmux from machine boot env; managed, do not edit"
        for cmux_var in $cmux_model_plane_vars; do
          eval "cmux_val=\${$cmux_var-}"
          if [ -n "$cmux_val" ]; then
            printf "export %s='%s'\n" "$cmux_var" "$(printf '%s' "$cmux_val" | sed "s/'/'\\\\''/g")"
          fi
        done
      } > "$HOME/.config/cmux/model-plane.env" 2>/dev/null
    )
  elif [ -f "$HOME/.config/cmux/model-plane.env" ]; then
    . "$HOME/.config/cmux/model-plane.env" 2>/dev/null || true
  elif [ -f /etc/cmux/model-plane.env ]; then
    # Baked into the image: the same alias origin for every machine; the
    # machine's TLS edge rule routes it and adds the credential.
    . /etc/cmux/model-plane.env 2>/dev/null || true
  fi
  unset cmux_model_plane_vars cmux_var cmux_val

  # codex: a CUSTOM provider, not the built-in openai one. WebSockets are
  # gated per provider by supports_websockets (codex-rs
  # model_provider_info: serde default false; client.rs
  # responses_websocket_enabled checks nothing else), so a custom provider
  # is already HTTP-only. It is pinned false explicitly anyway: the /v1 data
  # plane serves only the plain HTTP Responses API, and an implicit default
  # can move under a codex upgrade. Auth comes from OPENAI_API_KEY at request
  # time (env_key); it is the public placeholder, and the edge adds the real
  # credential, so a rotated token needs no config rewrite.
  #
  # config.toml has a second writer: `cmux-tui agent hook install codex` keeps
  # its hook trust state under [hooks] there (the bake runs it before any
  # shell has seen a boot env). A file that lacks model_provider is one of
  # those: the provider goes in around it, top-level key first (TOML keeps
  # bare keys above the first table header) and the tables last, so the
  # trust state is preserved. A file that already names a provider, or that
  # carries our tables, is left to whoever wrote it.
  # Parse logical TOML keys, including quoted and dotted forms. Invalid user
  # configuration is preserved so a shell startup cannot damage it further.
  if [ -n "${OPENAI_BASE_URL-}" ] && python3 - "$HOME/.codex/config.toml" 2>/dev/null <<'CMUX_TOML_CHECK'
import pathlib, sys, tomllib
config = pathlib.Path(sys.argv[1])
data = tomllib.loads(config.read_text()) if config.exists() else {}
providers = data.get("model_providers", {})
managed = "model_provider" in data or "history" in data or not isinstance(providers, dict) or "cmux" in providers
sys.exit(1 if managed else 0)
CMUX_TOML_CHECK
  then
    mkdir -p "$HOME/.codex" 2>/dev/null && {
      echo "# generated by cmux from machine boot env; delete to manage manually"
      echo "model_provider = \"cmux\""
      echo ""
      if [ -f "$HOME/.codex/config.toml" ]; then
        cat "$HOME/.codex/config.toml"
        echo ""
      fi
      echo "[model_providers.cmux]"
      echo "name = \"cmux\""
      echo "base_url = \"$OPENAI_BASE_URL\""
      echo "env_key = \"OPENAI_API_KEY\""
      echo "wire_api = \"responses\""
      echo "requires_openai_auth = false"
      echo "supports_websockets = false"
      echo ""
      echo "# usage attribution per cmux workspace/terminal; env_http_headers"
      echo "# skips a header whose variable is unset (plain SSH, exec API)"
      echo "[model_providers.cmux.env_http_headers]"
      echo "\"x-cmux-workspace-id\" = \"CMUX_WORKSPACE_ID\""
      echo "\"x-cmux-surface-id\" = \"CMUX_SURFACE_ID\""
      echo ""
      echo "[history]"
      echo "persistence = \"save-all\""
    } > "$HOME/.codex/config.toml.cmux-tmp" 2>/dev/null && mv -f "$HOME/.codex/config.toml.cmux-tmp" "$HOME/.codex/config.toml" 2>/dev/null
  fi

  # pi: override the built-in openai-codex provider, whose
  # openai-codex-responses implementation speaks the exact dialect the /v1
  # plane proxies (it appends /codex/responses to baseUrl, which the plane
  # serves). pi derives a chatgpt-account-id header from its apiKey
  # client-side and refuses a non-JWT, so the apiKey carries the same public
  # placeholder JWT the `cr pi` extension ships. No route-token header is
  # configured: the edge supplies it on every request. baseUrl must be a
  # literal (pi does not env-resolve it), hence this generator.
  if [ -n "${OPENAI_BASE_URL-}" ] && [ ! -e "$HOME/.pi/agent/models.json" ]; then
    mkdir -p "$HOME/.pi/agent" 2>/dev/null && {
      echo '{'
      echo '  "providers": {'
      echo '    "openai-codex": {'
      echo '      "name": "cmux",'
      echo "      \"baseUrl\": \"$OPENAI_BASE_URL\","
      echo '      "apiKey": "e30.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsiY2hhdGdwdF9hY2NvdW50X2lkIjoiY29kZXJvdXRlciJ9fQ.signature"'
      echo '    }'
      echo '  }'
      echo '}'
    } > "$HOME/.pi/agent/models.json" 2>/dev/null
  fi

  # claude: ANTHROPIC_BASE_URL and the placeholder ANTHROPIC_API_KEY in the
  # env are all Claude Code needs for the model plane. A fresh HOME still
  # blocks an interactive run on three first-run gates before the prompt is
  # usable: the theme/onboarding wizard, the folder-trust dialog, and the
  # --dangerously-skip-permissions confirmation. Seed the flags those gates
  # write. Not env-gated: the gates block regardless of the model plane.
  # The "/" trust entry covers plain directories only; claude's trust lookup
  # is exact-path and stops at a git root, so CLAUDE_CODE_SANDBOXED below is
  # what trusts a cloned repo. bypassPermissionsModeAccepted is the legacy
  # spelling of the bypass acceptance; the documented key,
  # skipDangerousModePermissionPrompt, rides
  # /etc/claude-code/managed-settings.json (written at image build).
  # A fourth gate is the custom-API-key consent ("Detected a custom API key
  # in your environment ... use this API key?", seen live on 2.1.252 and
  # still gated the same way on 2.1.267): claude
  # records answers under customApiKeyResponses as the key's LAST 20
  # characters, so the placeholder key from the env is pre-approved the same
  # way. Derived from the env so a placeholder change cannot desync it.
  if [ ! -e "$HOME/.claude.json" ]; then
    cmux_claude_key_tail=""
    if [ -n "${ANTHROPIC_API_KEY-}" ]; then
      cmux_claude_key_tail=$(printf '%s' "$ANTHROPIC_API_KEY" | tail -c 20)
    fi
    (
      umask 077
      {
        echo '{'
        echo '  "hasCompletedOnboarding": true,'
        echo '  "bypassPermissionsModeAccepted": true,'
        echo '  "theme": "dark",'
        if [ -n "$cmux_claude_key_tail" ]; then
          printf '  "customApiKeyResponses": { "approved": ["%s"], "rejected": [] },\n' "$cmux_claude_key_tail"
        fi
        echo '  "projects": { "/": { "hasTrustDialogAccepted": true } }'
        echo '}'
      } > "$HOME/.claude.json"
    ) 2>/dev/null
    unset cmux_claude_key_tail
  fi

}

# Optional provider discovery belongs to OpenCode launch, never shell startup.
# Python owns the advisory lock so process exit releases it even after a crash.
cmux_ensure_opencode_config() {
  [ -e "$HOME/.config/opencode/opencode.json" ] && return 0
  [ -n "${CMUX_CODEROUTER_URL-}" ] && [ -n "${OPENAI_API_KEY-}" ] || return 0
  python3 - <<'CMUX_OPENCODE_CONFIG'
import fcntl, hashlib, json, os, pathlib, re, subprocess, sys, tempfile, time

config = pathlib.Path.home() / ".config/opencode/opencode.json"
origin = os.environ["CMUX_CODEROUTER_URL"].rstrip("/")
key = os.environ["OPENAI_API_KEY"]
state = pathlib.Path.home() / ".cache/cmux"
state.mkdir(parents=True, exist_ok=True, mode=0o700)
scope = hashlib.sha256((origin + "\0" + key).encode()).hexdigest()
failure = state / ("opencode-config-" + scope + ".failed")

def unavailable():
    print("cmux: OpenCode provider configuration is unavailable; retry in one minute.", file=sys.stderr)
    sys.exit(75)

def redact(value):
    if isinstance(value, dict):
        return {k: redact(v) for k, v in value.items()}
    if isinstance(value, list):
        return [redact(v) for v in value]
    if isinstance(value, str):
        return re.sub(r"crt_[A-Za-z0-9._-]+", "{env:OPENAI_API_KEY}", value.replace(key, "{env:OPENAI_API_KEY}"))
    return value

with (state / "opencode-config.lock").open("a") as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    # Waiting callers must observe the result of the first request before
    # deciding to retry or launch. Existing user configuration always wins.
    if config.exists() or config.is_symlink():
        sys.exit(0)
    try:
        age = time.time() - float(failure.read_text())
        if 0 <= age < 60:
            unavailable()
    except (FileNotFoundError, ValueError):
        pass
    try:
        result = subprocess.run(
            ["curl", "-fsS", "--connect-timeout", "2", "-m", "10",
             "-H", "authorization: Bearer " + key,
             origin + "/api/coderouter/opencode/config"],
            capture_output=True, timeout=12, check=True,
        )
        document = json.loads(result.stdout)
        if not isinstance(document, dict) or not isinstance(document.get("provider"), dict) or not document["provider"]:
            raise ValueError("missing provider catalog")
        document = redact(document)
        config.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        fd, temporary = tempfile.mkstemp(prefix=".cmux-config-", dir=config.parent)
        try:
            with os.fdopen(fd, "w") as output:
                json.dump(document, output)
                output.write("\n")
                output.flush()
                os.fsync(output.fileno())
            try:
                # Atomic write-if-absent, never replace a user edit made while
                # the request was in flight, including an existing symlink.
                os.link(temporary, config)
            except FileExistsError:
                pass
        finally:
            os.unlink(temporary)
        failure.unlink(missing_ok=True)
    except (OSError, ValueError, subprocess.SubprocessError):
        if config.exists() or config.is_symlink():
            sys.exit(0)
        failure.write_text(str(time.time()))
        unavailable()
CMUX_OPENCODE_CONFIG
}

# The installed executable wrapper also covers exec/direct agent launches.
# This function retains the lazy path when this file is updated independently.
opencode() {
  if [ "$#" -eq 1 ]; then
    case "$1" in --version|-v|--help|-h) command opencode "$@"; return $? ;; esac
  fi
  cmux_ensure_opencode_config || return $?
  command opencode "$@"
}

# claude folder-trust gate: claude's trust check short-circuits on
# CLAUDE_CODE_SANDBOXED (the escape its own self-hosted runner provisioning
# uses), which describes this machine exactly: a disposable cloud VM the user
# owns. The ~/.claude.json seed above cannot express this for git repos,
# because the trust lookup is exact-path and the paths users clone are
# unknowable at image build. Exported for every shell (this file is sourced
# from /etc/profile.d and the bashrc chain).
export CLAUDE_CODE_SANDBOXED=1

# claude root gate, separate from the trust dialog: claude refuses
# --dangerously-skip-permissions under uid 0 unless IS_SANDBOX=1, its
# documented container escape. cmux-tui sessions and the exec API run as
# root, so without it the seeded `claude --dangerously-skip-permissions`
# launch dies at start. The VM, not the uid, is the isolation boundary here.
export IS_SANDBOX=1

# claude self-update: the npm install auto-updates itself in the background
# on the first interactive launch (2.1.252 -> latest within 20 s, verified
# live on the trust3 bake), reinstalling the package under nvm. That defeats
# the image pin and leaves `claude` briefly unresolvable while npm relinks
# the bin. The binary is image-baked; new versions ship by rebake
# (`bun run devbox:pins:check --write` in web/, then promote).
export DISABLE_AUTOUPDATER=1

# codex folder-trust gate: codex has no sandbox env short-circuit and its
# trust lookup matches config keys EXACTLY against the cwd or its git root,
# no ancestor walk, so the managed defaults (/etc/codex/managed_config.toml,
# baked at image build) can only pre-trust the HOMEs, never a cloned repo.
# Inject the launch directory's trust per invocation instead: -c overrides
# merge as a config layer, so other projects entries survive. For a linked
# worktree codex keys trust by the MAIN checkout root, so trust that too.
# Paths a TOML string cannot carry raw (quote, backslash, unprintable) are
# skipped; codex then prompts, which beats failing its config parse.
codex() {
  local sub main d entries
  sub=$(git rev-parse --show-toplevel 2>/dev/null) || sub=$PWD
  main=$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null) || main=""
  case $main in */.git) main=${main%/.git} ;; *) main="" ;; esac
  if [ "$main" = "$sub" ]; then main=""; fi
  entries=""
  for d in "$sub" "$main"; do
    case $d in ''|*[\"\\]*|*[![:print:]]*) continue ;; esac
    entries="${entries:+$entries, }\"$d\" = { trust_level = \"trusted\" }"
  done
  if [ -n "$entries" ]; then
    command codex -c "projects={ $entries }" "$@"
  else
    command codex "$@"
  fi
}

# usage attribution: cmux-tui exports CMUX_WORKSPACE_ID and CMUX_SURFACE_ID
# into every terminal it opens; the coderouter ledger keys usage by them so
# `cmux coderouter usage` can break spend down per workspace and terminal.
# Claude Code takes extra request headers from ANTHROPIC_CUSTOM_HEADERS (one
# "Name: value" per line); codex reads the same ids through the
# env_http_headers table generated above. A user-set value wins. Outside a
# cmux-tui terminal the variables are unset and no header is sent.
if [ -n "${CMUX_WORKSPACE_ID-}" ] && [ -z "${ANTHROPIC_CUSTOM_HEADERS-}" ]; then
  ANTHROPIC_CUSTOM_HEADERS="x-cmux-workspace-id: $CMUX_WORKSPACE_ID"
  if [ -n "${CMUX_SURFACE_ID-}" ]; then
    ANTHROPIC_CUSTOM_HEADERS="$ANTHROPIC_CUSTOM_HEADERS
x-cmux-surface-id: $CMUX_SURFACE_ID"
  fi
  export ANTHROPIC_CUSTOM_HEADERS
fi

cmux_write_agent_configs
unset -f cmux_write_agent_configs
