from __future__ import annotations

import builtins
import json
import keyword
import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any

from codegen.ir import SdkIR
from codegen.writer import Emitter


HEADER = """# Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
# Source: cmux-tui/spec/sdk-schema.json
"""

# Wire objects are semantically unordered, while Python positional parameters
# are not. Keep the few multi-argument commands in the order a Python caller
# naturally reads them.
COMMAND_FIELD_ORDER = {
    "apply-layout": ("layout", "workspace", "name", "cols", "rows"),
    "browser-key": (
        "surface",
        "kind",
        "key",
        "code",
        "windows_virtual_key_code",
        "modifiers",
        "text",
    ),
    "browser-mouse": ("surface", "kind", "x_px", "y_px", "button", "click_count"),
    "browser-wheel": ("surface", "x_px", "y_px", "delta_y_px"),
    "close-provider-managed-workspace": ("workspace", "key", "authority"),
    "close-workspace": (
        "workspace",
        "key",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "create-terminal": (
        "workspace",
        "key",
        "argv",
        "command",
        "cwd",
        "name",
        "cols",
        "rows",
        "terminal_id",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "create-workspace": (
        "name",
        "key",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "get-frontend-projection": ("frontend", "scope", "subject_key"),
    "move-terminal": (
        "terminal_id",
        "workspace_key",
        "terminal_incarnation",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "new-browser-tab": ("url", "pane", "cols", "rows"),
    "new-tab": ("pane", "cwd", "cols", "rows"),
    "new-workspace": ("name", "cols", "rows"),
    "notify": ("title", "body", "level", "surface"),
    "put-frontend-projection": (
        "frontend",
        "scope",
        "subject_key",
        "schema_version",
        "expected_projection_revision",
        "projection",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "read-scrollback": ("surface", "start", "count"),
    "rename-provider-managed-workspace": ("workspace", "key", "name", "authority"),
    "rename-workspace": (
        "name",
        "workspace",
        "key",
        "expected_revision",
        "expected_generation",
        "origin",
        "mutation_id",
    ),
    "report-agent": ("surface", "state", "source", "session"),
    "run": (
        "pane",
        "argv",
        "command",
        "cwd",
        "new_workspace",
        "key",
        "name",
        "cols",
        "rows",
    ),
    "select-screen": ("index", "delta"),
    "select-tab": ("pane", "index", "delta"),
    "select-workspace": ("index", "delta"),
    "send": ("surface", "text", "bytes", "paste"),
    "set-cell-pixels": ("width_px", "height_px"),
    "set-client-info": ("name", "kind"),
    "set-client-sizing": ("surface", "enabled", "client", "exclusive"),
    "set-default-colors": (
        "fg",
        "bg",
        "cursor",
        "selection_bg",
        "selection_fg",
        "cursor_style",
        "cursor_blink",
        "palette",
        "complete",
    ),
    "set-split-ratio": ("split", "ratio"),
    "shutdown-daemon": ("pid", "generation", "force"),
    "subscribe": ("surface", "tree_events"),
}


@dataclass(frozen=True)
class Model:
    path: str
    name: str
    expression: Mapping[str, Any]
    event: bool = False


def _plain(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _plain(item) for key, item in value.items()}
    if isinstance(value, (tuple, list)):
        return [_plain(item) for item in value]
    return value


def _pascal(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]", value) if part)


def _snake(value: str) -> str:
    name = value.replace("-", "_")
    if keyword.iskeyword(name):
        return name + "_"
    if name == "bytes":
        return "bytes_data"
    if name == "self":
        return "is_self"
    if name in dir(builtins) and name in {"id", "type"}:
        return name
    return name


def _quote(value: Any) -> str:
    return repr(value)


class PythonEmitter:
    def __init__(self, value: SdkIR):
        self.ir = value
        self.document = _plain(value.document)
        self.models: dict[str, Model] = {}
        self._collect_models()

    def _register(
        self,
        expression: Mapping[str, Any],
        path: str,
        name: str,
        *,
        event: bool = False,
    ) -> None:
        kind = expression["kind"]
        if kind == "object":
            self.models[path] = Model(path, name, expression, event)
            for wire_name, field in expression["fields"].items():
                self._register(
                    field["type"],
                    f"{path}/fields/{wire_name}/type",
                    name + _pascal(wire_name),
                )
        elif kind == "tagged_union":
            for variant, variant_type in expression["variants"].items():
                self._register(
                    variant_type,
                    f"{path}/variants/{variant}",
                    name + _pascal(str(variant)),
                    event=event,
                )
        elif kind == "untagged_union":
            for index, variant_type in enumerate(expression["variants"]):
                self._register(
                    variant_type,
                    f"{path}/variants/{index}",
                    name + f"Variant{index + 1}",
                    event=event,
                )
        elif kind == "array":
            self._register(expression["items"], f"{path}/items", name + "Item")
        elif kind == "map":
            self._register(expression["values"], f"{path}/values", name + "Value")
        elif kind == "alias":
            self._register(expression["target"], f"{path}/target", name + "Value")

    def _collect_models(self) -> None:
        for name, expression in self.document["types"].items():
            self._register(expression, f"types/{name}", name)
        for wire_name, command in self.document["commands"].items():
            base = _pascal(wire_name)
            self._register(command["request"], f"commands/{wire_name}/request", base + "Request")
            self._register(command["result"], f"commands/{wire_name}/result", base + "Result")
        for wire_name, event in self.document["events"].items():
            self._register(
                event["payload"],
                f"events/{wire_name}/payload",
                _pascal(wire_name) + "Event",
                event=True,
            )

    def annotation(self, expression: Mapping[str, Any], path: str) -> str:
        kind = expression["kind"]
        if kind == "scalar":
            return {
                "string": "str",
                "boolean": "bool",
                "int32": "int",
                "uint16": "int",
                "uint32": "int",
                "int64": "int",
                "uint64": "int",
                "float32": "float",
                "float64": "float",
            }[expression["name"]]
        if kind == "literal":
            return f"Literal[{_quote(expression['value'])}]"
        if kind == "enum":
            values = ", ".join(_quote(item) for item in expression["values"])
            return f"Literal[{values}]"
        if kind == "object":
            return self.models[path].name
        if kind == "alias":
            return self.annotation(expression["target"], f"{path}/target")
        if kind == "tagged_union":
            variants = [
                self.annotation(item, f"{path}/variants/{name}")
                for name, item in expression["variants"].items()
            ]
            return f"Union[{', '.join(variants)}]"
        if kind == "untagged_union":
            variants = [
                self.annotation(item, f"{path}/variants/{index}")
                for index, item in enumerate(expression["variants"])
            ]
            return f"Union[{', '.join(variants)}]"
        if kind == "array":
            return f"List[{self.annotation(expression['items'], f'{path}/items')}]"
        if kind == "map":
            return f"Dict[str, {self.annotation(expression['values'], f'{path}/values')}]"
        if kind == "ref":
            return expression["name"]
        if kind == "opaque_json":
            return "Any"
        raise ValueError(f"unsupported Python type expression {kind!r}")

    @staticmethod
    def field_annotation(annotation: str, field: Mapping[str, Any]) -> str:
        choices = [annotation]
        if field["nullable"]:
            choices.append("None")
        if field["presence"] == "optional":
            choices.append("MissingType")
        if len(choices) == 1:
            return annotation
        return f"Union[{', '.join(choices)}]"

    @staticmethod
    def ergonomic_fields(
        fields: list[tuple[str, Mapping[str, Any]]],
    ) -> list[tuple[str, Mapping[str, Any]]]:
        selectors = {
            "surface": 0,
            "pane": 1,
            "screen": 2,
            "workspace": 3,
            "split": 4,
            "terminal_id": 5,
            "client": 6,
            "request": 7,
        }
        return sorted(
            fields,
            key=lambda item: (selectors.get(item[0], 100), fields.index(item)),
        )

    def command_fields(
        self,
        command: str,
        fields: list[tuple[str, Mapping[str, Any]]],
    ) -> list[tuple[str, Mapping[str, Any]]]:
        explicit = COMMAND_FIELD_ORDER.get(command)
        if explicit is None:
            return self.ergonomic_fields(fields)
        positions = {name: index for index, name in enumerate(explicit)}
        return sorted(
            fields,
            key=lambda item: (positions.get(item[0], len(positions)), fields.index(item)),
        )

    def models_module(self) -> str:
        lines = [
            HEADER,
            "from __future__ import annotations",
            "",
            "import base64",
            "from dataclasses import dataclass, field",
            "from enum import Enum",
            "from typing import Any, ClassVar, Dict, List, Literal, Mapping, Optional, Union",
            "",
            "",
            "class MissingType:",
            "    __slots__ = ()",
            "",
            "    def __repr__(self) -> str:",
            '        return "MISSING"',
            "",
            "    def __bool__(self) -> bool:",
            "        return False",
            "",
            "",
            "MISSING = MissingType()",
            "",
            "",
            "class EventBase:",
            "    @property",
            "    def bytes_data(self) -> Optional[bytes]:",
            '        for name in ("data", "replay", "png"):',
            "            value = getattr(self, name, MISSING)",
            "            if value is not MISSING and value is not None:",
            "                return base64.b64decode(value, validate=True)",
            "        return None",
            "",
            "",
            "@dataclass(frozen=True)",
            "class UnknownEvent(EventBase):",
            "    event: str",
            "    raw: Mapping[str, Any]",
            "",
        ]

        enum_names: list[str] = []
        for name, expression in self.document["types"].items():
            if expression["kind"] != "enum":
                continue
            values = expression["values"]
            enum_names.append(name)
            if all(isinstance(value, str) for value in values):
                lines.extend([f"class {name}(str, Enum):"])
            else:
                lines.extend([f"class {name}(Enum):"])
            used: set[str] = set()
            for index, value in enumerate(values):
                member = re.sub(r"[^A-Za-z0-9]+", "_", str(value)).strip("_").upper()
                if not member or member[0].isdigit():
                    member = f"VALUE_{index + 1}"
                while member in used:
                    member += "_"
                used.add(member)
                lines.append(f"    {member} = {_quote(value)}")
            lines.append("")

        for model in self.models.values():
            expression = model.expression
            fields = list(expression["fields"].items())
            command = (
                model.path.split("/")[1]
                if model.path.startswith("commands/") and model.path.endswith("/request")
                else None
            )
            order = (
                (lambda value: self.command_fields(command, value))
                if command is not None
                else self.ergonomic_fields
            )
            required = order(
                [item for item in fields if item[1]["presence"] == "required"]
            )
            optional = order(
                [item for item in fields if item[1]["presence"] == "optional"]
            )
            base = "(EventBase)" if model.event else ""
            lines.extend(["", "@dataclass(frozen=True)", f"class {model.name}{base}:"])
            lines.append(f"    __cmux_schema_path__: ClassVar[str] = {_quote(model.path)}")
            if not fields and not expression.get("additional_properties") and not model.event:
                lines.append("    pass")
            for wire_name, field_spec in required + optional:
                python_name = _snake(wire_name)
                annotation = self.annotation(
                    field_spec["type"], f"{model.path}/fields/{wire_name}/type"
                )
                annotation = self.field_annotation(annotation, field_spec)
                metadata = ""
                if python_name != wire_name:
                    metadata = f", metadata={{'wire_name': {_quote(wire_name)}}}"
                if field_spec["presence"] == "optional":
                    lines.append(
                        f"    {python_name}: {annotation} = field(default=MISSING{metadata})"
                    )
                elif metadata:
                    lines.append(f"    {python_name}: {annotation} = field({metadata[2:]})")
                else:
                    lines.append(f"    {python_name}: {annotation}")
            if expression.get("additional_properties"):
                lines.append(
                    "    extra: Mapping[str, Any] = field(default_factory=dict, "
                    "metadata={'cmux_extra': True})"
                )
            if model.event:
                lines.append(
                    "    raw: Mapping[str, Any] = field(default_factory=dict, "
                    "repr=False, compare=False, metadata={'cmux_skip': True})"
                )
            lines.append("")

        aliases: list[str] = []
        for name, expression in self.document["types"].items():
            kind = expression["kind"]
            if kind in {"object", "enum"}:
                continue
            aliases.append(name)
            aliases.append(self.annotation(expression, f"types/{name}"))
        if aliases:
            lines.extend(["", "# Named protocol aliases."])
            for index in range(0, len(aliases), 2):
                lines.append(f"{aliases[index]} = {aliases[index + 1]}")

        event_names = [
            self.models[f"events/{name}/payload"].name
            for name in self.document["events"]
            if f"events/{name}/payload" in self.models
        ]
        if event_names:
            lines.extend(
                [
                    "",
                    f"KnownEvent = Union[{', '.join(event_names)}]",
                    "AnyEvent = Union[KnownEvent, UnknownEvent]",
                ]
            )
        else:
            lines.extend(["", "KnownEvent = UnknownEvent", "AnyEvent = UnknownEvent"])

        exported = [
            "MISSING",
            "MissingType",
            "EventBase",
            "UnknownEvent",
            "KnownEvent",
            "AnyEvent",
            *enum_names,
            *(model.name for model in self.models.values()),
            *self.document["types"].keys(),
        ]
        lines.extend(
            [
                "",
                "__all__ = [",
                *(f"    {_quote(name)}," for name in dict.fromkeys(exported)),
                "]",
                "",
            ]
        )
        return "\n".join(lines)

    def schema_module(self) -> str:
        encoded = json.dumps(self.document, ensure_ascii=False, separators=(",", ":"))
        return "\n".join(
            [
                HEADER,
                "from __future__ import annotations",
                "",
                "import json",
                "",
                f"SCHEMA = json.loads({_quote(encoded)})",
                "",
            ]
        )

    def metadata_module(self) -> str:
        profile_inherits = {
            name: tuple(value.get("inherits", ()))
            for name, value in self.document["profiles"].items()
        }

        def inherits(profile: str, authority: str) -> bool:
            if profile == authority:
                return True
            return any(inherits(parent, authority) for parent in profile_inherits[profile])

        lines = [
            HEADER,
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass, field",
            "from typing import Mapping, Optional, Tuple",
            "",
            f"SCHEMA_VERSION = {self.ir.schema_version}",
            f"MUX_PROTOCOL = {self.ir.mux_protocol}",
            f"IR_SHA256 = {_quote(self.ir.ir_sha256)}",
            "",
            "",
            "@dataclass(frozen=True)",
            "class CommandFieldMetadata:",
            "    since: Optional[int]",
            "    capability: Optional[str]",
            "",
            "",
            "@dataclass(frozen=True)",
            "class CommandMetadata:",
            "    wire_name: str",
            "    authority: str",
            "    since: int",
            "    capability: Optional[str]",
            "    profiles: Tuple[str, ...]",
            "    stream_kind: Optional[str]",
            "    fields: Mapping[str, CommandFieldMetadata] = field(default_factory=dict)",
            "",
            "",
            "@dataclass(frozen=True)",
            "class EventMetadata:",
            "    wire_name: str",
            "    since: int",
            "    capability: Optional[str]",
            "    streams: Tuple[str, ...]",
            "    emission: str",
            "",
            "",
            "COMMANDS = {",
        ]
        for wire_name, command in self.document["commands"].items():
            authority = command["authority"]
            profiles = tuple(
                profile
                for profile in self.document["profiles"]
                if inherits(profile, authority)
            )
            stream = command.get("stream")
            stream_kind = stream.get("kind") if stream else None
            lines.extend(
                [
                    f"    {_quote(wire_name)}: CommandMetadata(",
                    f"        {_quote(wire_name)},",
                    f"        {_quote(authority)},",
                    f"        {command['since']},",
                    f"        {_quote(command.get('capability'))},",
                    f"        {_quote(profiles)},",
                    f"        {_quote(stream_kind)},",
                    "        {",
                ]
            )
            for field_name, field_spec in command["request"]["fields"].items():
                lines.append(
                    f"            {_quote(field_name)}: CommandFieldMetadata("
                    f"{_quote(field_spec.get('since'))}, "
                    f"{_quote(field_spec.get('capability'))}),"
                )
            lines.extend(["        },", "    ),"])
        lines.extend(["}", "", "EVENTS = {"])
        for wire_name, event in self.document["events"].items():
            lines.append(
                f"    {_quote(wire_name)}: EventMetadata("
                f"{_quote(wire_name)}, {event['since']}, "
                f"{_quote(event.get('capability'))}, {_quote(tuple(event['streams']))}, "
                f"{_quote(event['emission'])}),"
            )
        lines.extend(
            [
                "}",
                "",
                "__all__ = [",
                '    "SCHEMA_VERSION",',
                '    "MUX_PROTOCOL",',
                '    "IR_SHA256",',
                '    "CommandFieldMetadata",',
                '    "CommandMetadata",',
                '    "EventMetadata",',
                '    "COMMANDS",',
                '    "EVENTS",',
                "]",
                "",
            ]
        )
        return "\n".join(lines)

    def codec_module(self) -> str:
        model_paths = ",\n".join(
            f"    {_quote(path)}: models.{model.name}"
            for path, model in self.models.items()
        )
        enum_paths = ",\n".join(
            f"    {_quote(f'types/{name}')}: models.{name}"
            for name, expression in self.document["types"].items()
            if expression["kind"] == "enum"
        )
        python_names = {
            wire_name: _snake(wire_name)
            for model in self.models.values()
            for wire_name in model.expression["fields"]
            if _snake(wire_name) != wire_name
        }
        python_name_entries = ",\n".join(
            f"    {_quote(wire_name)}: {_quote(python_name)}"
            for wire_name, python_name in sorted(python_names.items())
        )
        return (
            HEADER
            + """from __future__ import annotations

import dataclasses
from enum import Enum
from typing import Any, Dict, Mapping

from . import models
from ._schema import SCHEMA


class ProtocolDecodeError(ValueError):
    pass


MODEL_BY_PATH = {
"""
            + model_paths
            + """
}

ENUM_BY_PATH = {
"""
            + enum_paths
            + """
}

PYTHON_FIELD_NAMES = {
"""
            + python_name_entries
            + """
}


def _at(path: str) -> Mapping[str, Any]:
    value: Any = SCHEMA
    for part in path.split("/"):
        value = value[int(part)] if isinstance(value, list) else value[part]
    return value


def _validate_scalar(name: str, value: Any) -> Any:
    if name == "string":
        if not isinstance(value, str):
            raise ProtocolDecodeError("expected string")
        return value
    if name == "boolean":
        if not isinstance(value, bool):
            raise ProtocolDecodeError("expected boolean")
        return value
    if name.startswith("float"):
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ProtocolDecodeError("expected number")
        return float(value)
    if isinstance(value, bool) or not isinstance(value, int):
        raise ProtocolDecodeError("expected integer")
    bounds = {
        "int32": (-(2**31), 2**31 - 1),
        "uint16": (0, 2**16 - 1),
        "uint32": (0, 2**32 - 1),
        "int64": (-(2**63), 2**63 - 1),
        "uint64": (0, 2**64 - 1),
    }
    low, high = bounds[name]
    if not low <= value <= high:
        raise ProtocolDecodeError(f"{name} value is out of range")
    return value


def _validate_constraints(value: Any, constraints: Any) -> None:
    for constraint in constraints or ():
        if not isinstance(constraint, Mapping):
            continue
        if "minimum" in constraint and value < constraint["minimum"]:
            raise ProtocolDecodeError(f"value is below minimum {constraint['minimum']}")
        if "maximum" in constraint and value > constraint["maximum"]:
            raise ProtocolDecodeError(f"value exceeds maximum {constraint['maximum']}")
        if "min_length" in constraint and len(value) < constraint["min_length"]:
            raise ProtocolDecodeError("value is too short")
        if "max_length" in constraint and len(value) > constraint["max_length"]:
            raise ProtocolDecodeError("value is too long")


def _decode_field(field: Mapping[str, Any], value: Any, path: str) -> Any:
    if value is None:
        if field["nullable"]:
            return None
        raise ProtocolDecodeError(f"{path} cannot be null")
    decoded = _decode(field["type"], value, path)
    _validate_constraints(decoded, field.get("constraints"))
    return decoded


def _decode(expression: Mapping[str, Any], value: Any, path: str) -> Any:
    kind = expression["kind"]
    if kind == "scalar":
        return _validate_scalar(expression["name"], value)
    if kind == "literal":
        if value != expression["value"]:
            raise ProtocolDecodeError(f"expected literal {expression['value']!r}")
        return value
    if kind == "enum":
        if value not in expression["values"]:
            raise ProtocolDecodeError(f"unknown enum value {value!r}")
        enum_type = ENUM_BY_PATH.get(path)
        return enum_type(value) if enum_type is not None else value
    if kind == "ref":
        return _decode(SCHEMA["types"][expression["name"]], value, f"types/{expression['name']}")
    if kind == "alias":
        return _decode(expression["target"], value, f"{path}/target")
    if kind == "array":
        if not isinstance(value, list):
            raise ProtocolDecodeError("expected array")
        result = [
            _decode(expression["items"], item, f"{path}/items")
            for item in value
        ]
        if "min_items" in expression and len(result) < expression["min_items"]:
            raise ProtocolDecodeError("array has too few items")
        if "max_items" in expression and len(result) > expression["max_items"]:
            raise ProtocolDecodeError("array has too many items")
        return result
    if kind == "map":
        if not isinstance(value, Mapping) or not all(isinstance(key, str) for key in value):
            raise ProtocolDecodeError("expected string-keyed object")
        return {
            key: _decode(expression["values"], item, f"{path}/values")
            for key, item in value.items()
        }
    if kind == "opaque_json":
        return value
    if kind == "tagged_union":
        if not isinstance(value, Mapping):
            raise ProtocolDecodeError("expected tagged object")
        variant = value.get(expression["tag"])
        if variant not in expression["variants"]:
            raise ProtocolDecodeError(f"unknown {expression['tag']} variant {variant!r}")
        return _decode(
            expression["variants"][variant],
            value,
            f"{path}/variants/{variant}",
        )
    if kind == "untagged_union":
        failures = []
        for index, variant in enumerate(expression["variants"]):
            try:
                return _decode(variant, value, f"{path}/variants/{index}")
            except (ProtocolDecodeError, TypeError, ValueError) as error:
                failures.append(str(error))
        raise ProtocolDecodeError("value did not match union: " + "; ".join(failures))
    if kind != "object":
        raise ProtocolDecodeError(f"unsupported schema kind {kind!r}")
    if not isinstance(value, Mapping):
        raise ProtocolDecodeError("expected object")
    kwargs: Dict[str, Any] = {}
    known = set()
    for wire_name, field in expression["fields"].items():
        candidates = (wire_name, *field.get("aliases", ()))
        present = next((candidate for candidate in candidates if candidate in value), None)
        known.update(candidate for candidate in candidates if candidate in value)
        if present is None:
            if field["presence"] == "required":
                raise ProtocolDecodeError(f"missing required field {wire_name!r}")
            continue
        python_name = PYTHON_FIELD_NAMES.get(wire_name, wire_name.replace("-", "_"))
        kwargs[python_name] = _decode_field(
            field, value[present], f"{path}/fields/{wire_name}/type"
        )
    extras = {key: item for key, item in value.items() if key not in known}
    if extras and not expression["additional_properties"]:
        raise ProtocolDecodeError(f"unexpected fields: {', '.join(sorted(extras))}")
    model = MODEL_BY_PATH.get(path)
    if model is None:
        result = dict(kwargs)
        result.update(extras)
        return result
    field_names = {item.name for item in dataclasses.fields(model)}
    if "extra" in field_names:
        kwargs["extra"] = extras
    if "raw" in field_names:
        kwargs["raw"] = dict(value)
    return model(**kwargs)


def _encode(expression: Mapping[str, Any], value: Any, path: str) -> Any:
    if value is models.MISSING:
        return models.MISSING
    kind = expression["kind"]
    if isinstance(value, Enum):
        value = value.value
    if kind == "ref":
        return _encode(SCHEMA["types"][expression["name"]], value, f"types/{expression['name']}")
    if kind == "alias":
        return _encode(expression["target"], value, f"{path}/target")
    if kind == "enum":
        if value not in expression["values"]:
            raise ProtocolDecodeError(f"unknown enum value {value!r}")
        return value
    if kind in {"scalar", "literal"}:
        return _decode(expression, value, path)
    if kind == "array":
        if not isinstance(value, (list, tuple)):
            raise ProtocolDecodeError("expected array")
        return [
            _encode(expression["items"], item, f"{path}/items")
            for item in value
        ]
    if kind == "map":
        if not isinstance(value, Mapping):
            raise ProtocolDecodeError("expected map")
        return {
            str(key): _encode(expression["values"], item, f"{path}/values")
            for key, item in value.items()
        }
    if kind == "opaque_json":
        return value
    if kind == "tagged_union":
        if dataclasses.is_dataclass(value):
            raw = _encode(_at(value.__cmux_schema_path__), value, value.__cmux_schema_path__)
        elif isinstance(value, Mapping):
            raw = dict(value)
        else:
            raise ProtocolDecodeError("expected tagged object")
        variant = raw.get(expression["tag"])
        if variant not in expression["variants"]:
            raise ProtocolDecodeError(f"unknown {expression['tag']} variant {variant!r}")
        return _encode(
            expression["variants"][variant], value, f"{path}/variants/{variant}"
        )
    if kind == "untagged_union":
        for index, variant in enumerate(expression["variants"]):
            try:
                return _encode(variant, value, f"{path}/variants/{index}")
            except (ProtocolDecodeError, TypeError, ValueError):
                pass
        raise ProtocolDecodeError("value did not match union")
    if kind != "object":
        raise ProtocolDecodeError(f"unsupported schema kind {kind!r}")
    if dataclasses.is_dataclass(value):
        raw: Dict[str, Any] = {}
        for item in dataclasses.fields(value):
            if item.metadata.get("cmux_skip"):
                continue
            item_value = getattr(value, item.name)
            if item.metadata.get("cmux_extra"):
                raw.update(item_value)
                continue
            if item_value is models.MISSING:
                continue
            wire_name = item.metadata.get("wire_name", item.name)
            field = expression["fields"][wire_name]
            if item_value is None:
                if not field["nullable"]:
                    raise ProtocolDecodeError(f"{wire_name} cannot be null")
                raw[wire_name] = None
            else:
                _validate_constraints(item_value, field.get("constraints"))
                raw[wire_name] = _encode(
                    field["type"], item_value, f"{path}/fields/{wire_name}/type"
                )
        value = raw
    if not isinstance(value, Mapping):
        raise ProtocolDecodeError("expected object")
    result: Dict[str, Any] = {}
    for wire_name, field in expression["fields"].items():
        if wire_name not in value:
            if field["presence"] == "required":
                raise ProtocolDecodeError(f"missing required field {wire_name!r}")
            continue
        item = value[wire_name]
        if item is models.MISSING:
            continue
        if item is None:
            if not field["nullable"]:
                raise ProtocolDecodeError(f"{wire_name} cannot be null")
            result[wire_name] = None
        else:
            _validate_constraints(item, field.get("constraints"))
            result[wire_name] = _encode(
                field["type"], item, f"{path}/fields/{wire_name}/type"
            )
    if expression["additional_properties"]:
        result.update({key: item for key, item in value.items() if key not in result})
    return result


def encode_request(command: str, request: Any) -> Dict[str, Any]:
    expression = SCHEMA["commands"][command]["request"]
    encoded = _encode(expression, request, f"commands/{command}/request")
    if not isinstance(encoded, dict):
        raise ProtocolDecodeError("command request must encode to an object")
    return encoded


def decode_command_result(command: str, value: Any) -> Any:
    expression = SCHEMA["commands"][command]["result"]
    return _decode(expression, value, f"commands/{command}/result")


def decode_event(value: Mapping[str, Any]) -> models.AnyEvent:
    event_name = value.get("event")
    if not isinstance(event_name, str):
        raise ProtocolDecodeError("event frame has no string event name")
    event = SCHEMA["events"].get(event_name)
    if event is None:
        return models.UnknownEvent(event=event_name, raw=dict(value))
    return _decode(event["payload"], value, f"events/{event_name}/payload")


__all__ = [
    "ProtocolDecodeError",
    "encode_request",
    "decode_command_result",
    "decode_event",
]
"""
        )

    def client_module(self) -> str:
        lines = [
            HEADER,
            "from __future__ import annotations",
            "",
            "import base64",
            "from typing import Any, Dict, List, Literal, Union",
            "",
            "from .metadata import COMMANDS",
            "from .models import *",
            "",
            "",
            "class GeneratedClientMixin:",
        ]
        for wire_name, command in self.document["commands"].items():
            method_name = _snake(wire_name)
            request = command["request"]
            fields = list(request["fields"].items())
            required = self.command_fields(
                wire_name,
                [item for item in fields if item[1]["presence"] == "required"]
            )
            optional = self.command_fields(
                wire_name,
                [item for item in fields if item[1]["presence"] == "optional"]
            )
            parameters = ["self"]
            for name, field_spec in required:
                annotation = self.annotation(
                    field_spec["type"], f"commands/{wire_name}/request/fields/{name}/type"
                )
                annotation = self.field_annotation(annotation, field_spec)
                if name == "bytes":
                    annotation = f"Union[{annotation}, bytes]"
                parameters.append(f"{_snake(name)}: {annotation}")
            positional_optional = []
            if (
                not required
                and optional
                and optional[0][0]
                in {"client", "fg", "index", "pane", "screen", "surface", "workspace"}
            ):
                positional_optional = [optional.pop(0)]
                name, field_spec = positional_optional[0]
                annotation = self.annotation(
                    field_spec["type"], f"commands/{wire_name}/request/fields/{name}/type"
                )
                annotation = self.field_annotation(annotation, field_spec)
                parameters.append(f"{_snake(name)}: {annotation} = MISSING")
            if optional:
                parameters.append("*")
            for name, field_spec in optional:
                annotation = self.annotation(
                    field_spec["type"], f"commands/{wire_name}/request/fields/{name}/type"
                )
                annotation = self.field_annotation(annotation, field_spec)
                if name == "bytes":
                    annotation = f"Union[{annotation}, bytes]"
                parameters.append(f"{_snake(name)}: {annotation} = MISSING")
            result = self.annotation(command["result"], f"commands/{wire_name}/result")
            if command.get("stream") is not None:
                result = "Any"
            lines.extend(
                [
                    "",
                    f"    def {method_name}({', '.join(parameters)}) -> {result}:",
                ]
            )
            request_name = self.models[f"commands/{wire_name}/request"].name
            arguments = []
            for name, _field in required + positional_optional + optional:
                python_name = _snake(name)
                value = python_name
                if name == "bytes":
                    value = (
                        "(base64.b64encode(bytes_data).decode('ascii') "
                        "if isinstance(bytes_data, bytes) else bytes_data)"
                    )
                arguments.append(f"{python_name}={value}")
            constructed = f"{request_name}({', '.join(arguments)})"
            if command.get("stream") is not None:
                lines.append(
                    f"        return self._open_command_stream({_quote(wire_name)}, {constructed})"
                )
            else:
                lines.append(
                    f"        return self._invoke_command({_quote(wire_name)}, {constructed})"
                )

        lines.extend(["", ""])
        for wire_name in self.document["commands"]:
            method_name = _snake(wire_name)
            lines.append(
                f"GeneratedClientMixin.{method_name}.__cmux_command__ = COMMANDS[{_quote(wire_name)}]"
            )
        lines.extend(["", '__all__ = ["GeneratedClientMixin"]', ""])
        return "\n".join(lines)

    def init_module(self) -> str:
        return (
            HEADER
            + """from .client import *
from .codec import *
from .metadata import *
from .models import *

from .client import __all__ as _client_all
from .codec import __all__ as _codec_all
from .metadata import __all__ as _metadata_all
from .models import __all__ as _models_all

__all__ = list(dict.fromkeys((*_client_all, *_codec_all, *_metadata_all, *_models_all)))
"""
        )

    def render(self) -> Mapping[PurePosixPath, str]:
        return {
            PurePosixPath("__init__.py"): self.init_module(),
            PurePosixPath("_schema.py"): self.schema_module(),
            PurePosixPath("client.py"): self.client_module(),
            PurePosixPath("codec.py"): self.codec_module(),
            PurePosixPath("metadata.py"): self.metadata_module(),
            PurePosixPath("models.py"): self.models_module(),
        }


def emit(value: SdkIR) -> Mapping[PurePosixPath, str]:
    return PythonEmitter(value).render()


EMITTER = Emitter(
    language="python",
    output_root=PurePosixPath("python/cmux/raw/_generated"),
    render=emit,
)
