from __future__ import annotations

import json
import re
from collections.abc import Mapping
from pathlib import PurePosixPath
from typing import Any

from codegen.ir import SdkIR, mutable_document
from codegen.writer import Emitter


HEADER = """// Generated by cmux-tui/bindings/codegen. DO NOT EDIT.
// Source: cmux-tui/spec/sdk-schema.json
"""

ZIG_KEYWORDS = {
    "addrspace",
    "align",
    "allowzero",
    "and",
    "anyframe",
    "anytype",
    "asm",
    "async",
    "await",
    "break",
    "callconv",
    "catch",
    "comptime",
    "const",
    "continue",
    "defer",
    "else",
    "enum",
    "errdefer",
    "error",
    "export",
    "extern",
    "fn",
    "for",
    "if",
    "inline",
    "linksection",
    "noalias",
    "noinline",
    "nosuspend",
    "opaque",
    "or",
    "orelse",
    "packed",
    "pub",
    "resume",
    "return",
    "struct",
    "suspend",
    "switch",
    "test",
    "threadlocal",
    "try",
    "union",
    "unreachable",
    "usingnamespace",
    "var",
    "volatile",
    "while",
}

SCALARS = {
    "string": "[]const u8",
    "boolean": "bool",
    "int32": "i32",
    "uint16": "u16",
    "uint32": "u32",
    "int64": "i64",
    "uint64": "u64",
    "float32": "f32",
    "float64": "f64",
}


def _pascal(value: str) -> str:
    return "".join(
        part[:1].upper() + part[1:]
        for part in re.split(r"[^A-Za-z0-9]+", value)
        if part
    )


def _camel(value: str) -> str:
    pascal = _pascal(value)
    return pascal[:1].lower() + pascal[1:]


def _snake(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", value)
    value = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", value).lower()
    if value[:1].isdigit():
        value = "_" + value
    return value


def _identifier(value: str) -> str:
    candidate = _snake(value)
    if candidate in ZIG_KEYWORDS:
        return f'@"{candidate}"'
    return candidate


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


class ZigEmitter:
    def __init__(self, ir: SdkIR):
        self.ir = ir
        self.document = mutable_document(ir)
        self.named = set(self.document["types"])
        self.optional_nonnull_cases: list[tuple[str, str]] = []

    def type_expr(
        self,
        expression: Mapping[str, Any],
        *,
        nested: bool = False,
        inline_name: str | None = None,
        recursive_name: str | None = None,
    ) -> str:
        kind = expression["kind"]
        if kind == "scalar":
            return SCALARS[expression["name"]]
        if kind == "literal":
            value = expression["value"]
            if isinstance(value, str):
                return "[]const u8"
            if isinstance(value, bool):
                return "bool"
            if isinstance(value, int):
                return "i64"
            return "wire.Value"
        if kind == "enum":
            return inline_name or "[]const u8"
        if kind == "object":
            return "wire.Value" if nested else "struct {}"
        if kind == "alias":
            return self.type_expr(expression["target"], nested=nested)
        if kind in {"tagged_union", "untagged_union", "opaque_json"}:
            return "wire.Value"
        if kind == "map":
            return f"wire.Map({self.type_expr(expression['values'], nested=True)})"
        if kind == "array":
            return (
                "[]const "
                + self.type_expr(
                    expression["items"],
                    nested=True,
                    recursive_name=recursive_name,
                )
            )
        if kind == "ref":
            if expression["name"] == recursive_name:
                return f"*const {recursive_name}"
            return expression["name"]
        raise ValueError(f"unsupported Zig IR type kind: {kind}")

    def field_type(
        self,
        field: Mapping[str, Any],
        *,
        owner_name: str,
        wire_name: str,
        recursive_name: str | None,
    ) -> tuple[str, str]:
        inline_name = (
            owner_name + _pascal(wire_name)
            if field["type"]["kind"] == "enum"
            else None
        )
        base = self.type_expr(
            field["type"],
            nested=True,
            inline_name=inline_name,
            recursive_name=recursive_name,
        )
        presence = field["presence"]
        nullable = field["nullable"]
        if presence == "optional" and nullable:
            return f"wire.Field({base})", " = .absent"
        if presence == "optional":
            return f"?{base}", " = null"
        if nullable:
            return f"wire.Nullable({base})", ""
        return base, ""

    def render_enum(self, name: str, expression: Mapping[str, Any]) -> list[str]:
        values = expression["values"]
        lines = [f"pub const {name} = enum {{"]
        for value in values:
            lines.append(f"    {_identifier(str(value))},")
        lines.extend(
            [
                "",
                "    pub fn fromWire(value: []const u8) !@This() {",
            ]
        )
        for value in values:
            lines.append(
                f"        if (std.mem.eql(u8, value, {_quote(str(value))})) "
                f"return .{_identifier(str(value))};"
            )
        lines.extend(
            [
                "        return error.UnknownEnumValue;",
                "    }",
                "",
                "    pub fn toWire(self: @This()) []const u8 {",
                "        return switch (self) {",
            ]
        )
        for value in values:
            lines.append(
                f"            .{_identifier(str(value))} => {_quote(str(value))},"
            )
        lines.extend(["        };", "    }", "};", ""])
        return lines

    def render_struct(
        self,
        name: str,
        expression: Mapping[str, Any],
        description: str | None = None,
        *,
        skip_fields: frozenset[str] = frozenset(),
        recursive_name: str | None = None,
    ) -> list[str]:
        lines: list[str] = []
        if description:
            lines.append(f"/// {' '.join(description.split())}")
        for wire_name, field in expression["fields"].items():
            if wire_name in skip_fields:
                continue
            if field["type"]["kind"] == "enum":
                lines.extend(
                    self.render_enum(
                        name + _pascal(wire_name),
                        field["type"],
                    )
                )
        rendered_fields = [
            item
            for item in expression["fields"].items()
            if item[0] not in skip_fields
        ]
        if not rendered_fields:
            lines.append(f"pub const {name} = struct {{}};")
            lines.append("")
            return lines
        lines.append(f"pub const {name} = struct {{")
        for wire_name, field in rendered_fields:
            if field.get("description"):
                lines.append(f"    /// {' '.join(field['description'].split())}")
            rendered, default = self.field_type(
                field,
                owner_name=name,
                wire_name=wire_name,
                recursive_name=recursive_name,
            )
            lines.append(f"    {_identifier(wire_name)}: {rendered}{default},")
        optional_nonnull_fields = [
            wire_name
            for wire_name, field in rendered_fields
            if field["presence"] == "optional" and not field["nullable"]
        ]
        if optional_nonnull_fields:
            self.optional_nonnull_cases.extend(
                (name, wire_name) for wire_name in optional_nonnull_fields
            )
            lines.extend(
                [
                    "",
                    "    pub const cmux_wire_optional_nonnull_fields = "
                    "[_][]const u8{",
                ]
            )
            for wire_name in optional_nonnull_fields:
                lines.append(f"        {_quote(wire_name)},")
            lines.append("    };")
        lines.extend(["};", ""])
        return lines

    def render_tagged_union(
        self,
        name: str,
        expression: Mapping[str, Any],
    ) -> list[str]:
        tag = expression["tag"]
        lines: list[str] = []
        variants: list[tuple[str, str]] = []
        for wire_value, variant in expression["variants"].items():
            variant_name = name + _pascal(str(wire_value))
            lines.extend(
                self.render_struct(
                    variant_name,
                    variant,
                    skip_fields=frozenset({tag}),
                    recursive_name=name,
                )
            )
            variants.append((str(wire_value), variant_name))

        lines.append(f"pub const {name} = union(enum) {{")
        for wire_value, variant_name in variants:
            lines.append(f"    {_identifier(wire_value)}: {variant_name},")
        lines.extend(
            [
                "",
                "    pub const cmux_wire_custom_union = true;",
                "",
                "    pub fn cmuxEncode(self: @This(), allocator: "
                "std.mem.Allocator) !wire.Value {",
                "        return switch (self) {",
            ]
        )
        for wire_value, _variant_name in variants:
            lines.append(
                f"            .{_identifier(wire_value)} => |payload| "
                f"try wire.encodeTagged(allocator, {_quote(tag)}, "
                f"{_quote(wire_value)}, payload),"
            )
        lines.extend(
            [
                "        };",
                "    }",
                "",
                "    pub fn cmuxDecode(allocator: std.mem.Allocator, "
                "value: wire.Value) !@This() {",
                f"        const tag_value = try wire.objectString(value, {_quote(tag)});",
            ]
        )
        for wire_value, variant_name in variants:
            lines.extend(
                [
                    f"        if (std.mem.eql(u8, tag_value, {_quote(wire_value)})) {{",
                    f"            return .{{ .{_identifier(wire_value)} = "
                    f"try wire.decodeLeaky({variant_name}, allocator, value) }};",
                    "        }",
                ]
            )
        lines.extend(
            [
                "        return error.UnknownUnionVariant;",
                "    }",
                "};",
                "",
            ]
        )
        return lines

    def render_untagged_union(
        self,
        name: str,
        expression: Mapping[str, Any],
    ) -> list[str]:
        variants: list[tuple[str, str]] = []
        for index, variant in enumerate(expression["variants"]):
            if variant["kind"] != "ref":
                variant_type = "wire.Value"
                variant_name = f"variant_{index + 1}"
            else:
                variant_type = variant["name"]
                base = variant_type
                if base.endswith(name):
                    base = base[: -len(name)]
                variant_name = _snake(base) or f"variant_{index + 1}"
            variants.append((variant_name, variant_type))
        lines = [f"pub const {name} = union(enum) {{"]
        for variant_name, variant_type in variants:
            lines.append(f"    {_identifier(variant_name)}: {variant_type},")
        lines.extend(
            [
                "",
                "    pub const cmux_wire_custom_union = true;",
                "",
                "    pub fn cmuxEncode(self: @This(), allocator: "
                "std.mem.Allocator) !wire.Value {",
                "        return switch (self) {",
            ]
        )
        for variant_name, _variant_type in variants:
            lines.append(
                f"            .{_identifier(variant_name)} => |payload| "
                "try wire.encodeValue(allocator, payload),"
            )
        lines.extend(
            [
                "        };",
                "    }",
                "",
                "    pub fn cmuxDecode(allocator: std.mem.Allocator, "
                "value: wire.Value) !@This() {",
            ]
        )
        # Pane is the only untagged union in the current protocol. Its `dead` literal
        # is the stable discriminator and avoids speculative allocations.
        if name == "Pane":
            lines.extend(
                [
                    '        if (wire.objectHas(value, "dead")) {',
                    "            return .{ .dead = try wire.decodeLeaky("
                    "DeadPane, allocator, value) };",
                    "        }",
                    "        return .{ .live = try wire.decodeLeaky("
                    "LivePane, allocator, value) };",
                ]
            )
        else:
            lines.append("        _ = allocator;")
            lines.append("        _ = value;")
            lines.append("        return error.AmbiguousUnion;")
        lines.extend(["    }", "};", ""])
        return lines

    def render_named_types(self) -> list[str]:
        lines: list[str] = []
        for name, expression in self.document["types"].items():
            kind = expression["kind"]
            if kind == "enum":
                lines.extend(self.render_enum(name, expression))
            elif kind == "object":
                lines.extend(
                    self.render_struct(
                        name,
                        expression,
                        expression.get("description"),
                    )
                )
            elif kind == "alias":
                lines.append(
                    f"pub const {name} = {self.type_expr(expression['target'], nested=True)};"
                )
                lines.append("")
            elif kind == "tagged_union":
                lines.extend(self.render_tagged_union(name, expression))
            elif kind == "untagged_union":
                lines.extend(self.render_untagged_union(name, expression))
            elif kind == "opaque_json":
                reason = expression.get("reason")
                if reason:
                    lines.append(f"/// {' '.join(reason.split())}")
                lines.append(f"pub const {name} = wire.Value;")
                lines.append("")
            else:
                raise ValueError(f"unsupported named Zig type {name}: {kind}")
        return lines

    def render_commands(self) -> tuple[list[str], list[dict[str, Any]]]:
        lines: list[str] = []
        descriptors: list[dict[str, Any]] = []
        for wire_name, command in self.document["commands"].items():
            stem = _pascal(wire_name)
            request_name = f"{stem}Request"
            result_name = f"{stem}Result"
            request = command["request"]
            if request["kind"] == "object":
                lines.extend(self.render_struct(request_name, request))
            else:
                lines.append(
                    f"pub const {request_name} = {self.type_expr(request, nested=True)};"
                )
                lines.append("")
            result = command["result"]
            if result["kind"] == "object":
                if result_name not in self.named:
                    lines.extend(self.render_struct(result_name, result))
            else:
                target = self.type_expr(result, nested=True)
                if result_name != target:
                    lines.append(f"pub const {result_name} = {target};")
                    lines.append("")

            function = _camel(wire_name)
            stream = command["stream"]
            if stream is None:
                lines.append(
                    f"pub fn {function}(client: anytype, request: {request_name}) "
                    f"!wire.Decoded({result_name}) {{"
                )
                lines.extend(
                    [
                        "    return client.callTyped(",
                        f"        {result_name},",
                    ]
                )
                lines.extend(
                    self.render_command_requirements(
                        wire_name,
                        command,
                        indent="        ",
                    )
                )
                lines.extend(["        request,", "    );", "}", ""])
            else:
                terminal_event = stream.get("terminal_event")
                terminal = (
                    "null"
                    if terminal_event is None
                    else _quote(str(terminal_event))
                )
                lines.append(
                    f"pub fn {function}(client: anytype, request: {request_name}) "
                    "!client_runtime.Stream {"
                )
                lines.append("    return client.openStream(")
                lines.extend(
                    self.render_command_requirements(
                        wire_name,
                        command,
                        indent="        ",
                    )
                )
                lines.extend(
                    [
                        "        request,",
                        f"        {terminal},",
                        "    );",
                        "}",
                        "",
                    ]
                )
            descriptors.append(
                {
                    "name": wire_name,
                    "authority": command["authority"],
                    "since": command["since"],
                    "capability": command["capability"],
                    "stream": None if stream is None else stream["kind"],
                }
            )
        return lines, descriptors

    @staticmethod
    def render_command_requirements(
        wire_name: str,
        command: Mapping[str, Any],
        *,
        indent: str,
    ) -> list[str]:
        capability = (
            "null"
            if command["capability"] is None
            else _quote(str(command["capability"]))
        )
        lines = [
            f"{indent}.{{",
            f"{indent}    .name = {_quote(wire_name)},",
            f"{indent}    .authority = {_quote(command['authority'])},",
            f"{indent}    .since = {command['since']},",
            f"{indent}    .capability = {capability},",
        ]
        request = command["request"]
        fields = (
            request["fields"].items()
            if request["kind"] == "object"
            else ()
        )
        gated_fields = [
            (field_name, field)
            for field_name, field in fields
            if field.get("since") is not None
            or field.get("capability") is not None
        ]
        if gated_fields:
            lines.append(f"{indent}    .fields = &.{{")
            for field_name, field in gated_fields:
                since = (
                    "null"
                    if field.get("since") is None
                    else str(field["since"])
                )
                field_capability = (
                    "null"
                    if field.get("capability") is None
                    else _quote(str(field["capability"]))
                )
                lines.append(
                    f"{indent}        .{{ "
                    f".name = {_quote(_snake(field_name))}, "
                    f".since = {since}, "
                    f".capability = {field_capability} "
                    "},"
                )
            lines.append(f"{indent}    }},")
        lines.append(f"{indent}}},")
        return lines

    def render_events(self) -> tuple[list[str], list[dict[str, Any]]]:
        lines: list[str] = []
        descriptors: list[dict[str, Any]] = []
        event_types: list[tuple[str, str]] = []
        for wire_name, event in self.document["events"].items():
            payload_name = f"{_pascal(wire_name)}Event"
            payload = event["payload"]
            if payload["kind"] == "object":
                lines.extend(self.render_struct(payload_name, payload))
            else:
                lines.append(
                    f"pub const {payload_name} = {self.type_expr(payload, nested=True)};"
                )
                lines.append("")
            event_types.append((wire_name, payload_name))
            descriptors.append(
                {
                    "name": wire_name,
                    "since": event["since"],
                    "capability": event["capability"],
                    "streams": event["streams"],
                }
            )

        lines.extend(
            [
                "pub const UnknownEvent = struct {",
                "    name: []const u8,",
                "    raw: wire.Value,",
                "};",
                "",
                "pub const Event = union(enum) {",
            ]
        )
        for wire_name, payload_name in event_types:
            lines.append(f"    {_identifier(wire_name)}: {payload_name},")
        lines.extend(["    unknown: UnknownEvent,", "};", ""])

        lines.extend(
            [
                "pub fn eventWireName(event: Event) []const u8 {",
                "    return switch (event) {",
            ]
        )
        for wire_name, _ in event_types:
            lines.append(
                f"        .{_identifier(wire_name)} => {_quote(wire_name)},"
            )
        lines.extend(
            [
                "        .unknown => |unknown| unknown.name,",
                "    };",
                "}",
                "",
            ]
        )

        lines.extend(
            [
                "pub const DecodedEvent = struct {",
                "    arena: std.heap.ArenaAllocator,",
                "    value: Event,",
                "",
                "    pub fn deinit(self: *DecodedEvent) void {",
                "        self.arena.deinit();",
                "        self.* = undefined;",
                "    }",
                "};",
                "",
                "pub fn decodeEvent(allocator: std.mem.Allocator, value: wire.Value) "
                "!DecodedEvent {",
                "    const name = try wire.eventName(value);",
                "    var arena = std.heap.ArenaAllocator.init(allocator);",
                "    errdefer arena.deinit();",
            ]
        )
        for wire_name, payload_name in event_types:
            lines.extend(
                [
                    f"    if (std.mem.eql(u8, name, {_quote(wire_name)})) {{",
                    f"        const decoded = try wire.decodeLeaky("
                    f"{payload_name}, arena.allocator(), value);",
                    f"        return .{{ .arena = arena, .value = "
                    f".{{ .{_identifier(wire_name)} = decoded }} }};",
                    "    }",
                ]
            )
        lines.extend(
            [
                "    const owned_name = try arena.allocator().dupe(u8, name);",
                "    const raw = try wire.cloneValue(arena.allocator(), value);",
                "    return .{",
                "        .arena = arena,",
                "        .value = .{ .unknown = .{",
                "            .name = owned_name,",
                "            .raw = raw,",
                "        } },",
                "    };",
                "}",
                "",
                "pub fn nextEvent(stream: *client_runtime.Stream, allocator: "
                "std.mem.Allocator) !?DecodedEvent {",
                "    var raw = (try stream.next()) orelse return null;",
                "    defer raw.deinit();",
                "    return try decodeEvent(allocator, raw.value);",
                "}",
                "",
            ]
        )
        return lines, descriptors

    @staticmethod
    def render_command_metadata(descriptors: list[dict[str, Any]]) -> list[str]:
        lines = [
            "pub const CommandDescriptor = struct {",
            "    name: []const u8,",
            "    authority: []const u8,",
            "    since: u16,",
            "    capability: ?[]const u8,",
            "    stream: ?[]const u8,",
            "};",
            "",
            f"pub const command_count: usize = {len(descriptors)};",
            "pub const commands = [_]CommandDescriptor{",
        ]
        for item in descriptors:
            capability = (
                "null"
                if item["capability"] is None
                else _quote(str(item["capability"]))
            )
            stream = (
                "null" if item["stream"] is None else _quote(str(item["stream"]))
            )
            lines.append(
                "    .{ "
                f".name = {_quote(item['name'])}, "
                f".authority = {_quote(item['authority'])}, "
                f".since = {item['since']}, "
                f".capability = {capability}, "
                f".stream = {stream} "
                "},"
            )
        lines.extend(["};", ""])
        return lines

    @staticmethod
    def render_event_metadata(descriptors: list[dict[str, Any]]) -> list[str]:
        lines = [
            "pub const EventDescriptor = struct {",
            "    name: []const u8,",
            "    since: u16,",
            "    capability: ?[]const u8,",
            "    streams: []const []const u8,",
            "};",
            "",
        ]
        for index, item in enumerate(descriptors):
            values = ", ".join(_quote(stream) for stream in item["streams"])
            if len(item["streams"]) == 1:
                lines.append(
                    f"const event_streams_{index} = [_][]const u8{{{values}}};"
                )
            else:
                lines.append(
                    f"const event_streams_{index} = [_][]const u8{{ {values} }};"
                )
        lines.extend(
            [
                "",
                f"pub const event_count: usize = {len(descriptors)};",
                "pub const events = [_]EventDescriptor{",
            ]
        )
        for index, item in enumerate(descriptors):
            capability = (
                "null"
                if item["capability"] is None
                else _quote(str(item["capability"]))
            )
            lines.append(
                "    .{ "
                f".name = {_quote(item['name'])}, "
                f".since = {item['since']}, "
                f".capability = {capability}, "
                f".streams = &event_streams_{index} "
                "},"
            )
        lines.extend(["};", ""])
        return lines

    def render(self) -> str:
        self.optional_nonnull_cases.clear()
        command_lines, command_descriptors = self.render_commands()
        event_lines, event_descriptors = self.render_events()
        lines = [
            HEADER,
            'const std = @import("std");',
            'const wire = @import("../wire.zig");',
            'const client_runtime = @import("../client.zig");',
            "",
            f"pub const schema_version: u16 = {self.ir.schema_version};",
            f"pub const mux_protocol: u16 = {self.ir.mux_protocol};",
            f'pub const ir_sha256 = "{self.ir.ir_sha256}";',
            "",
        ]
        lines.extend(self.render_named_types())
        lines.extend(command_lines)
        lines.extend(event_lines)
        lines.extend(self.render_command_metadata(command_descriptors))
        lines.extend(self.render_event_metadata(event_descriptors))
        return "\n".join(lines).rstrip() + "\n"

    def render_presence_test(self) -> str:
        lines = [
            HEADER,
            'const std = @import("std");',
            'const wire = @import("../wire.zig");',
            'const protocol = @import("protocol.zig");',
            "",
            "fn expectExplicitNullRejected(",
            "    comptime T: type,",
            "    field_name: []const u8,",
            ") !void {",
            "    var object = wire.Object.init(std.testing.allocator);",
            "    defer object.deinit();",
            "    try object.put(field_name, .null);",
            "    try std.testing.expectError(",
            "        error.UnexpectedNull,",
            "        wire.decode(T, std.testing.allocator, .{ .object = object }),",
            "    );",
            "}",
            "",
            'test "every generated optional non-null field rejects explicit null" {',
        ]
        for owner_name, wire_name in self.optional_nonnull_cases:
            lines.append(
                "    try expectExplicitNullRejected("
                f"protocol.{owner_name}, {_quote(wire_name)});"
            )
        lines.extend(["}", ""])
        return "\n".join(lines)


def render(ir: SdkIR) -> Mapping[str | PurePosixPath, str | bytes]:
    emitter = ZigEmitter(ir)
    protocol = emitter.render()
    return {
        "presence_test.zig": emitter.render_presence_test(),
        "protocol.zig": protocol,
    }


EMITTER = Emitter(
    language="zig",
    output_root=PurePosixPath("zig/src/raw/generated"),
    render=render,
)
