#!/usr/bin/env python3
"""Generate the embedded cmux.json schema used by the native CLI validator."""

from __future__ import annotations

import argparse
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "web" / "data" / "cmux.schema.json"
OUTPUT = (
    ROOT
    / "Packages"
    / "macOS"
    / "CmuxFoundation"
    / "Sources"
    / "CmuxFoundation"
    / "ConfigValidation"
    / "CmuxConfigSchema.generated.swift"
)


def generated_source() -> str:
    encoded = base64.b64encode(SCHEMA.read_bytes()).decode("ascii")
    chunks = [encoded[i : i + 400] for i in range(0, len(encoded), 400)]
    body = "\n".join(f'        "{chunk}",' for chunk in chunks)
    return f"""// Generated by scripts/generate-cmux-config-schema.py. Do not edit.
// Source: web/data/cmux.schema.json

import Foundation

enum CmuxEmbeddedConfigSchema {{
    static let data: Data = {{
        let base64 = [
{body}
        ].joined()
        guard let data = Data(base64Encoded: base64) else {{
            preconditionFailure("embedded cmux.json schema is corrupt")
        }}
        return data
    }}()
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated_source()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
