#!/usr/bin/env python3
"""Generate compile-time Claude launch environment policy for every consumer."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parent.parent
MANIFEST_PATH = SCRIPT_PATH.with_name("claude-launch-environment-policy.json")
SWIFT_PATH = REPO_ROOT / "Packages/macOS/CMUXAgentLaunch/Sources/CMUXAgentLaunch/ClaudeSessionEnvironmentPolicy+Generated.swift"
TYPESCRIPT_PATH = REPO_ROOT / "agent-chat/adapters/claude-environment-policy.generated.ts"
WRAPPER_PATH = REPO_ROOT / "Resources/bin/cmux-claude-wrapper"
WRAPPER_BEGIN = "    # BEGIN GENERATED CLAUDE LAUNCH ENVIRONMENT POLICY"
WRAPPER_END = "    # END GENERATED CLAUDE LAUNCH ENVIRONMENT POLICY"
ENVIRONMENT_KEY_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")


def load_manifest() -> Dict[str, List[str]]:
    raw = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    expected_fields = {"inheritedSessionIdentityKeys", "inheritedTrustBypassKeys"}
    if set(raw) != expected_fields:
        raise ValueError(
            f"{MANIFEST_PATH.relative_to(REPO_ROOT)} must contain exactly "
            f"{', '.join(sorted(expected_fields))}"
        )

    manifest: Dict[str, List[str]] = {}
    all_keys: List[str] = []
    for field in ("inheritedSessionIdentityKeys", "inheritedTrustBypassKeys"):
        value = raw[field]
        if not isinstance(value, list) or not value or not all(isinstance(key, str) for key in value):
            raise ValueError(f"{field} must be a non-empty array of strings")
        invalid_keys = [key for key in value if not ENVIRONMENT_KEY_PATTERN.fullmatch(key)]
        if invalid_keys:
            raise ValueError(f"{field} contains invalid environment keys: {', '.join(invalid_keys)}")
        manifest[field] = value
        all_keys.extend(value)

    duplicate_keys = sorted({key for key in all_keys if all_keys.count(key) > 1})
    if duplicate_keys:
        raise ValueError(f"manifest contains duplicate environment keys: {', '.join(duplicate_keys)}")
    return manifest


def swift_array(keys: List[str], indentation: str) -> str:
    return "\n".join(f'{indentation}"{key}",' for key in keys)


def render_swift(manifest: Dict[str, List[str]]) -> str:
    identity_keys = swift_array(manifest["inheritedSessionIdentityKeys"], "            ")
    trust_keys = swift_array(manifest["inheritedTrustBypassKeys"], "            ")
    return f'''// Generated by scripts/generate-claude-launch-environment-policy.py.
// Source: scripts/claude-launch-environment-policy.json. Do not edit by hand.

extension ClaudeSessionEnvironmentPolicy {{
    /// Creates the canonical Claude session-environment policy.
    public init() {{
        inheritedSessionIdentityKeys = [
{identity_keys}
        ]
        inheritedTrustBypassKeys = [
{trust_keys}
        ]
    }}
}}
'''


def render_typescript(manifest: Dict[str, List[str]]) -> str:
    keys = manifest["inheritedSessionIdentityKeys"] + manifest["inheritedTrustBypassKeys"]
    rendered_keys = "\n".join(f'  "{key}",' for key in keys)
    return f'''// Generated by scripts/generate-claude-launch-environment-policy.py.
// Source: scripts/claude-launch-environment-policy.json. Do not edit by hand.

export const inheritedClaudeLaunchStateKeys = [
{rendered_keys}
] as const;
'''


def render_wrapper(wrapper: str, manifest: Dict[str, List[str]]) -> str:
    # The wrapper continues an authorized cmux launch, so only detach it from
    # the inherited conversation; independent launchers also clear trust state.
    keys = manifest["inheritedSessionIdentityKeys"]
    generated_block = "\n".join(
        [WRAPPER_BEGIN, *(f"    unset {key}" for key in keys), WRAPPER_END]
    )
    pattern = re.compile(
        rf"{re.escape(WRAPPER_BEGIN)}\n.*?\n{re.escape(WRAPPER_END)}",
        flags=re.DOTALL,
    )
    updated, replacement_count = pattern.subn(generated_block, wrapper)
    if replacement_count != 1:
        raise ValueError(
            f"{WRAPPER_PATH.relative_to(REPO_ROOT)} must contain exactly one generated policy block"
        )
    return updated


def generated_outputs(manifest: Dict[str, List[str]]) -> Dict[Path, str]:
    wrapper = WRAPPER_PATH.read_text(encoding="utf-8")
    return {
        SWIFT_PATH: render_swift(manifest),
        TYPESCRIPT_PATH: render_typescript(manifest),
        WRAPPER_PATH: render_wrapper(wrapper, manifest),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if a generated consumer is stale")
    mode.add_argument("--write", action="store_true", help="update every generated consumer")
    args = parser.parse_args()

    try:
        outputs = generated_outputs(load_manifest())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.write:
        for path, expected in outputs.items():
            path.write_text(expected, encoding="utf-8")
            print(f"updated {path.relative_to(REPO_ROOT)}")
        return 0

    stale_paths = [
        path for path, expected in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != expected
    ]
    if stale_paths:
        for path in stale_paths:
            print(f"stale generated Claude launch policy: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
        print(
            "run scripts/generate-claude-launch-environment-policy.py --write",
            file=sys.stderr,
        )
        return 1

    print("Claude launch environment policy consumers are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
