#!/usr/bin/env python3
"""Generate the embedded cmux.json schema used by the native CLI validator."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = Path("web") / "data" / "cmux.schema.json"
OUTPUT_PATH = (
    Path("Packages")
    / "macOS"
    / "CmuxFoundation"
    / "Sources"
    / "CmuxFoundation"
    / "ConfigValidation"
    / "CmuxConfigSchema.generated.swift"
)
SCHEMA = ROOT / SCHEMA_PATH
OUTPUT = ROOT / OUTPUT_PATH


def raw_string_delimiter(text: str) -> str:
    # Return the shortest `#` run that makes `text` safe in a Swift raw
    # string. Only the closing quotes plus that run end the literal, and only
    # a backslash plus that run starts an escape, so the run is safe when
    # neither a quote nor a backslash is ever followed by it. Checking one
    # quote instead of three is stricter than needed and keeps the rule simple.
    hashes = "#"
    while f'"{hashes}' in text or f"\\{hashes}" in text:
        hashes += "#"
    return hashes


def generated_source(schema: Path = SCHEMA) -> str:
    raw = schema.read_bytes()
    text = raw.decode("utf-8")
    # A multi-line literal normalizes CR and CRLF to LF, and Swift rejects
    # most raw control characters, so either would change the embedded bytes
    # or break the build. JSON needs neither outside escapes.
    bad = sorted({hex(ord(c)) for c in text if (ord(c) < 0x20 and c not in "\n\t") or ord(c) == 0x7F})
    if bad:
        raise SystemExit(f"{SCHEMA_PATH} has control characters {bad}; cannot embed as a Swift literal")
    delimiter = raw_string_delimiter(text)
    assert f'"{delimiter}' not in text and f"\\{delimiter}" not in text
    # The literal drops the line break just before its closing delimiter, so
    # one extra newline keeps the source's final newline (or its absence).
    # Lines stay line for line with the JSON, so git merges this file the way
    # it merges the schema: settings added in different places do not conflict.
    return f"""// Generated by scripts/generate-cmux-config-schema.py. Do not edit.
// Source: web/data/cmux.schema.json

import Foundation

enum CmuxEmbeddedConfigSchema {{
    static let data = Data(json.utf8)

    // Line for line with the source so independent schema edits merge cleanly.
    static let json = {delimiter}\"\"\"
{text}
\"\"\"{delimiter}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    # Read the schema from, and write the Swift into, another checkout. PR
# The trusted merge-main resolver runs this copy against a branch's tree, so
# the generator never comes from an untrusted tree.
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    root = args.root.resolve()
    output = root / OUTPUT_PATH
    expected = generated_source(root / SCHEMA_PATH)
    if args.check:
        if not output.exists() or output.read_text() != expected:
            print(f"{OUTPUT_PATH} is stale; run {Path(__file__).name}")
            return 1
        return 0
    output.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
