//! Cute verification code ("word-word-NN") derived from the relay's ephemeral
//! X25519 public key. The terminal derives it locally; the backend derives the
//! same string from the pubkey it received at /v2/pairing/start and shows it
//! on the approval page, so a user who visually matches the two strings has
//! verified the page is approving THIS terminal's key, not an impostor's.
//!
//! KEEP IN SYNC with chatmux `apps/backend/src/pairing-crypto.ts` and
//! `packages/relay/bin/fingerprint.mjs` (word table extracted mechanically
//! from the JS module; the unit tests below pin cross-implementation
//! vectors produced by the JS `deriveCuteCode`).

use sha2::{Digest, Sha256};

/// Exactly 256 short, visually distinct, easy-to-say words.
pub const CUTE_WORDS: [&str; 256] = [
    "acorn",
    "amber",
    "anchor",
    "apple",
    "apricot",
    "aspen",
    "atlas",
    "aurora",
    "autumn",
    "avocado",
    "badger",
    "bagel",
    "bamboo",
    "banjo",
    "basil",
    "beacon",
    "berry",
    "birch",
    "bison",
    "blaze",
    "bloom",
    "blossom",
    "bluff",
    "bobcat",
    "bonsai",
    "breeze",
    "brick",
    "brook",
    "bubble",
    "bucket",
    "burrow",
    "butter",
    "cabin",
    "cactus",
    "camel",
    "candle",
    "canoe",
    "canyon",
    "caramel",
    "carrot",
    "cedar",
    "cello",
    "cherry",
    "chess",
    "chime",
    "cider",
    "cinnamon",
    "citrus",
    "cliff",
    "clover",
    "cobalt",
    "cocoa",
    "comet",
    "compass",
    "copper",
    "coral",
    "cosmos",
    "cotton",
    "cove",
    "crane",
    "crater",
    "creek",
    "cricket",
    "crocus",
    "crystal",
    "cumin",
    "current",
    "daisy",
    "dapple",
    "dawn",
    "delta",
    "denim",
    "dewdrop",
    "dingo",
    "dolphin",
    "domino",
    "donut",
    "drift",
    "dune",
    "dusk",
    "eagle",
    "ember",
    "estuary",
    "fable",
    "falcon",
    "fennel",
    "fern",
    "fiddle",
    "fig",
    "finch",
    "fjord",
    "flint",
    "fossil",
    "fox",
    "freckle",
    "frost",
    "galaxy",
    "garnet",
    "gecko",
    "geyser",
    "ginger",
    "glacier",
    "glade",
    "goose",
    "granite",
    "grape",
    "grove",
    "guitar",
    "hammock",
    "harbor",
    "hazel",
    "heron",
    "hickory",
    "honey",
    "husky",
    "iceberg",
    "iguana",
    "indigo",
    "inkwell",
    "iris",
    "island",
    "ivory",
    "jade",
    "jasmine",
    "jasper",
    "jigsaw",
    "juniper",
    "kayak",
    "kelp",
    "kettle",
    "kiwi",
    "koala",
    "lagoon",
    "lantern",
    "larch",
    "lark",
    "lava",
    "lemon",
    "lichen",
    "lilac",
    "lily",
    "lime",
    "linen",
    "lotus",
    "lunar",
    "lynx",
    "magnet",
    "mango",
    "mantis",
    "maple",
    "marble",
    "meadow",
    "melon",
    "mesa",
    "mint",
    "mirror",
    "mocha",
    "monsoon",
    "moss",
    "moth",
    "mulberry",
    "mustard",
    "nectar",
    "nettle",
    "night",
    "nimbus",
    "nutmeg",
    "oasis",
    "ocean",
    "ochre",
    "octave",
    "olive",
    "onyx",
    "opal",
    "orchid",
    "oriole",
    "osprey",
    "otter",
    "owl",
    "oyster",
    "palm",
    "panda",
    "pansy",
    "papaya",
    "parade",
    "peach",
    "pebble",
    "pecan",
    "penguin",
    "peony",
    "pepper",
    "petal",
    "pickle",
    "pigeon",
    "pine",
    "pistachio",
    "plum",
    "polar",
    "pond",
    "poppy",
    "prairie",
    "prism",
    "pumpkin",
    "quail",
    "quartz",
    "quill",
    "quince",
    "raccoon",
    "radish",
    "raven",
    "reef",
    "ribbon",
    "ridge",
    "river",
    "robin",
    "rocket",
    "rosemary",
    "ruby",
    "saffron",
    "sage",
    "salmon",
    "sandbar",
    "sapphire",
    "scarlet",
    "seal",
    "sequoia",
    "shadow",
    "shell",
    "sierra",
    "silver",
    "sleet",
    "sloth",
    "smoke",
    "sorrel",
    "sparrow",
    "spruce",
    "squash",
    "stone",
    "stork",
    "summit",
    "sunset",
    "swan",
    "tango",
    "teal",
    "tempo",
    "thistle",
    "tiger",
    "timber",
    "topaz",
    "toucan",
    "trellis",
    "trout",
    "tulip",
    "tundra",
    "turnip",
    "turtle",
];

/// `word-word-NN` from SHA-256 of the base64url SPKI public key string:
/// bytes 0 and 1 index `CUTE_WORDS`, byte 2 mod 100 is the two-digit suffix.
pub fn derive_cute_code(relay_public_key: &str) -> String {
    let digest = Sha256::digest(relay_public_key.as_bytes());
    let first = CUTE_WORDS[usize::from(digest[0])];
    let second = CUTE_WORDS[usize::from(digest[1])];
    let number = digest[2] % 100;
    format!("{first}-{second}-{number:02}")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Vectors produced by the JS implementation
    /// (`packages/relay/bin/fingerprint.mjs` `deriveCuteCode`).
    #[test]
    fn matches_the_js_implementation_on_pinned_vectors() {
        assert_eq!(derive_cute_code("test-key"), "gecko-oriole-35");
        assert_eq!(
            derive_cute_code("MCowBQYDK2VuAyEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
            "salmon-radish-40"
        );
        assert_eq!(derive_cute_code("abc"), "pebble-island-22");
    }

    #[test]
    fn word_table_has_exactly_256_distinct_words() {
        let mut sorted: Vec<&str> = CUTE_WORDS.to_vec();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), 256);
    }
}
