// relay_wire.rs — generated by packages/protocol/scripts/emit-rust.ts. DO NOT EDIT.
// Source of truth: src/relay.ts (Effect Schema) in chatmux's packages/protocol,
// emitted through generated/schema/relay-client.schema.json (relay -> Worker)
// and relay-server.schema.json (Worker -> relay).
//
// VENDOR STEP (cross-repo): the Rust relay lives in manaflow-ai/cmux (crate
// `chatmux-relay` in the cmux-tui workspace). After a chatmux protocol
// change, run `bun run generate` in chatmux's packages/protocol and copy
// this file verbatim into the cmux repo (e.g. cmux-tui/chatmux-relay/src/
// relay_wire.rs). Never edit the copy; re-vendor instead. The chatmux e2e
// conformance harness (apps/backend/test/e2e-workspace.ts) is the gate that
// the binary built from the vendored copy still speaks the wire.
//
// Dialect constants (src/relay.ts):
//   v2 hello negotiation, v3 exec verbs, v4 PTY, v5 process credentials,
//   v6 workspace verbs + fs_watch (RELAY_PROTOCOL_WORKSPACE_VERSION).
// Requires serde + serde_json (derive feature); no other crates.

#![allow(clippy::all)]

use serde::{Deserialize, Serialize};

/// A JSON boolean that must be `true` (a literal discriminant; decoding
/// the other value fails, which is what lets untagged unions dispatch).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ConstTrue;

impl Serialize for ConstTrue {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_bool(true)
    }
}

impl<'de> Deserialize<'de> for ConstTrue {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        if bool::deserialize(deserializer)? == true {
            Ok(ConstTrue)
        } else {
            Err(serde::de::Error::custom("expected true"))
        }
    }
}

/// A JSON boolean that must be `false` (a literal discriminant; decoding
/// the other value fails, which is what lets untagged unions dispatch).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ConstFalse;

impl Serialize for ConstFalse {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_bool(false)
    }
}

impl<'de> Deserialize<'de> for ConstFalse {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        if bool::deserialize(deserializer)? == false {
            Ok(ConstFalse)
        } else {
            Err(serde::de::Error::custom("expected false"))
        }
    }
}

/// The literal string "action_request" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagActionRequest {
    #[default]
    #[serde(rename = "action_request")]
    ActionRequest,
}

/// The literal string "action_result" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagActionResult {
    #[default]
    #[serde(rename = "action_result")]
    ActionResult,
}

/// The literal string "cmux-relay-managed-v1" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagCmuxRelayManagedV1 {
    #[default]
    #[serde(rename = "cmux-relay-managed-v1")]
    CmuxRelayManagedV1,
}

/// The literal string "console" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagConsole {
    #[default]
    #[serde(rename = "console")]
    Console,
}

/// The literal string "error" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagError {
    #[default]
    #[serde(rename = "error")]
    Error,
}

/// The literal string "fs_delete" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsDelete {
    #[default]
    #[serde(rename = "fs_delete")]
    FsDelete,
}

/// The literal string "fs_read" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsRead {
    #[default]
    #[serde(rename = "fs_read")]
    FsRead,
}

/// The literal string "fs_rename" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsRename {
    #[default]
    #[serde(rename = "fs_rename")]
    FsRename,
}

/// The literal string "fs_search" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsSearch {
    #[default]
    #[serde(rename = "fs_search")]
    FsSearch,
}

/// The literal string "fs_tree" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsTree {
    #[default]
    #[serde(rename = "fs_tree")]
    FsTree,
}

/// The literal string "fs_watch_close" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWatchClose {
    #[default]
    #[serde(rename = "fs_watch_close")]
    FsWatchClose,
}

/// The literal string "fs_watch_error" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWatchError {
    #[default]
    #[serde(rename = "fs_watch_error")]
    FsWatchError,
}

/// The literal string "fs_watch_event" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWatchEvent {
    #[default]
    #[serde(rename = "fs_watch_event")]
    FsWatchEvent,
}

/// The literal string "fs_watch_open" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWatchOpen {
    #[default]
    #[serde(rename = "fs_watch_open")]
    FsWatchOpen,
}

/// The literal string "fs_watch_opened" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWatchOpened {
    #[default]
    #[serde(rename = "fs_watch_opened")]
    FsWatchOpened,
}

/// The literal string "fs_write" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagFsWrite {
    #[default]
    #[serde(rename = "fs_write")]
    FsWrite,
}

/// The literal string "git_diff" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagGitDiff {
    #[default]
    #[serde(rename = "git_diff")]
    GitDiff,
}

/// The literal string "git_status" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagGitStatus {
    #[default]
    #[serde(rename = "git_status")]
    GitStatus,
}

/// The literal string "heartbeat" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagHeartbeat {
    #[default]
    #[serde(rename = "heartbeat")]
    Heartbeat,
}

/// The literal string "heartbeat_ack" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagHeartbeatAck {
    #[default]
    #[serde(rename = "heartbeat_ack")]
    HeartbeatAck,
}

/// The literal string "hello" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagHello {
    #[default]
    #[serde(rename = "hello")]
    Hello,
}

/// The literal string "hello_accepted" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagHelloAccepted {
    #[default]
    #[serde(rename = "hello_accepted")]
    HelloAccepted,
}

/// The literal string "network" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagNetwork {
    #[default]
    #[serde(rename = "network")]
    Network,
}

/// The literal string "preview_console_tail" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPreviewConsoleTail {
    #[default]
    #[serde(rename = "preview_console_tail")]
    PreviewConsoleTail,
}

/// The literal string "preview_open" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPreviewOpen {
    #[default]
    #[serde(rename = "preview_open")]
    PreviewOpen,
}

/// The literal string "pty_close" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyClose {
    #[default]
    #[serde(rename = "pty_close")]
    PtyClose,
}

/// The literal string "pty_error" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyError {
    #[default]
    #[serde(rename = "pty_error")]
    PtyError,
}

/// The literal string "pty_exit" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyExit {
    #[default]
    #[serde(rename = "pty_exit")]
    PtyExit,
}

/// The literal string "pty_flow" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyFlow {
    #[default]
    #[serde(rename = "pty_flow")]
    PtyFlow,
}

/// The literal string "pty_input" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyInput {
    #[default]
    #[serde(rename = "pty_input")]
    PtyInput,
}

/// The literal string "pty_open" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyOpen {
    #[default]
    #[serde(rename = "pty_open")]
    PtyOpen,
}

/// The literal string "pty_opened" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyOpened {
    #[default]
    #[serde(rename = "pty_opened")]
    PtyOpened,
}

/// The literal string "pty_output" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyOutput {
    #[default]
    #[serde(rename = "pty_output")]
    PtyOutput,
}

/// The literal string "pty_resize" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagPtyResize {
    #[default]
    #[serde(rename = "pty_resize")]
    PtyResize,
}

/// The literal string "set_trust" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagSetTrust {
    #[default]
    #[serde(rename = "set_trust")]
    SetTrust,
}

/// The literal string "surface_list" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagSurfaceList {
    #[default]
    #[serde(rename = "surface_list")]
    SurfaceList,
}

/// The literal string "surface_list_result" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagSurfaceListResult {
    #[default]
    #[serde(rename = "surface_list_result")]
    SurfaceListResult,
}

/// The literal string "trust_ack" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagTrustAck {
    #[default]
    #[serde(rename = "trust_ack")]
    TrustAck,
}

/// The literal string "upgrade_required" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagUpgradeRequired {
    #[default]
    #[serde(rename = "upgrade_required")]
    UpgradeRequired,
}

/// The literal string "workspace_request" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagWorkspaceRequest {
    #[default]
    #[serde(rename = "workspace_request")]
    WorkspaceRequest,
}

/// The literal string "workspace_result" (a frame/field discriminant).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub enum TagWorkspaceResult {
    #[default]
    #[serde(rename = "workspace_result")]
    WorkspaceResult,
}

/// utf8 for valid text; base64 when the bytes are not UTF-8
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FsContentEncoding {
    #[serde(rename = "utf8")]
    Utf8,
    #[serde(rename = "base64")]
    Base64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsDeleteOp {
    #[serde(rename = "op")]
    pub op: TagFsDelete,
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "recursive", default, skip_serializing_if = "Option::is_none")]
    pub recursive: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsDeleteResult {
    #[serde(rename = "op")]
    pub op: TagFsDelete,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsReadOp {
    #[serde(rename = "op")]
    pub op: TagFsRead,
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "maxBytes")]
    pub max_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsReadResult {
    #[serde(rename = "op")]
    pub op: TagFsRead,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "encoding")]
    pub encoding: FsContentEncoding,
    #[serde(rename = "sha256")]
    pub sha256: Sha256Hex,
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsRenameOp {
    #[serde(rename = "op")]
    pub op: TagFsRename,
    #[serde(rename = "fromPath")]
    pub from_path: WorkspacePath,
    #[serde(rename = "toPath")]
    pub to_path: WorkspacePath,
    #[serde(rename = "overwrite", default, skip_serializing_if = "Option::is_none")]
    pub overwrite: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsRenameResult {
    #[serde(rename = "op")]
    pub op: TagFsRename,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsSearchMatch {
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "line")]
    pub line: i64,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "spans")]
    pub spans: Vec<FsSearchSpan>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsSearchOp {
    #[serde(rename = "op")]
    pub op: TagFsSearch,
    #[serde(rename = "query")]
    pub query: String,
    #[serde(rename = "root", default, skip_serializing_if = "Option::is_none")]
    pub root: Option<WorkspacePath>,
    #[serde(rename = "maxResults")]
    pub max_results: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsSearchResult {
    #[serde(rename = "op")]
    pub op: TagFsSearch,
    #[serde(rename = "matches")]
    pub matches: Vec<FsSearchMatch>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsSearchSpan {
    #[serde(rename = "start")]
    pub start: i64,
    #[serde(rename = "end")]
    pub end: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsTreeEntry {
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "kind")]
    pub kind: FsTreeEntryKind,
    #[serde(rename = "size", default, skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    #[serde(rename = "mtimeMs", default, skip_serializing_if = "Option::is_none")]
    pub mtime_ms: Option<f64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FsTreeEntryKind {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "dir")]
    Dir,
    #[serde(rename = "symlink")]
    Symlink,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsTreeOp {
    #[serde(rename = "op")]
    pub op: TagFsTree,
    #[serde(rename = "root", default, skip_serializing_if = "Option::is_none")]
    pub root: Option<WorkspacePath>,
    #[serde(rename = "maxEntries")]
    pub max_entries: i64,
    #[serde(rename = "includeIgnored", default, skip_serializing_if = "Option::is_none")]
    pub include_ignored: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsTreeResult {
    #[serde(rename = "op")]
    pub op: TagFsTree,
    #[serde(rename = "root")]
    pub root: String,
    #[serde(rename = "entries")]
    pub entries: Vec<FsTreeEntry>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsWatchChange {
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "kind")]
    pub kind: FsWatchChangeKind,
    #[serde(rename = "oldPath", default, skip_serializing_if = "Option::is_none")]
    pub old_path: Option<WorkspacePath>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FsWatchChangeKind {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "modified")]
    Modified,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "renamed")]
    Renamed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsWriteOp {
    #[serde(rename = "op")]
    pub op: TagFsWrite,
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "baseSha256", default, skip_serializing_if = "Option::is_none")]
    pub base_sha256: Option<Sha256Hex>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FsWriteResult {
    #[serde(rename = "op")]
    pub op: TagFsWrite,
    #[serde(rename = "sha256")]
    pub sha256: Sha256Hex,
    #[serde(rename = "size")]
    pub size: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitDiffOp {
    #[serde(rename = "op")]
    pub op: TagGitDiff,
    #[serde(rename = "base", default, skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    #[serde(rename = "paths", default, skip_serializing_if = "Option::is_none")]
    pub paths: Option<Vec<WorkspacePath>>,
    #[serde(rename = "contextLines", default, skip_serializing_if = "Option::is_none")]
    pub context_lines: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitDiffResult {
    #[serde(rename = "op")]
    pub op: TagGitDiff,
    #[serde(rename = "patch")]
    pub patch: String,
    #[serde(rename = "stat")]
    pub stat: GitDiffStat,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitDiffStat {
    #[serde(rename = "files")]
    pub files: i64,
    #[serde(rename = "additions")]
    pub additions: i64,
    #[serde(rename = "deletions")]
    pub deletions: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitStatusEntry {
    #[serde(rename = "path")]
    pub path: WorkspacePath,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "origPath", default, skip_serializing_if = "Option::is_none")]
    pub orig_path: Option<WorkspacePath>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitStatusOp {
    #[serde(rename = "op")]
    pub op: TagGitStatus,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GitStatusResult {
    #[serde(rename = "op")]
    pub op: TagGitStatus,
    #[serde(rename = "branch")]
    pub branch: Option<String>,
    #[serde(rename = "upstream")]
    pub upstream: Option<String>,
    #[serde(rename = "ahead")]
    pub ahead: i64,
    #[serde(rename = "behind")]
    pub behind: i64,
    #[serde(rename = "entries")]
    pub entries: Vec<GitStatusEntry>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MachineScope {
    #[serde(rename = "personal")]
    Personal,
    #[serde(rename = "org")]
    Org,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ManagedRelayEnrollment {
    #[serde(rename = "client")]
    pub client: TagCmuxRelayManagedV1,
    #[serde(rename = "orgId")]
    pub org_id: String,
    #[serde(rename = "targetRef")]
    pub target_ref: String,
    #[serde(rename = "generation")]
    pub generation: String,
    #[serde(rename = "provider")]
    pub provider: ManagedRelayEnrollmentProvider,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ManagedRelayEnrollmentProvider {
    #[serde(rename = "e2b")]
    E2b,
    #[serde(rename = "daytona")]
    Daytona,
    #[serde(rename = "sprites")]
    Sprites,
    #[serde(rename = "freestyle")]
    Freestyle,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewConsoleEvent {
    #[serde(rename = "kind")]
    pub kind: TagConsole,
    #[serde(rename = "level")]
    pub level: PreviewConsoleLevel,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "at")]
    pub at: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PreviewConsoleLevel {
    #[serde(rename = "log")]
    Log,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warn")]
    Warn,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "debug")]
    Debug,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewConsoleTailOp {
    #[serde(rename = "op")]
    pub op: TagPreviewConsoleTail,
    #[serde(rename = "maxEvents", default, skip_serializing_if = "Option::is_none")]
    pub max_events: Option<i64>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewConsoleTailResult {
    #[serde(rename = "op")]
    pub op: TagPreviewConsoleTail,
    #[serde(rename = "events")]
    pub events: Vec<PreviewEvent>,
    #[serde(rename = "dropped")]
    pub dropped: i64,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PreviewEvent {
    Console(PreviewConsoleEvent),
    Network(PreviewNetworkEvent),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewNetworkEvent {
    #[serde(rename = "kind")]
    pub kind: TagNetwork,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "status")]
    pub status: Option<i64>,
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "at")]
    pub at: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewOpenOp {
    #[serde(rename = "op")]
    pub op: TagPreviewOpen,
    #[serde(rename = "targetPort")]
    pub target_port: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PreviewOpenResult {
    #[serde(rename = "op")]
    pub op: TagPreviewOpen,
    #[serde(rename = "proxyPort")]
    pub proxy_port: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayActionErrorCode {
    #[serde(rename = "unsupported_verb")]
    UnsupportedVerb,
    #[serde(rename = "path_forbidden")]
    PathForbidden,
    #[serde(rename = "trust_refused")]
    TrustRefused,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayActionRequest {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagActionRequest,
    #[serde(rename = "actionId")]
    pub action_id: String,
    #[serde(rename = "verb")]
    pub verb: RelayActionVerb,
    #[serde(rename = "args")]
    pub args: serde_json::Map<String, serde_json::Value>,
    #[serde(rename = "runtime", default, skip_serializing_if = "Option::is_none")]
    pub runtime: Option<RelayProcessRuntime>,
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
    #[serde(rename = "allowedRoots")]
    pub allowed_roots: Option<Vec<String>>,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "threadId")]
    pub thread_id: Option<String>,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RelayActionResult {
    RelayActionResultOk(RelayActionResultOk),
    RelayActionResultError(RelayActionResultError),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayActionResultError {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagActionResult,
    #[serde(rename = "actionId")]
    pub action_id: String,
    #[serde(rename = "ok")]
    pub ok: ConstFalse,
    #[serde(rename = "code")]
    pub code: RelayActionErrorCode,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayActionResultOk {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagActionResult,
    #[serde(rename = "actionId")]
    pub action_id: String,
    #[serde(rename = "ok")]
    pub ok: ConstTrue,
    #[serde(rename = "result")]
    pub result: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayActionVerb {
    #[serde(rename = "exec")]
    Exec,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "ls")]
    Ls,
    #[serde(rename = "grep")]
    Grep,
    #[serde(rename = "find")]
    Find,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RelayClientMessage {
    RelayHello(RelayHello),
    RelayHeartbeat(RelayHeartbeat),
    RelaySetTrust(RelaySetTrust),
    RelayActionResult(RelayActionResult),
    RelayPtyOpened(RelayPtyOpened),
    RelayPtyOutput(RelayPtyOutput),
    RelayPtyExit(RelayPtyExit),
    RelayPtyError(RelayPtyError),
    RelaySurfaceListResult(RelaySurfaceListResult),
    RelayWorkspaceResult(RelayWorkspaceResult),
    RelayFsWatchOpened(RelayFsWatchOpened),
    RelayFsWatchEvent(RelayFsWatchEvent),
    RelayFsWatchError(RelayFsWatchError),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayErrorCode {
    #[serde(rename = "unauthorized")]
    Unauthorized,
    #[serde(rename = "machine_mismatch")]
    MachineMismatch,
    #[serde(rename = "unknown_type")]
    UnknownType,
    #[serde(rename = "invalid_trust")]
    InvalidTrust,
    #[serde(rename = "malformed")]
    Malformed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayErrorMessage {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagError,
    #[serde(rename = "code")]
    pub code: RelayErrorCode,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Relay wire dialect of this frame (>= 2)
pub type RelayFrameVersion = i64;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayFsWatchClose {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagFsWatchClose,
    #[serde(rename = "watchId")]
    pub watch_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayFsWatchError {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagFsWatchError,
    #[serde(rename = "watchId")]
    pub watch_id: String,
    #[serde(rename = "code")]
    pub code: WorkspaceErrorCode,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayFsWatchEvent {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagFsWatchEvent,
    #[serde(rename = "watchId")]
    pub watch_id: String,
    #[serde(rename = "changes")]
    pub changes: Vec<FsWatchChange>,
    #[serde(rename = "overflow", default, skip_serializing_if = "Option::is_none")]
    pub overflow: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayFsWatchOpen {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagFsWatchOpen,
    #[serde(rename = "watchId")]
    pub watch_id: String,
    #[serde(rename = "root", default, skip_serializing_if = "Option::is_none")]
    pub root: Option<WorkspacePath>,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
    #[serde(rename = "allowedRoots")]
    pub allowed_roots: Option<Vec<String>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayFsWatchOpened {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagFsWatchOpened,
    #[serde(rename = "watchId")]
    pub watch_id: String,
    #[serde(rename = "root")]
    pub root: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayHeartbeat {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagHeartbeat,
    #[serde(rename = "at")]
    pub at: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayHeartbeatAck {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagHeartbeatAck,
    #[serde(rename = "at")]
    pub at: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayHello {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagHello,
    #[serde(rename = "relayProtocolVersion")]
    pub relay_protocol_version: i64,
    #[serde(rename = "cliVersion")]
    pub cli_version: String,
    #[serde(rename = "machineId")]
    pub machine_id: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "allowedRoots", default, skip_serializing_if = "Option::is_none")]
    pub allowed_roots: Option<Vec<String>>,
    #[serde(rename = "managedEnrollment", default, skip_serializing_if = "Option::is_none")]
    pub managed_enrollment: Option<ManagedRelayEnrollment>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayHelloAccepted {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagHelloAccepted,
    #[serde(rename = "relayProtocolVersion")]
    pub relay_protocol_version: i64,
    #[serde(rename = "heartbeatIntervalMs")]
    pub heartbeat_interval_ms: i64,
    #[serde(rename = "machineName")]
    pub machine_name: String,
    #[serde(rename = "scope")]
    pub scope: MachineScope,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
    #[serde(rename = "ownerUserId", default, skip_serializing_if = "Option::is_none")]
    pub owner_user_id: Option<String>,
    #[serde(rename = "managedSessionToken", default, skip_serializing_if = "Option::is_none")]
    pub managed_session_token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayProcessRuntime {
    #[serde(rename = "environment")]
    pub environment: std::collections::BTreeMap<String, String>,
    #[serde(rename = "files")]
    pub files: Vec<RelayRuntimeFileBinding>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyClose {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyClose,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyError {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyError,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "code")]
    pub code: RelayPtyErrorCode,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayPtyErrorCode {
    #[serde(rename = "bad_request")]
    BadRequest,
    #[serde(rename = "trust_refused")]
    TrustRefused,
    #[serde(rename = "session_limit")]
    SessionLimit,
    #[serde(rename = "terminal_gone")]
    TerminalGone,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyExit {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyExit,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "code")]
    pub code: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyFlow {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyFlow,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "pause")]
    pub pause: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyInput {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyInput,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "dataB64")]
    pub data_b64: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyOpen {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyOpen,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "session")]
    pub session: RelayPtySessionName,
    #[serde(rename = "cols")]
    pub cols: i64,
    #[serde(rename = "rows")]
    pub rows: i64,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
    #[serde(rename = "allowedRoots")]
    pub allowed_roots: Option<Vec<String>>,
    #[serde(rename = "surface", default, skip_serializing_if = "Option::is_none")]
    pub surface: Option<RelayPtySurfaceRef>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyOpened {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyOpened,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "session")]
    pub session: RelayPtySessionName,
    #[serde(rename = "created")]
    pub created: bool,
    #[serde(rename = "cols")]
    pub cols: i64,
    #[serde(rename = "rows")]
    pub rows: i64,
    #[serde(rename = "surface", default, skip_serializing_if = "Option::is_none")]
    pub surface: Option<RelayPtySurfaceRef>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyOutput {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyOutput,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "dataB64")]
    pub data_b64: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayPtyResize {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagPtyResize,
    #[serde(rename = "ptyId")]
    pub pty_id: String,
    #[serde(rename = "cols")]
    pub cols: i64,
    #[serde(rename = "rows")]
    pub rows: i64,
}

/// Machine-side PTY session name (becomes a socket filename)
pub type RelayPtySessionName = String;

/// A terminal inside the session (cmux-tui surface/terminal id)
pub type RelayPtySurfaceRef = String;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayRuntimeFileBinding {
    #[serde(rename = "contentEnvironmentVariable")]
    pub content_environment_variable: String,
    #[serde(rename = "pathEnvironmentVariable")]
    pub path_environment_variable: String,
    #[serde(rename = "pathHint")]
    pub path_hint: String,
    #[serde(rename = "format")]
    pub format: RelayRuntimeFileBindingFormat,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RelayRuntimeFileBindingFormat {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "pem")]
    Pem,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RelayServerMessage {
    HelloAccepted(RelayHelloAccepted),
    UpgradeRequired(RelayUpgradeRequired),
    HeartbeatAck(RelayHeartbeatAck),
    TrustAck(RelayTrustAck),
    Error(RelayErrorMessage),
    ActionRequest(RelayActionRequest),
    PtyOpen(RelayPtyOpen),
    PtyInput(RelayPtyInput),
    PtyResize(RelayPtyResize),
    PtyFlow(RelayPtyFlow),
    PtyClose(RelayPtyClose),
    SurfaceList(RelaySurfaceListRequest),
    WorkspaceRequest(RelayWorkspaceRequest),
    FsWatchOpen(RelayFsWatchOpen),
    FsWatchClose(RelayFsWatchClose),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelaySetTrust {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagSetTrust,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelaySurface {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "subtitle", default, skip_serializing_if = "Option::is_none")]
    pub subtitle: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelaySurfaceListRequest {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagSurfaceList,
    #[serde(rename = "requestId")]
    pub request_id: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelaySurfaceListResult {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagSurfaceListResult,
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "surfaces")]
    pub surfaces: Vec<RelaySurface>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayTrustAck {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagTrustAck,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayUpgradeRequired {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagUpgradeRequired,
    #[serde(rename = "minVersion")]
    pub min_version: i64,
    #[serde(rename = "message")]
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayWorkspaceRequest {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagWorkspaceRequest,
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "op")]
    pub op: WorkspaceOp,
    #[serde(rename = "timeoutMs")]
    pub timeout_ms: i64,
    #[serde(rename = "allowedRoots")]
    pub allowed_roots: Option<Vec<String>>,
    #[serde(rename = "trust")]
    pub trust: TrustLevel,
    #[serde(rename = "actorId")]
    pub actor_id: String,
    #[serde(rename = "threadId")]
    pub thread_id: Option<String>,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RelayWorkspaceResult {
    RelayWorkspaceResultOk(RelayWorkspaceResultOk),
    RelayWorkspaceResultError(RelayWorkspaceResultError),
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayWorkspaceResultError {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagWorkspaceResult,
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "ok")]
    pub ok: ConstFalse,
    #[serde(rename = "code")]
    pub code: WorkspaceErrorCode,
    #[serde(rename = "message", default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "currentSha256", default, skip_serializing_if = "Option::is_none")]
    pub current_sha256: Option<Sha256Hex>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RelayWorkspaceResultOk {
    #[serde(rename = "version")]
    pub version: RelayFrameVersion,
    #[serde(rename = "type")]
    pub r#type: TagWorkspaceResult,
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "ok")]
    pub ok: ConstTrue,
    #[serde(rename = "result")]
    pub result: WorkspaceResultBody,
}

/// Lowercase hex SHA-256 of raw file bytes
pub type Sha256Hex = String;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TrustLevel {
    #[serde(rename = "observe")]
    Observe,
    #[serde(rename = "supervised")]
    Supervised,
    #[serde(rename = "autonomous")]
    Autonomous,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkspaceErrorCode {
    #[serde(rename = "unsupported_verb")]
    UnsupportedVerb,
    #[serde(rename = "path_forbidden")]
    PathForbidden,
    #[serde(rename = "trust_refused")]
    TrustRefused,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "too_large")]
    TooLarge,
    #[serde(rename = "write_conflict")]
    WriteConflict,
    #[serde(rename = "destination_exists")]
    DestinationExists,
    #[serde(rename = "directory_not_empty")]
    DirectoryNotEmpty,
    #[serde(rename = "not_a_repository")]
    NotARepository,
    #[serde(rename = "watch_limit")]
    WatchLimit,
    #[serde(rename = "port_unavailable")]
    PortUnavailable,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "failed")]
    Failed,
}

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WorkspaceOp {
    FsTree(FsTreeOp),
    FsRead(FsReadOp),
    FsWrite(FsWriteOp),
    FsRename(FsRenameOp),
    FsDelete(FsDeleteOp),
    FsSearch(FsSearchOp),
    GitStatus(GitStatusOp),
    GitDiff(GitDiffOp),
    PreviewOpen(PreviewOpenOp),
    PreviewConsoleTail(PreviewConsoleTailOp),
}

/// File path, resolved and scoped by the relay against the allowed roots
pub type WorkspacePath = String;

/// Untagged: variants dispatch on their literal-enforcing fields (Tag*,
/// ConstTrue/ConstFalse), so exactly one variant can decode. A frame type
/// this build does not know fails the whole decode — answer it with a
/// typed error frame, never a socket close (W23).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WorkspaceResultBody {
    FsTree(FsTreeResult),
    FsRead(FsReadResult),
    FsWrite(FsWriteResult),
    FsRename(FsRenameResult),
    FsDelete(FsDeleteResult),
    FsSearch(FsSearchResult),
    GitStatus(GitStatusResult),
    GitDiff(GitDiffResult),
    PreviewOpen(PreviewOpenResult),
    PreviewConsoleTail(PreviewConsoleTailResult),
}
