// Writes docs/browser-repl/parity-report.md from the cases and the recorded
// results (node tests/browser-parity/diff/run.mjs report).
import fs from "node:fs";
import path from "node:path";
import { here, REFERENCES, readResults, allVerdicts } from "./lib.mjs";

const docPath = path.resolve(here, "../../../docs/browser-repl/parity-report.md");
const capsPath = path.resolve(here, "../capabilities.json");
const MARK = { same: "same", "cmux-better": "better", "cmux-worse": "WORSE", "not-applicable": "n/a", "out-of-scope": "scope", "not-run": "NOT RUN" };

export function writeReport(cases) {
  const results = Object.fromEntries(["cmux", "cmux-dev", ...REFERENCES].map((b) => [b, readResults(b)]));
  const rows = allVerdicts(cases, results);
  const byId = new Map(rows.map((r) => [r.id, r]));
  const caps = JSON.parse(fs.readFileSync(capsPath, "utf8"));
  const totals = Object.fromEntries(REFERENCES.map((r) => [r, {}]));
  for (const row of rows) for (const ref of REFERENCES) totals[ref][row.refs[ref].verdict] = (totals[ref][row.refs[ref].verdict] ?? 0) + 1;
  const count = (ref, v) => totals[ref][v] ?? 0;
  const appRows = rows.filter((r) => r.cmuxBackend === "cmux").length;
  const failing = rows.filter((r) => r.cmuxProblems.length);
  const lines = [];
  const meta = (b) => results[b].meta ?? {};
  lines.push("# Browser REPL parity report", "");
  lines.push(
    "Generated by `node tests/browser-parity/diff/run.mjs report` from the recorded",
    "differential results in `tests/browser-parity/diff/results/`. Each case is one",
    "task expressed in the cmux API, in reference A's REPL and in reference B",
    "(its reference runtime driving Chrome), run live; its observable",
    "outcomes (values, page state, error class, event order, `isTrusted`, timing",
    "class) are compared into a verdict per reference. Verdicts are recomputed",
    "from the results by `tests/browser-parity/unit/diff.test.mjs`, which fails on",
    "any cmux-worse verdict, any cmux result that misses its case's expectation,",
    "and any member without a same or better case.",
    "",
  );
  lines.push("## Evidence", "");
  lines.push(`- Reference A: ${meta("reference-a").version ?? "?"}, recorded ${meta("reference-a").recordedAt ?? "?"}.`);
  lines.push(`- Reference B: the installed app's reference runtime, AX and legacy modes, recorded ${meta("reference-b").recordedAt ?? "?"}.`);
  lines.push(`- cmux app: tagged build \`${meta("cmux").tag ?? "?"}\`${meta("cmux").sha ? ` at ${String(meta("cmux").sha).slice(0, 10)}` : ""}, recorded ${meta("cmux").recordedAt ?? "?"}; ${appRows} of ${rows.length} verdicts use the app's result${appRows < rows.length ? ", the rest the dev driver's (Playwright WebKit, the same runtime)" : ""}.`);
  lines.push("");
  lines.push("## Totals", "");
  lines.push(`${rows.length} cases. cmux misses its own expectation in ${failing.length}.`, "");
  lines.push("| Reference | same | cmux-better | cmux-worse | not-applicable | out-of-scope | not-run |", "| --- | ---: | ---: | ---: | ---: | ---: | ---: |");
  for (const ref of REFERENCES) lines.push(`| ${ref === "reference-a" ? "Reference A" : "Reference B"} | ${count(ref, "same")} | ${count(ref, "cmux-better")} | ${count(ref, "cmux-worse")} | ${count(ref, "not-applicable")} | ${count(ref, "out-of-scope")} | ${count(ref, "not-run")} |`);
  lines.push("");
  lines.push(
    "Verdicts: **same** (normalized outcomes equal), **better** (they differ and the",
    "case's stated reason holds on the recorded outcomes), **WORSE** (a gap),",
    "**n/a** (the reference has no way to do the task), **scope** (the task needs",
    "something outside the approved reference scope: another origin for reference B, a",
    "non-loopback host for reference A, a process kill or a person's click).",
    "",
  );

  lines.push("## Member matrix", "");
  const memberRows = [];
  for (const [group, members] of Object.entries(caps["reference-a"])) {
    for (const [name, e] of Object.entries(members)) memberRows.push(["reference-a", group === "globals" ? name : `${group}.${name}`, e]);
  }
  for (const [name, e] of Object.entries(caps["reference-b"])) memberRows.push(["reference-b", name, e]);
  for (const ref of REFERENCES) {
    lines.push(`### ${ref === "reference-a" ? "Reference A" : "Reference B"}`, "");
    lines.push("| Member | cmux | Cases (verdict) |", "| --- | --- | --- |");
    for (const [r, name, e] of memberRows.filter((m) => m[0] === ref)) {
      if (e.excluded) {
        lines.push(`| \`${name}\` | excluded | ${e.excluded.replace(/\|/g, "\\|")} |`);
        continue;
      }
      const cells = (e.cases ?? []).map((id) => `\`${id}\` ${MARK[byId.get(id)?.refs[r].verdict] ?? "?"}`).join(", ");
      lines.push(`| \`${name}\` | ${String(e.cmux).replace(/\|/g, "\\|")} | ${cells} |`);
    }
    lines.push("");
  }

  lines.push("## Cases", "");
  lines.push("| Case | Members / edge | cmux run | Reference A | Reference B |", "| --- | --- | --- | --- | --- |");
  for (const row of rows) {
    const what = [...row.members.map((m) => m.replace(/^(reference-a|reference-b):/, "")), ...[].concat(row.edge ?? []).map((e) => `edge:${e}`)].join(", ");
    lines.push(`| \`${row.id}\` | ${what} | ${row.cmuxBackend}${row.cmuxProblems.length ? " FAILS" : ""} | ${MARK[row.refs["reference-a"].verdict]} | ${MARK[row.refs["reference-b"].verdict]} |`);
  }
  lines.push("");

  lines.push("## Why cmux is better", "");
  for (const ref of REFERENCES) {
    const better = rows.filter((r) => r.refs[ref].verdict === "cmux-better");
    lines.push(`### Against ${ref === "reference-a" ? "Reference A" : "Reference B"} (${better.length})`, "");
    for (const r of better) lines.push(`- \`${r.id}\`: ${r.refs[ref].reason}.`);
    lines.push("");
  }

  lines.push("## Not applicable and out of scope", "");
  for (const ref of REFERENCES) {
    lines.push(`### ${ref === "reference-a" ? "Reference A" : "Reference B"}`, "");
    for (const r of rows.filter((x) => ["not-applicable", "out-of-scope"].includes(x.refs[ref].verdict))) lines.push(`- \`${r.id}\` (${MARK[r.refs[ref].verdict]}): ${r.refs[ref].reason}.`);
    lines.push("");
  }

  if (caps.sites) {
    lines.push("## Site integrations", "");
    lines.push("Every reference A site global and method and every reference B site capability (`reference/site-surface.txt`) maps to a cmux tool proven by `tests/browser-parity/sites` or a differential case, or to a pending user decision ([site-tools.md](site-tools.md)).", "");
    lines.push("| Reference | mapped to cmux | pending decision |", "| --- | ---: | ---: |");
    for (const ref of REFERENCES) {
      const entries = Object.values(caps.sites[ref] ?? {});
      lines.push(`| ${ref === "reference-a" ? "Reference A" : "Reference B"} | ${entries.filter((e) => !e.decision).length} | ${entries.filter((e) => e.decision).length} |`);
    }
    lines.push("");
    const byDecision = {};
    for (const ref of REFERENCES) for (const [name, e] of Object.entries(caps.sites[ref] ?? {})) if (e.decision) (byDecision[e.decision] ??= []).push(`${ref === "reference-a" ? "Reference A" : "Reference B"} \`${name}\``);
    for (const [d, names] of Object.entries(byDecision)) lines.push(`- decision \`${d}\`: ${names.join(", ")}.`);
    lines.push("");
  }

  lines.push("## Exclusions", "");
  for (const [r, name, e] of memberRows.filter((m) => m[2].excluded)) lines.push(`- ${r} \`${name}\`: ${e.excluded}`);
  lines.push("");
  const unverified = cases.filter((c) => c.requiresPerson && !results.cmux.cases[c.id]);
  if (unverified.length) {
    lines.push("## Unverified", "");
    for (const c of unverified) lines.push(`- \`${c.id}\`: needs a person during the run (${c.requiresPerson}); no app result is recorded.`);
    lines.push("");
  }
  if (failing.filter((r) => !unverified.some((c) => c.id === r.id)).length || rows.some((r) => REFERENCES.some((ref) => r.refs[ref].verdict === "cmux-worse"))) {
    lines.push("## Open gaps", "");
    for (const r of failing.filter((x) => !unverified.some((c) => c.id === x.id))) lines.push(`- \`${r.id}\`: ${r.cmuxProblems.join("; ")}`);
    for (const r of rows) for (const ref of REFERENCES) if (r.refs[ref].verdict === "cmux-worse") lines.push(`- \`${r.id}\` vs ${ref}: ${r.refs[ref].reason}`);
    lines.push("");
  }
  fs.writeFileSync(docPath, lines.join("\n").replace(/—/g, ", "));
  console.log(`wrote ${path.relative(process.cwd(), docPath)}`);
}
