// Generated from cmux-tui/spec/sdk-schema.json. DO NOT EDIT.
package com.cmux.raw;


import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;


public final class Commands {
    private Commands() {}

    public static final CommandMetadata APPLY_LAYOUT = new CommandMetadata("apply-layout", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata ATTACH_SURFACE = new CommandMetadata("attach-surface", Authority.FRONTEND, 5, null, StreamKind.ATTACH, Map.ofEntries(Map.entry("mode", 7L)), Map.ofEntries(Map.entry("cols", "attach-initial-size"), Map.entry("rows", "attach-initial-size")));
    public static final CommandMetadata BROWSER_ACTIVATE = new CommandMetadata("browser-activate", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_BACK = new CommandMetadata("browser-back", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_FORWARD = new CommandMetadata("browser-forward", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_FRAME_PRESENTED = new CommandMetadata("browser-frame-presented", Authority.FRONTEND, 10, "browser-pointer-frame-guard-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_INSERT_TEXT = new CommandMetadata("browser-insert-text", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_KEY = new CommandMetadata("browser-key", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_KEY_PRESS = new CommandMetadata("browser-key-press", Authority.FRONTEND, 10, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_MOUSE = new CommandMetadata("browser-mouse", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_MOUSE_GUARDED = new CommandMetadata("browser-mouse-guarded", Authority.FRONTEND, 10, "browser-pointer-frame-guard-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_NAVIGATE = new CommandMetadata("browser-navigate", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_RELOAD = new CommandMetadata("browser-reload", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_WHEEL = new CommandMetadata("browser-wheel", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata BROWSER_WHEEL_GUARDED = new CommandMetadata("browser-wheel-guarded", Authority.FRONTEND, 10, "browser-pointer-frame-guard-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLEAR_HISTORY = new CommandMetadata("clear-history", Authority.CONTROL, 9, "clear-history-v1", StreamKind.NONE, Map.ofEntries(Map.entry("fallback_key", 9L)), Map.ofEntries(Map.entry("fallback_key", "clear-history-key-v1")));
    public static final CommandMetadata CLEAR_WINDOW_TITLE = new CommandMetadata("clear-window-title", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLIENT_FOCUS = new CommandMetadata("client-focus", Authority.CONTROL, 12, "client-focus-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_PANE = new CommandMetadata("close-pane", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_PROVIDER_MANAGED_WORKSPACE = new CommandMetadata("close-provider-managed-workspace", Authority.PROVIDER_AUTHORITY, 9, "provider-managed-workspace-authority-v2", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_SCREEN = new CommandMetadata("close-screen", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_SURFACE = new CommandMetadata("close-surface", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_TERMINAL = new CommandMetadata("close-terminal", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CLOSE_WORKSPACE = new CommandMetadata("close-workspace", Authority.CONTROL, 5, null, StreamKind.NONE, Map.ofEntries(Map.entry("expected_generation", 7L), Map.entry("expected_revision", 7L), Map.entry("key", 7L), Map.entry("mutation_id", 7L), Map.entry("origin", 7L)), Map.ofEntries(Map.entry("key", "workspace-registry-v1")));
    public static final CommandMetadata COPY = new CommandMetadata("copy", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata CREATE_SURFACE_WITH_RECEIPT = new CommandMetadata("create-surface-with-receipt", Authority.CONTROL, 10, "creation-receipts-v1", StreamKind.NONE, Map.of(), Map.ofEntries(Map.entry("idempotency_key", "creation-attempt-keys-v1")));
    public static final CommandMetadata CREATE_TERMINAL = new CommandMetadata("create-terminal", Authority.CONTROL, 7, "workspace-registry-v1", StreamKind.NONE, Map.ofEntries(Map.entry("terminal_id", 9L)), Map.of());
    public static final CommandMetadata CREATE_WORKSPACE = new CommandMetadata("create-workspace", Authority.CONTROL, 7, "workspace-registry-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata DETACH_ATTACHED_VIEW = new CommandMetadata("detach-attached-view", Authority.FRONTEND, 10, "view-attachment-detach-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata DETACH_CLIENT = new CommandMetadata("detach-client", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata EXPORT_LAYOUT = new CommandMetadata("export-layout", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata FOCUS_DIRECTION = new CommandMetadata("focus-direction", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata FOCUS_PANE = new CommandMetadata("focus-pane", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata GET_BROWSER_PROVIDER = new CommandMetadata("get-browser-provider", Authority.LOCAL_ADMIN, 10, "browser-provider-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata GET_CELL_PIXELS = new CommandMetadata("get-cell-pixels", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata GET_FRONTEND_PROJECTION = new CommandMetadata("get-frontend-projection", Authority.CONTROL, 7, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata IDENTIFY = new CommandMetadata("identify", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata IDS = new CommandMetadata("ids", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata JOURNAL_FRONTEND_EVENT = new CommandMetadata("journal-frontend-event", Authority.CONTROL, 10, "frontend-journal-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata LIST_AGENTS = new CommandMetadata("list-agents", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata LIST_CLIENTS = new CommandMetadata("list-clients", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata LIST_TERMINALS = new CommandMetadata("list-terminals", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata LIST_WORKSPACES = new CommandMetadata("list-workspaces", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MARK_WORKSPACES_PROVIDER_MANAGED = new CommandMetadata("mark-workspaces-provider-managed", Authority.PROVIDER_AUTHORITY, 9, "provider-managed-workspace-authority-v2", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MINT_TERMINAL_RENDERER = new CommandMetadata("mint-terminal-renderer", Authority.FRONTEND, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MINT_TERMINAL_RENDERER_BY_TERMINAL = new CommandMetadata("mint-terminal-renderer-by-terminal", Authority.FRONTEND, 11, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MOVE_TAB = new CommandMetadata("move-tab", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MOVE_TERMINAL = new CommandMetadata("move-terminal", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata MOVE_WORKSPACE = new CommandMetadata("move-workspace", Authority.CONTROL, 5, null, StreamKind.NONE, Map.ofEntries(Map.entry("expected_generation", 7L), Map.entry("expected_revision", 7L), Map.entry("key", 7L), Map.entry("mutation_id", 7L), Map.entry("origin", 7L)), Map.ofEntries(Map.entry("key", "workspace-registry-v1")));
    public static final CommandMetadata NEW_BROWSER_TAB = new CommandMetadata("new-browser-tab", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NEW_PANE = new CommandMetadata("new-pane", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NEW_PANE_RIGHT = new CommandMetadata("new-pane-right", Authority.CONTROL, 9, "viewport-splits-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NEW_SCREEN = new CommandMetadata("new-screen", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NEW_TAB = new CommandMetadata("new-tab", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NEW_WORKSPACE = new CommandMetadata("new-workspace", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata NOTIFY = new CommandMetadata("notify", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata PAIRING_RESPONSE = new CommandMetadata("pairing-response", Authority.LOCAL_ADMIN, 7, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata PANE_NEIGHBOR = new CommandMetadata("pane-neighbor", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata PING = new CommandMetadata("ping", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata PROCESS_INFO = new CommandMetadata("process-info", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata PUT_FRONTEND_PROJECTION = new CommandMetadata("put-frontend-projection", Authority.CONTROL, 7, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata READ_SCREEN = new CommandMetadata("read-screen", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata READ_SCROLLBACK = new CommandMetadata("read-scrollback", Authority.CONTROL, 7, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata REGISTER_BROWSER_PROVIDER = new CommandMetadata("register-browser-provider", Authority.LOCAL_ADMIN, 10, "browser-provider-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RELEASE_ATTACHED_VIEW_SIZE = new CommandMetadata("release-attached-view-size", Authority.FRONTEND, 10, "view-attachment-lease-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RELEASE_SURFACE_SIZE = new CommandMetadata("release-surface-size", Authority.CONTROL, 7, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RELOAD_CONFIG = new CommandMetadata("reload-config", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RENAME_PANE = new CommandMetadata("rename-pane", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RENAME_PROVIDER_MANAGED_WORKSPACE = new CommandMetadata("rename-provider-managed-workspace", Authority.PROVIDER_AUTHORITY, 9, "provider-managed-workspace-authority-v2", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RENAME_SCREEN = new CommandMetadata("rename-screen", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RENAME_SURFACE = new CommandMetadata("rename-surface", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RENAME_WORKSPACE = new CommandMetadata("rename-workspace", Authority.CONTROL, 5, null, StreamKind.NONE, Map.ofEntries(Map.entry("expected_generation", 7L), Map.entry("expected_revision", 7L), Map.entry("key", 7L), Map.entry("mutation_id", 7L), Map.entry("origin", 7L)), Map.ofEntries(Map.entry("key", "workspace-registry-v1")));
    public static final CommandMetadata REPORT_AGENT = new CommandMetadata("report-agent", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata REPORT_FOCUS = new CommandMetadata("report-focus", Authority.CONTROL, 12, "client-focus-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RESIZE_ATTACHED_VIEW = new CommandMetadata("resize-attached-view", Authority.FRONTEND, 10, "view-attachment-lease-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RESIZE_SURFACE = new CommandMetadata("resize-surface", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RESOLVE_TERMINAL = new CommandMetadata("resolve-terminal", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata RUN = new CommandMetadata("run", Authority.CONTROL, 6, null, StreamKind.NONE, Map.ofEntries(Map.entry("key", 9L)), Map.of());
    public static final CommandMetadata SCROLL_SURFACE = new CommandMetadata("scroll-surface", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SELECT_SCREEN = new CommandMetadata("select-screen", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SELECT_TAB = new CommandMetadata("select-tab", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SELECT_WORKSPACE = new CommandMetadata("select-workspace", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SEND = new CommandMetadata("send", Authority.CONTROL, 5, null, StreamKind.NONE, Map.ofEntries(Map.entry("paste", 7L)), Map.of());
    public static final CommandMetadata SEND_KEY = new CommandMetadata("send-key", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SET_CELL_PIXELS = new CommandMetadata("set-cell-pixels", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SET_CLIENT_INFO = new CommandMetadata("set-client-info", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SET_CLIENT_SIZING = new CommandMetadata("set-client-sizing", Authority.CONTROL, 10, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SET_DEFAULT_COLORS = new CommandMetadata("set-default-colors", Authority.CONTROL, 5, null, StreamKind.NONE, Map.ofEntries(Map.entry("complete", 9L), Map.entry("cursor", 9L), Map.entry("cursor_blink", 9L), Map.entry("cursor_style", 9L), Map.entry("palette", 9L), Map.entry("selection_bg", 9L), Map.entry("selection_fg", 9L)), Map.of());
    public static final CommandMetadata SET_RATIO = new CommandMetadata("set-ratio", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SET_SPLIT_RATIO = new CommandMetadata("set-split-ratio", Authority.CONTROL, 8, null, StreamKind.NONE, Map.ofEntries(Map.entry("transaction", 9L)), Map.ofEntries(Map.entry("transaction", "layout-undo-v1")));
    public static final CommandMetadata SET_VIEWPORT_PANE_WIDTH = new CommandMetadata("set-viewport-pane-width", Authority.CONTROL, 9, "viewport-column-resize-v1", StreamKind.NONE, Map.ofEntries(Map.entry("transaction", 9L)), Map.ofEntries(Map.entry("transaction", "layout-undo-v1")));
    public static final CommandMetadata SET_WINDOW_TITLE = new CommandMetadata("set-window-title", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SHUTDOWN_DAEMON = new CommandMetadata("shutdown-daemon", Authority.LOCAL_ADMIN, 9, null, StreamKind.NONE, Map.ofEntries(Map.entry("force", 10L)), Map.ofEntries(Map.entry("force", "daemon-handoff-force-v1")));
    public static final CommandMetadata SIDEBAR_PLUGIN = new CommandMetadata("sidebar-plugin", Authority.FRONTEND, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SPLIT = new CommandMetadata("split", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata SUBSCRIBE = new CommandMetadata("subscribe", Authority.FRONTEND, 5, null, StreamKind.SUBSCRIBE, Map.ofEntries(Map.entry("surface", 9L), Map.entry("tree_events", 7L)), Map.ofEntries(Map.entry("surface", "surface-subscribe-filter")));
    public static final CommandMetadata SWAP_PANE = new CommandMetadata("swap-pane", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata TERMINAL_EVENTS = new CommandMetadata("terminal-events", Authority.CONTROL, 9, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata UNDO_LAYOUT = new CommandMetadata("undo-layout", Authority.CONTROL, 9, "layout-undo-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata UNREGISTER_BROWSER_PROVIDER = new CommandMetadata("unregister-browser-provider", Authority.LOCAL_ADMIN, 10, "browser-provider-v1", StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata VT_STATE = new CommandMetadata("vt-state", Authority.CONTROL, 5, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata WAIT_FOR = new CommandMetadata("wait-for", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());
    public static final CommandMetadata ZOOM_PANE = new CommandMetadata("zoom-pane", Authority.CONTROL, 6, null, StreamKind.NONE, Map.of(), Map.of());

    public static final Map<String, CommandMetadata> ALL;
    static {
        LinkedHashMap<String, CommandMetadata> values = new LinkedHashMap<>();
        values.put("apply-layout", APPLY_LAYOUT);
        values.put("attach-surface", ATTACH_SURFACE);
        values.put("browser-activate", BROWSER_ACTIVATE);
        values.put("browser-back", BROWSER_BACK);
        values.put("browser-forward", BROWSER_FORWARD);
        values.put("browser-frame-presented", BROWSER_FRAME_PRESENTED);
        values.put("browser-insert-text", BROWSER_INSERT_TEXT);
        values.put("browser-key", BROWSER_KEY);
        values.put("browser-key-press", BROWSER_KEY_PRESS);
        values.put("browser-mouse", BROWSER_MOUSE);
        values.put("browser-mouse-guarded", BROWSER_MOUSE_GUARDED);
        values.put("browser-navigate", BROWSER_NAVIGATE);
        values.put("browser-reload", BROWSER_RELOAD);
        values.put("browser-wheel", BROWSER_WHEEL);
        values.put("browser-wheel-guarded", BROWSER_WHEEL_GUARDED);
        values.put("clear-history", CLEAR_HISTORY);
        values.put("clear-window-title", CLEAR_WINDOW_TITLE);
        values.put("client-focus", CLIENT_FOCUS);
        values.put("close-pane", CLOSE_PANE);
        values.put("close-provider-managed-workspace", CLOSE_PROVIDER_MANAGED_WORKSPACE);
        values.put("close-screen", CLOSE_SCREEN);
        values.put("close-surface", CLOSE_SURFACE);
        values.put("close-terminal", CLOSE_TERMINAL);
        values.put("close-workspace", CLOSE_WORKSPACE);
        values.put("copy", COPY);
        values.put("create-surface-with-receipt", CREATE_SURFACE_WITH_RECEIPT);
        values.put("create-terminal", CREATE_TERMINAL);
        values.put("create-workspace", CREATE_WORKSPACE);
        values.put("detach-attached-view", DETACH_ATTACHED_VIEW);
        values.put("detach-client", DETACH_CLIENT);
        values.put("export-layout", EXPORT_LAYOUT);
        values.put("focus-direction", FOCUS_DIRECTION);
        values.put("focus-pane", FOCUS_PANE);
        values.put("get-browser-provider", GET_BROWSER_PROVIDER);
        values.put("get-cell-pixels", GET_CELL_PIXELS);
        values.put("get-frontend-projection", GET_FRONTEND_PROJECTION);
        values.put("identify", IDENTIFY);
        values.put("ids", IDS);
        values.put("journal-frontend-event", JOURNAL_FRONTEND_EVENT);
        values.put("list-agents", LIST_AGENTS);
        values.put("list-clients", LIST_CLIENTS);
        values.put("list-terminals", LIST_TERMINALS);
        values.put("list-workspaces", LIST_WORKSPACES);
        values.put("mark-workspaces-provider-managed", MARK_WORKSPACES_PROVIDER_MANAGED);
        values.put("mint-terminal-renderer", MINT_TERMINAL_RENDERER);
        values.put("mint-terminal-renderer-by-terminal", MINT_TERMINAL_RENDERER_BY_TERMINAL);
        values.put("move-tab", MOVE_TAB);
        values.put("move-terminal", MOVE_TERMINAL);
        values.put("move-workspace", MOVE_WORKSPACE);
        values.put("new-browser-tab", NEW_BROWSER_TAB);
        values.put("new-pane", NEW_PANE);
        values.put("new-pane-right", NEW_PANE_RIGHT);
        values.put("new-screen", NEW_SCREEN);
        values.put("new-tab", NEW_TAB);
        values.put("new-workspace", NEW_WORKSPACE);
        values.put("notify", NOTIFY);
        values.put("pairing-response", PAIRING_RESPONSE);
        values.put("pane-neighbor", PANE_NEIGHBOR);
        values.put("ping", PING);
        values.put("process-info", PROCESS_INFO);
        values.put("put-frontend-projection", PUT_FRONTEND_PROJECTION);
        values.put("read-screen", READ_SCREEN);
        values.put("read-scrollback", READ_SCROLLBACK);
        values.put("register-browser-provider", REGISTER_BROWSER_PROVIDER);
        values.put("release-attached-view-size", RELEASE_ATTACHED_VIEW_SIZE);
        values.put("release-surface-size", RELEASE_SURFACE_SIZE);
        values.put("reload-config", RELOAD_CONFIG);
        values.put("rename-pane", RENAME_PANE);
        values.put("rename-provider-managed-workspace", RENAME_PROVIDER_MANAGED_WORKSPACE);
        values.put("rename-screen", RENAME_SCREEN);
        values.put("rename-surface", RENAME_SURFACE);
        values.put("rename-workspace", RENAME_WORKSPACE);
        values.put("report-agent", REPORT_AGENT);
        values.put("report-focus", REPORT_FOCUS);
        values.put("resize-attached-view", RESIZE_ATTACHED_VIEW);
        values.put("resize-surface", RESIZE_SURFACE);
        values.put("resolve-terminal", RESOLVE_TERMINAL);
        values.put("run", RUN);
        values.put("scroll-surface", SCROLL_SURFACE);
        values.put("select-screen", SELECT_SCREEN);
        values.put("select-tab", SELECT_TAB);
        values.put("select-workspace", SELECT_WORKSPACE);
        values.put("send", SEND);
        values.put("send-key", SEND_KEY);
        values.put("set-cell-pixels", SET_CELL_PIXELS);
        values.put("set-client-info", SET_CLIENT_INFO);
        values.put("set-client-sizing", SET_CLIENT_SIZING);
        values.put("set-default-colors", SET_DEFAULT_COLORS);
        values.put("set-ratio", SET_RATIO);
        values.put("set-split-ratio", SET_SPLIT_RATIO);
        values.put("set-viewport-pane-width", SET_VIEWPORT_PANE_WIDTH);
        values.put("set-window-title", SET_WINDOW_TITLE);
        values.put("shutdown-daemon", SHUTDOWN_DAEMON);
        values.put("sidebar-plugin", SIDEBAR_PLUGIN);
        values.put("split", SPLIT);
        values.put("subscribe", SUBSCRIBE);
        values.put("swap-pane", SWAP_PANE);
        values.put("terminal-events", TERMINAL_EVENTS);
        values.put("undo-layout", UNDO_LAYOUT);
        values.put("unregister-browser-provider", UNREGISTER_BROWSER_PROVIDER);
        values.put("vt-state", VT_STATE);
        values.put("wait-for", WAIT_FOR);
        values.put("zoom-pane", ZOOM_PANE);
        ALL = Collections.unmodifiableMap(values);
    }
}
