import Foundation

/// Recognizes only the attach command generated by cmux's local-tmux profile.
///
/// `tmuxStartCommand` is also used by older agent integrations, so accepting
/// every command that happens to contain `tmux` would turn session restore into
/// an arbitrary shell-command launcher. The profile emits a fixed environment
/// marker and a server-incarnation-guarded attach shape; both are required here.
struct LocalTmuxRestoreCommandPolicy: Sendable {
    func restorableCommand(_ rawCommand: String?) -> String? {
        guard let command = rawCommand?.trimmingCharacters(in: .whitespacesAndNewlines),
              !command.isEmpty,
              !containsControlScalar(command) else {
            return nil
        }
        let words = shellWords(command)
        let isCanonicalCommand = words.count == 11
            && words[0] == "/usr/bin/env"
            && words[1] == "TMUX="
            && words[2] == "CMUX_LOCAL_TMUX=1"
        let isLegacyCommand = words.count == 11
            && words[0] == "TMUX="
            && words[1] == "CMUX_LOCAL_TMUX=1"
            && words[2] == "exec"
        guard isCanonicalCommand || isLegacyCommand,
              words[3].hasPrefix("/"),
              URL(fileURLWithPath: words[3]).standardizedFileURL.path == words[3],
              words[4] == "-S",
              words[5].hasPrefix("/"),
              (words[5] as NSString).lastPathComponent == "server.sock",
              URL(fileURLWithPath: words[5]).standardizedFileURL.path == words[5],
              words[6] == "if-shell",
              words[7] == "-F",
              let serverID = serverIdentity(from: words[8]),
              let sessionID = attachSessionID(from: words[9]),
              words[10] == "run-shell false" else {
            return nil
        }
        // The command is later evaluated by a login shell. Accept only the
        // exact single-quoted serialization produced by LocalTmuxCommandBuilder;
        // otherwise shell substitutions/operators could survive this word
        // parser even though their decoded values look structurally valid.
        let condition = "#{==:#{@cmux_local_server_id},\(serverID.uuidString.lowercased())}"
        let action = ["attach-session", "-t", sessionID]
            .map(shellQuote)
            .joined(separator: " ")
        let canonical = "/usr/bin/env TMUX= CMUX_LOCAL_TMUX=1 \(shellQuote(words[3])) -S \(shellQuote(words[5])) if-shell -F \(shellQuote(condition)) \(shellQuote(action)) \(shellQuote(words[10]))"
        let legacyCanonical = "TMUX= CMUX_LOCAL_TMUX=1 exec \(shellQuote(words[3])) -S \(shellQuote(words[5])) if-shell -F \(shellQuote(condition)) \(shellQuote(action)) \(shellQuote(words[10]))"
        guard (isCanonicalCommand && command == canonical)
            || (isLegacyCommand && command == legacyCanonical)
        else { return nil }
        return canonical
    }

    private func containsControlScalar(_ command: String) -> Bool {
        command.unicodeScalars.contains { scalar in
            switch scalar.properties.generalCategory {
            case .control, .format, .lineSeparator, .paragraphSeparator:
                return true
            default:
                return false
            }
        }
    }

    private func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private func serverIdentity(from condition: String) -> UUID? {
        let prefix = "#{==:#{@cmux_local_server_id},"
        guard condition.hasPrefix(prefix), condition.hasSuffix("}") else { return nil }
        let rawValue = String(condition.dropFirst(prefix.count).dropLast())
        guard let serverID = UUID(uuidString: rawValue),
              serverID.uuidString.lowercased() == rawValue else {
            return nil
        }
        return serverID
    }

    private func attachSessionID(from command: String) -> String? {
        let words = shellWords(command)
        guard words.count == 3,
              words[0] == "attach-session",
              words[1] == "-t",
              words[2].range(of: "^\\$[0-9]+$", options: .regularExpression) != nil else {
            return nil
        }
        return words[2]
    }

    /// Small shell-word reader used only to validate cmux-generated commands.
    /// It deliberately does not expand variables or execute substitutions.
    private func shellWords(_ command: String) -> [String] {
        var words: [String] = []
        var index = command.startIndex
        while index < command.endIndex {
            while index < command.endIndex, command[index].isWhitespace {
                index = command.index(after: index)
            }
            guard index < command.endIndex else { break }
            var value = ""
            while index < command.endIndex, !command[index].isWhitespace {
                let character = command[index]
                if character == "'" {
                    index = command.index(after: index)
                    while index < command.endIndex, command[index] != "'" {
                        value.append(command[index])
                        index = command.index(after: index)
                    }
                    guard index < command.endIndex else { return [] }
                    index = command.index(after: index)
                } else if character == "\\" {
                    let next = command.index(after: index)
                    guard next < command.endIndex else { return [] }
                    value.append(command[next])
                    index = command.index(after: next)
                } else {
                    value.append(character)
                    index = command.index(after: index)
                }
            }
            guard !value.isEmpty else { return [] }
            words.append(value)
        }
        return words
    }
}
