import Foundation

/// Recognizes only the attach command generated by cmux's local-zellij profile.
///
/// Session restore replays this command in a login shell, so it must never
/// become an arbitrary shell-command launcher. The values are read out of the
/// fixed single-quoted shape `LocalZellijCommandBuilder` emits, validated, and
/// re-serialized; only a byte-identical command is accepted.
struct LocalZellijRestoreCommandPolicy: Sendable {
    private static let quotedWord = #"'((?:[^']|'\\'')*)'"#
    private static let pattern = "^/usr/bin/env ZELLIJ_SOCKET_DIR=\(quotedWord) CMUX_LOCAL_ZELLIJ=1 \(quotedWord) 'attach' \(quotedWord) 'options' '--on-force-close' 'detach'$"

    func restorableCommand(_ rawCommand: String?) -> String? {
        guard let command = rawCommand?.trimmingCharacters(in: .whitespacesAndNewlines),
              !command.isEmpty,
              !containsLineBreakingScalar(command),
              let regex = try? NSRegularExpression(pattern: Self.pattern),
              let match = regex.firstMatch(in: command, range: NSRange(command.startIndex..., in: command)),
              match.numberOfRanges == 4 else {
            return nil
        }
        let values = (1...3).compactMap { index in
            Range(match.range(at: index), in: command).map {
                command[$0].replacingOccurrences(of: "'\\''", with: "'")
            }
        }
        guard values.count == 3 else { return nil }
        let (socketDirectory, zellijPath, sessionName) = (values[0], values[1], values[2])
        guard isStandardizedAbsolutePath(socketDirectory),
              (socketDirectory as NSString).lastPathComponent == "sock",
              isStandardizedAbsolutePath(zellijPath),
              sessionName.range(of: "^[A-Za-z0-9_][A-Za-z0-9_-]{0,127}$", options: .regularExpression) != nil else {
            return nil
        }
        let arguments = ["attach", sessionName, "options", "--on-force-close", "detach"]
            .map(shellQuote)
            .joined(separator: " ")
        let canonical = "/usr/bin/env ZELLIJ_SOCKET_DIR=\(shellQuote(socketDirectory)) CMUX_LOCAL_ZELLIJ=1 \(shellQuote(zellijPath)) \(arguments)"
        return command == canonical ? canonical : nil
    }

    private func isStandardizedAbsolutePath(_ path: String) -> Bool {
        path.hasPrefix("/") && URL(fileURLWithPath: path).standardizedFileURL.path == path
    }

    /// Controls and line or paragraph separators could split the command.
    /// Format characters such as U+200D (inside emoji) are allowed: the
    /// canonical comparison confines them to single-quoted path values.
    private func containsLineBreakingScalar(_ command: String) -> Bool {
        command.unicodeScalars.contains { scalar in
            switch scalar.properties.generalCategory {
            case .control, .lineSeparator, .paragraphSeparator:
                return true
            default:
                return false
            }
        }
    }

    private func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
