// The model-plane env every Cloud VM guest gets: where the coding agents
// inside the machine send model traffic. It is the same bytes for every
// machine in every environment, so the bake writes it into the snapshot
// (/etc/cmux/model-plane.env) and create writes nothing into the guest.
//
// How it stays static: the guest dials one alias host name. The machine's TLS
// edge rule (services/coderouter/vmModelPlane.ts) terminates that name inside
// the platform's edge, forwards to this deployment's real API host, and adds
// the machine's route token header. Prod, staging, and previews differ only in
// the rule's destination, never in what the guest sees. This module must stay
// free of database and framework imports: the bake script runs it on a laptop.

/** The public placeholder credential agents send; the edge swaps in the real token. */
export const VM_PLACEHOLDER_API_KEY = "cmux-vm-edge-placeholder";

export const VM_EDGE_ALIAS_DOMAIN_ENV = "CMUX_VM_EDGE_ALIAS_DOMAIN";
export const DEFAULT_VM_EDGE_ALIAS_DOMAIN = "coderouter.cmux.internal";

const HOST_NAME = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;

/** The host name the guest dials for model traffic; overridable for a deployment, never per machine. */
export function vmEdgeAliasDomain(raw: string | undefined = process.env[VM_EDGE_ALIAS_DOMAIN_ENV]): string {
  const value = raw?.trim().toLowerCase();
  if (!value) return DEFAULT_VM_EDGE_ALIAS_DOMAIN;
  if (!HOST_NAME.test(value)) {
    throw new Error(`${VM_EDGE_ALIAS_DOMAIN_ENV} must be a bare host name, got ${JSON.stringify(raw)}`);
  }
  return value;
}

export const VM_REFLECTION_ALIAS_DOMAIN_ENV = "CMUX_VM_REFLECTION_ALIAS_DOMAIN";
export const DEFAULT_VM_REFLECTION_ALIAS_DOMAIN = "reflection.cmux.internal";

/**
 * The header the edge adds on the reflection alias only, so the proxy can serve
 * `https://reflection.cmux.internal/<path>` from the guest-facing reflection API.
 * A routing hint, never a credential: the request still authenticates with the
 * injected route token.
 */
export const VM_REFLECTION_ALIAS_HEADER = "x-cmux-vm-alias";
export const VM_REFLECTION_ALIAS_VALUE = "reflection";

/** The vanity host a guest dials for reflection (`curl https://reflection.cmux.internal/`). */
export function vmReflectionAliasDomain(raw: string | undefined = process.env[VM_REFLECTION_ALIAS_DOMAIN_ENV]): string {
  const value = raw?.trim().toLowerCase();
  if (!value) return DEFAULT_VM_REFLECTION_ALIAS_DOMAIN;
  if (!HOST_NAME.test(value)) {
    throw new Error(`${VM_REFLECTION_ALIAS_DOMAIN_ENV} must be a bare host name, got ${JSON.stringify(raw)}`);
  }
  return value;
}

/** The variables agent-config.sh persists and every harness reads. No token, no per-machine value. */
export function vmGuestModelPlaneEnv(alias: string = vmEdgeAliasDomain()): Record<string, string> {
  const origin = `https://${alias}`;
  return {
    OPENAI_BASE_URL: `${origin}/v1`,
    OPENAI_API_KEY: VM_PLACEHOLDER_API_KEY,
    CMUX_CODEROUTER_URL: origin,
    ANTHROPIC_BASE_URL: origin,
    ANTHROPIC_API_KEY: VM_PLACEHOLDER_API_KEY,
  };
}

const ENV_NAME = /^[A-Z_][A-Z0-9_]*$/;
const ROUTE_TOKEN_GRAMMAR = /\bcrt_[A-Za-z0-9._-]+/;

/**
 * The file agent-config.sh sources (same format it writes itself from a boot
 * env). Refuses a route token anywhere in the values: the guest never holds one.
 */
export function renderVmGuestModelPlaneEnvFile(env: Readonly<Record<string, string>>): string {
  const quote = (value: string) => `'${value.replace(/'/g, `'\\''`)}'`;
  const lines = ["# generated by cmux; the same for every machine; managed, do not edit"];
  for (const [key, value] of Object.entries(env)) {
    if (!ENV_NAME.test(key)) throw new Error(`model-plane env key ${JSON.stringify(key)} is not a shell identifier`);
    if (ROUTE_TOKEN_GRAMMAR.test(value) || /\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/.test(value)) throw new Error(`model-plane env ${key} carries a route token; the guest never holds one`);
    if (value === "") continue;
    lines.push(`export ${key}=${quote(value)}`);
  }
  return `${lines.join("\n")}\n`;
}

/** Where the bake puts the file; agent-config.sh falls back to it when no boot env and no per-home file exist. */
export const VM_GUEST_MODEL_PLANE_ENV_PATH = "/etc/cmux/model-plane.env";
