// Code generated by cmux-tui SDK codegen. DO NOT EDIT.
// Mux protocol 12; IR SHA-256 65aa592727bc414fe3e66ac125c9b8541a1926bbe9eaa572acc66b4681bf6589.

package raw

const (
	SDKSchemaVersion   = 2
	MuxProtocolVersion = 12
	SDKIRSHA256        = "65aa592727bc414fe3e66ac125c9b8541a1926bbe9eaa572acc66b4681bf6589"
)

type Authority string

const (
	AuthorityControl           Authority = "control"
	AuthorityFrontend          Authority = "frontend"
	AuthorityLocalAdmin        Authority = "local-admin"
	AuthorityProviderAuthority Authority = "provider-authority"
)

type CommandMetadata struct {
	Name              string
	GoMethod          string
	Authority         Authority
	Since             uint32
	Capability        string
	Stream            string
	FieldSince        map[string]uint32
	FieldCapabilities map[string]string
}

type EventMetadata struct {
	Name       string
	Since      uint32
	Capability string
	Streams    []string
	Emission   string
}

type Profile string

const (
	ProfileControl           Profile = "control"
	ProfileFrontend          Profile = "frontend"
	ProfileLocalAdmin        Profile = "local-admin"
	ProfileProviderAuthority Profile = "provider-authority"
)

type ProfileMetadata struct {
	Name              Profile
	Description       string
	Inherits          []Profile
	Transport         string
	RequiresAuthority bool
}

var profileMetadata = map[Profile]ProfileMetadata{
	ProfileControl:           {Name: ProfileControl, Description: "Base authenticated session-control commands available to ordinary SDK clients.", Inherits: []Profile{}, Transport: "", RequiresAuthority: false},
	ProfileFrontend:          {Name: ProfileFrontend, Description: "Rendering, input, presentation, subscribe, and attach commands.", Inherits: []Profile{ProfileControl}, Transport: "", RequiresAuthority: false},
	ProfileLocalAdmin:        {Name: ProfileLocalAdmin, Description: "Trusted local administration commands.", Inherits: []Profile{ProfileControl}, Transport: "Unix-classified transport, including direct Unix and the current stdio relay", RequiresAuthority: false},
	ProfileProviderAuthority: {Name: ProfileProviderAuthority, Description: "Provider-owned workspace mutation commands.", Inherits: []Profile{ProfileControl}, Transport: "", RequiresAuthority: true},
}

var commandMetadata = map[string]CommandMetadata{
	"apply-layout":                       {Name: "apply-layout", GoMethod: "ApplyLayout", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"attach-surface":                     {Name: "attach-surface", GoMethod: "AttachSurface", Authority: AuthorityFrontend, Since: 5, Capability: "", Stream: "attach", FieldSince: map[string]uint32{"mode": 7}, FieldCapabilities: map[string]string{"cols": "attach-initial-size", "rows": "attach-initial-size"}},
	"browser-activate":                   {Name: "browser-activate", GoMethod: "BrowserActivate", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-back":                       {Name: "browser-back", GoMethod: "BrowserBack", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-forward":                    {Name: "browser-forward", GoMethod: "BrowserForward", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-frame-presented":            {Name: "browser-frame-presented", GoMethod: "BrowserFramePresented", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-insert-text":                {Name: "browser-insert-text", GoMethod: "BrowserInsertText", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-key":                        {Name: "browser-key", GoMethod: "BrowserKey", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-key-press":                  {Name: "browser-key-press", GoMethod: "BrowserKeyPress", Authority: AuthorityFrontend, Since: 10, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-mouse":                      {Name: "browser-mouse", GoMethod: "BrowserMouse", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-mouse-guarded":              {Name: "browser-mouse-guarded", GoMethod: "BrowserMouseGuarded", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-navigate":                   {Name: "browser-navigate", GoMethod: "BrowserNavigate", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-reload":                     {Name: "browser-reload", GoMethod: "BrowserReload", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-wheel":                      {Name: "browser-wheel", GoMethod: "BrowserWheel", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"browser-wheel-guarded":              {Name: "browser-wheel-guarded", GoMethod: "BrowserWheelGuarded", Authority: AuthorityFrontend, Since: 10, Capability: "browser-pointer-frame-guard-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"clear-history":                      {Name: "clear-history", GoMethod: "ClearHistory", Authority: AuthorityControl, Since: 9, Capability: "clear-history-v1", Stream: "", FieldSince: map[string]uint32{"fallback_key": 9}, FieldCapabilities: map[string]string{"fallback_key": "clear-history-key-v1"}},
	"clear-window-title":                 {Name: "clear-window-title", GoMethod: "ClearWindowTitle", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"client-focus":                       {Name: "client-focus", GoMethod: "ClientFocus", Authority: AuthorityControl, Since: 12, Capability: "client-focus-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-pane":                         {Name: "close-pane", GoMethod: "ClosePane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-provider-managed-workspace":   {Name: "close-provider-managed-workspace", GoMethod: "CloseProviderManagedWorkspace", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-screen":                       {Name: "close-screen", GoMethod: "CloseScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-surface":                      {Name: "close-surface", GoMethod: "CloseSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-terminal":                     {Name: "close-terminal", GoMethod: "CloseTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"close-workspace":                    {Name: "close-workspace", GoMethod: "CloseWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"key": "workspace-registry-v1"}},
	"copy":                               {Name: "copy", GoMethod: "Copy", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"create-surface-with-receipt":        {Name: "create-surface-with-receipt", GoMethod: "CreateSurfaceWithReceipt", Authority: AuthorityControl, Since: 10, Capability: "creation-receipts-v1", Stream: "", FieldSince: nil, FieldCapabilities: map[string]string{"idempotency_key": "creation-attempt-keys-v1"}},
	"create-terminal":                    {Name: "create-terminal", GoMethod: "CreateTerminal", Authority: AuthorityControl, Since: 7, Capability: "workspace-registry-v1", Stream: "", FieldSince: map[string]uint32{"terminal_id": 9}, FieldCapabilities: nil},
	"create-workspace":                   {Name: "create-workspace", GoMethod: "CreateWorkspace", Authority: AuthorityControl, Since: 7, Capability: "workspace-registry-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"detach-attached-view":               {Name: "detach-attached-view", GoMethod: "DetachAttachedView", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-detach-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"detach-client":                      {Name: "detach-client", GoMethod: "DetachClient", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"export-layout":                      {Name: "export-layout", GoMethod: "ExportLayout", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"focus-direction":                    {Name: "focus-direction", GoMethod: "FocusDirection", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"focus-pane":                         {Name: "focus-pane", GoMethod: "FocusPane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-browser-provider":               {Name: "get-browser-provider", GoMethod: "GetBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-cell-pixels":                    {Name: "get-cell-pixels", GoMethod: "GetCellPixels", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"get-frontend-projection":            {Name: "get-frontend-projection", GoMethod: "GetFrontendProjection", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"identify":                           {Name: "identify", GoMethod: "Identify", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ids":                                {Name: "ids", GoMethod: "IDs", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"journal-frontend-event":             {Name: "journal-frontend-event", GoMethod: "JournalFrontendEvent", Authority: AuthorityControl, Since: 10, Capability: "frontend-journal-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-agents":                        {Name: "list-agents", GoMethod: "ListAgents", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-clients":                       {Name: "list-clients", GoMethod: "ListClients", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-terminals":                     {Name: "list-terminals", GoMethod: "ListTerminals", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"list-workspaces":                    {Name: "list-workspaces", GoMethod: "ListWorkspaces", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mark-workspaces-provider-managed":   {Name: "mark-workspaces-provider-managed", GoMethod: "MarkWorkspacesProviderManaged", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mint-terminal-renderer":             {Name: "mint-terminal-renderer", GoMethod: "MintTerminalRenderer", Authority: AuthorityFrontend, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"mint-terminal-renderer-by-terminal": {Name: "mint-terminal-renderer-by-terminal", GoMethod: "MintTerminalRendererByTerminal", Authority: AuthorityFrontend, Since: 11, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-tab":                           {Name: "move-tab", GoMethod: "MoveTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-terminal":                      {Name: "move-terminal", GoMethod: "MoveTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"move-workspace":                     {Name: "move-workspace", GoMethod: "MoveWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"key": "workspace-registry-v1"}},
	"new-browser-tab":                    {Name: "new-browser-tab", GoMethod: "NewBrowserTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-pane":                           {Name: "new-pane", GoMethod: "NewPane", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-pane-right":                     {Name: "new-pane-right", GoMethod: "NewPaneRight", Authority: AuthorityControl, Since: 9, Capability: "viewport-splits-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-screen":                         {Name: "new-screen", GoMethod: "NewScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-tab":                            {Name: "new-tab", GoMethod: "NewTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"new-workspace":                      {Name: "new-workspace", GoMethod: "NewWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"notify":                             {Name: "notify", GoMethod: "Notify", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"pairing-response":                   {Name: "pairing-response", GoMethod: "PairingResponse", Authority: AuthorityLocalAdmin, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"pane-neighbor":                      {Name: "pane-neighbor", GoMethod: "PaneNeighbor", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"ping":                               {Name: "ping", GoMethod: "Ping", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"process-info":                       {Name: "process-info", GoMethod: "ProcessInfo", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"put-frontend-projection":            {Name: "put-frontend-projection", GoMethod: "PutFrontendProjection", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"read-screen":                        {Name: "read-screen", GoMethod: "ReadScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"read-scrollback":                    {Name: "read-scrollback", GoMethod: "ReadScrollback", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"register-browser-provider":          {Name: "register-browser-provider", GoMethod: "RegisterBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"release-attached-view-size":         {Name: "release-attached-view-size", GoMethod: "ReleaseAttachedViewSize", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-lease-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"release-surface-size":               {Name: "release-surface-size", GoMethod: "ReleaseSurfaceSize", Authority: AuthorityControl, Since: 7, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"reload-config":                      {Name: "reload-config", GoMethod: "ReloadConfig", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-pane":                        {Name: "rename-pane", GoMethod: "RenamePane", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-provider-managed-workspace":  {Name: "rename-provider-managed-workspace", GoMethod: "RenameProviderManagedWorkspace", Authority: AuthorityProviderAuthority, Since: 9, Capability: "provider-managed-workspace-authority-v2", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-screen":                      {Name: "rename-screen", GoMethod: "RenameScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-surface":                     {Name: "rename-surface", GoMethod: "RenameSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"rename-workspace":                   {Name: "rename-workspace", GoMethod: "RenameWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"expected_generation": 7, "expected_revision": 7, "key": 7, "mutation_id": 7, "origin": 7}, FieldCapabilities: map[string]string{"key": "workspace-registry-v1"}},
	"report-agent":                       {Name: "report-agent", GoMethod: "ReportAgent", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"report-focus":                       {Name: "report-focus", GoMethod: "ReportFocus", Authority: AuthorityControl, Since: 12, Capability: "client-focus-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"resize-attached-view":               {Name: "resize-attached-view", GoMethod: "ResizeAttachedView", Authority: AuthorityFrontend, Since: 10, Capability: "view-attachment-lease-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"resize-surface":                     {Name: "resize-surface", GoMethod: "ResizeSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"resolve-terminal":                   {Name: "resolve-terminal", GoMethod: "ResolveTerminal", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"run":                                {Name: "run", GoMethod: "Run", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: map[string]uint32{"key": 9}, FieldCapabilities: nil},
	"scroll-surface":                     {Name: "scroll-surface", GoMethod: "ScrollSurface", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-screen":                      {Name: "select-screen", GoMethod: "SelectScreen", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-tab":                         {Name: "select-tab", GoMethod: "SelectTab", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"select-workspace":                   {Name: "select-workspace", GoMethod: "SelectWorkspace", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"send":                               {Name: "send", GoMethod: "Send", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"paste": 7}, FieldCapabilities: nil},
	"send-key":                           {Name: "send-key", GoMethod: "SendKey", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-cell-pixels":                    {Name: "set-cell-pixels", GoMethod: "SetCellPixels", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-client-info":                    {Name: "set-client-info", GoMethod: "SetClientInfo", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-client-sizing":                  {Name: "set-client-sizing", GoMethod: "SetClientSizing", Authority: AuthorityControl, Since: 10, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-default-colors":                 {Name: "set-default-colors", GoMethod: "SetDefaultColors", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: map[string]uint32{"complete": 9, "cursor": 9, "cursor_blink": 9, "cursor_style": 9, "palette": 9, "selection_bg": 9, "selection_fg": 9}, FieldCapabilities: nil},
	"set-ratio":                          {Name: "set-ratio", GoMethod: "SetRatio", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"set-split-ratio":                    {Name: "set-split-ratio", GoMethod: "SetSplitRatio", Authority: AuthorityControl, Since: 8, Capability: "", Stream: "", FieldSince: map[string]uint32{"transaction": 9}, FieldCapabilities: map[string]string{"transaction": "layout-undo-v1"}},
	"set-viewport-pane-width":            {Name: "set-viewport-pane-width", GoMethod: "SetViewportPaneWidth", Authority: AuthorityControl, Since: 9, Capability: "viewport-column-resize-v1", Stream: "", FieldSince: map[string]uint32{"transaction": 9}, FieldCapabilities: map[string]string{"transaction": "layout-undo-v1"}},
	"set-window-title":                   {Name: "set-window-title", GoMethod: "SetWindowTitle", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"shutdown-daemon":                    {Name: "shutdown-daemon", GoMethod: "ShutdownDaemon", Authority: AuthorityLocalAdmin, Since: 9, Capability: "", Stream: "", FieldSince: map[string]uint32{"force": 10}, FieldCapabilities: map[string]string{"force": "daemon-handoff-force-v1"}},
	"sidebar-plugin":                     {Name: "sidebar-plugin", GoMethod: "SidebarPlugin", Authority: AuthorityFrontend, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"split":                              {Name: "split", GoMethod: "Split", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"subscribe":                          {Name: "subscribe", GoMethod: "Subscribe", Authority: AuthorityFrontend, Since: 5, Capability: "", Stream: "subscribe", FieldSince: map[string]uint32{"surface": 9, "tree_events": 7}, FieldCapabilities: map[string]string{"surface": "surface-subscribe-filter"}},
	"swap-pane":                          {Name: "swap-pane", GoMethod: "SwapPane", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"terminal-events":                    {Name: "terminal-events", GoMethod: "TerminalEvents", Authority: AuthorityControl, Since: 9, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"undo-layout":                        {Name: "undo-layout", GoMethod: "UndoLayout", Authority: AuthorityControl, Since: 9, Capability: "layout-undo-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"unregister-browser-provider":        {Name: "unregister-browser-provider", GoMethod: "UnregisterBrowserProvider", Authority: AuthorityLocalAdmin, Since: 10, Capability: "browser-provider-v1", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"vt-state":                           {Name: "vt-state", GoMethod: "VTState", Authority: AuthorityControl, Since: 5, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"wait-for":                           {Name: "wait-for", GoMethod: "WaitFor", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
	"zoom-pane":                          {Name: "zoom-pane", GoMethod: "ZoomPane", Authority: AuthorityControl, Since: 6, Capability: "", Stream: "", FieldSince: nil, FieldCapabilities: nil},
}

var eventMetadata = map[string]EventMetadata{
	"agent-changed":               {Name: "agent-changed", Since: 11, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"bell":                        {Name: "bell", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"browser-state":               {Name: "browser-state", Since: 6, Capability: "", Streams: []string{"attach-browser"}, Emission: "emitted"},
	"client-attached":             {Name: "client-attached", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-changed":              {Name: "client-changed", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-detached":             {Name: "client-detached", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"client-list-invalidated":     {Name: "client-list-invalidated", Since: 9, Capability: "", Streams: []string{"subscribe"}, Emission: "serialized-never-emitted"},
	"colors-changed":              {Name: "colors-changed", Since: 6, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"config-reload-requested":     {Name: "config-reload-requested", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"detached":                    {Name: "detached", Since: 5, Capability: "", Streams: []string{"attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"empty":                       {Name: "empty", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"frame":                       {Name: "frame", Since: 6, Capability: "", Streams: []string{"attach-browser"}, Emission: "emitted"},
	"frontend-projection-changed": {Name: "frontend-projection-changed", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"graphics-status":             {Name: "graphics-status", Since: 10, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"layout-changed":              {Name: "layout-changed", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"notification":                {Name: "notification", Since: 6, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-browser"}, Emission: "emitted"},
	"output":                      {Name: "output", Since: 5, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"overflow":                    {Name: "overflow", Since: 7, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"pairing-requested":           {Name: "pairing-requested", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"pairing-resolved":            {Name: "pairing-resolved", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"pane-added":                  {Name: "pane-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"pane-closed":                 {Name: "pane-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"render-delta":                {Name: "render-delta", Since: 7, Capability: "", Streams: []string{"attach-render"}, Emission: "emitted"},
	"render-state":                {Name: "render-state", Since: 7, Capability: "", Streams: []string{"attach-render"}, Emission: "emitted"},
	"resized":                     {Name: "resized", Since: 6, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"screen-added":                {Name: "screen-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"screen-closed":               {Name: "screen-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"screen-renamed":              {Name: "screen-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"scroll-changed":              {Name: "scroll-changed", Since: 6, Capability: "", Streams: []string{"subscribe", "attach-byte", "attach-render", "attach-browser"}, Emission: "emitted"},
	"status":                      {Name: "status", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-exited":              {Name: "surface-exited", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-output":              {Name: "surface-output", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-resize-failed":       {Name: "surface-resize-failed", Since: 7, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"surface-resized":             {Name: "surface-resized", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"tab-added":                   {Name: "tab-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"tab-closed":                  {Name: "tab-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"tab-renamed":                 {Name: "tab-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"terminal-registry-changed":   {Name: "terminal-registry-changed", Since: 9, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"title-changed":               {Name: "title-changed", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"tree-changed":                {Name: "tree-changed", Since: 5, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"vt-state":                    {Name: "vt-state", Since: 5, Capability: "", Streams: []string{"attach-byte"}, Emission: "emitted"},
	"window-title-requested":      {Name: "window-title-requested", Since: 6, Capability: "", Streams: []string{"subscribe"}, Emission: "emitted"},
	"workspace-added":             {Name: "workspace-added", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-closed":            {Name: "workspace-closed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-moved":             {Name: "workspace-moved", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
	"workspace-renamed":           {Name: "workspace-renamed", Since: 7, Capability: "", Streams: []string{"subscribe-deltas"}, Emission: "emitted"},
}

func CommandInfo(name string) (CommandMetadata, bool) {
	metadata, ok := commandMetadata[name]
	if ok {
		metadata = cloneCommandMetadata(metadata)
	}
	return metadata, ok
}

func cloneCommandMetadata(metadata CommandMetadata) CommandMetadata {
	if metadata.FieldSince != nil {
		values := metadata.FieldSince
		metadata.FieldSince = make(map[string]uint32, len(metadata.FieldSince))
		for name, since := range values {
			metadata.FieldSince[name] = since
		}
	}
	if metadata.FieldCapabilities != nil {
		values := metadata.FieldCapabilities
		metadata.FieldCapabilities = make(map[string]string, len(metadata.FieldCapabilities))
		for name, capability := range values {
			metadata.FieldCapabilities[name] = capability
		}
	}
	return metadata
}

func EventInfo(name string) (EventMetadata, bool) {
	metadata, ok := eventMetadata[name]
	if ok {
		metadata.Streams = append([]string(nil), metadata.Streams...)
	}
	return metadata, ok
}

func ProfileInfo(name Profile) (ProfileMetadata, bool) {
	metadata, ok := profileMetadata[name]
	if ok {
		metadata.Inherits = append([]Profile(nil), metadata.Inherits...)
	}
	return metadata, ok
}

func AllCommandMetadata() []CommandMetadata {
	result := make([]CommandMetadata, 0, 103)
	result = append(result, cloneCommandMetadata(commandMetadata["apply-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["attach-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-activate"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-back"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-forward"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-frame-presented"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-insert-text"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-key"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-key-press"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-mouse"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-mouse-guarded"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-navigate"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-reload"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-wheel"]))
	result = append(result, cloneCommandMetadata(commandMetadata["browser-wheel-guarded"]))
	result = append(result, cloneCommandMetadata(commandMetadata["clear-history"]))
	result = append(result, cloneCommandMetadata(commandMetadata["clear-window-title"]))
	result = append(result, cloneCommandMetadata(commandMetadata["client-focus"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-provider-managed-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["close-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["copy"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-surface-with-receipt"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["create-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["detach-attached-view"]))
	result = append(result, cloneCommandMetadata(commandMetadata["detach-client"]))
	result = append(result, cloneCommandMetadata(commandMetadata["export-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["focus-direction"]))
	result = append(result, cloneCommandMetadata(commandMetadata["focus-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-cell-pixels"]))
	result = append(result, cloneCommandMetadata(commandMetadata["get-frontend-projection"]))
	result = append(result, cloneCommandMetadata(commandMetadata["identify"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ids"]))
	result = append(result, cloneCommandMetadata(commandMetadata["journal-frontend-event"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-agents"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-clients"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-terminals"]))
	result = append(result, cloneCommandMetadata(commandMetadata["list-workspaces"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mark-workspaces-provider-managed"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mint-terminal-renderer"]))
	result = append(result, cloneCommandMetadata(commandMetadata["mint-terminal-renderer-by-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["move-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-browser-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-pane-right"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["new-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["notify"]))
	result = append(result, cloneCommandMetadata(commandMetadata["pairing-response"]))
	result = append(result, cloneCommandMetadata(commandMetadata["pane-neighbor"]))
	result = append(result, cloneCommandMetadata(commandMetadata["ping"]))
	result = append(result, cloneCommandMetadata(commandMetadata["process-info"]))
	result = append(result, cloneCommandMetadata(commandMetadata["put-frontend-projection"]))
	result = append(result, cloneCommandMetadata(commandMetadata["read-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["read-scrollback"]))
	result = append(result, cloneCommandMetadata(commandMetadata["register-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["release-attached-view-size"]))
	result = append(result, cloneCommandMetadata(commandMetadata["release-surface-size"]))
	result = append(result, cloneCommandMetadata(commandMetadata["reload-config"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-provider-managed-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["rename-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["report-agent"]))
	result = append(result, cloneCommandMetadata(commandMetadata["report-focus"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resize-attached-view"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resize-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["resolve-terminal"]))
	result = append(result, cloneCommandMetadata(commandMetadata["run"]))
	result = append(result, cloneCommandMetadata(commandMetadata["scroll-surface"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-screen"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-tab"]))
	result = append(result, cloneCommandMetadata(commandMetadata["select-workspace"]))
	result = append(result, cloneCommandMetadata(commandMetadata["send"]))
	result = append(result, cloneCommandMetadata(commandMetadata["send-key"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-cell-pixels"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-client-info"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-client-sizing"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-default-colors"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-ratio"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-split-ratio"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-viewport-pane-width"]))
	result = append(result, cloneCommandMetadata(commandMetadata["set-window-title"]))
	result = append(result, cloneCommandMetadata(commandMetadata["shutdown-daemon"]))
	result = append(result, cloneCommandMetadata(commandMetadata["sidebar-plugin"]))
	result = append(result, cloneCommandMetadata(commandMetadata["split"]))
	result = append(result, cloneCommandMetadata(commandMetadata["subscribe"]))
	result = append(result, cloneCommandMetadata(commandMetadata["swap-pane"]))
	result = append(result, cloneCommandMetadata(commandMetadata["terminal-events"]))
	result = append(result, cloneCommandMetadata(commandMetadata["undo-layout"]))
	result = append(result, cloneCommandMetadata(commandMetadata["unregister-browser-provider"]))
	result = append(result, cloneCommandMetadata(commandMetadata["vt-state"]))
	result = append(result, cloneCommandMetadata(commandMetadata["wait-for"]))
	result = append(result, cloneCommandMetadata(commandMetadata["zoom-pane"]))
	return result
}

func AllEventMetadata() []EventMetadata {
	result := make([]EventMetadata, 0, 46)
	var metadata EventMetadata
	metadata = eventMetadata["agent-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["bell"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["browser-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-attached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-detached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["client-list-invalidated"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["colors-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["config-reload-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["detached"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["empty"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["frame"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["frontend-projection-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["graphics-status"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["layout-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["notification"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["output"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["overflow"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pairing-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pairing-resolved"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pane-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["pane-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["render-delta"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["render-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["resized"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["screen-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["scroll-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["status"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-exited"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-output"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-resize-failed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["surface-resized"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tab-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["terminal-registry-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["title-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["tree-changed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["vt-state"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["window-title-requested"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-added"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-closed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-moved"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	metadata = eventMetadata["workspace-renamed"]
	metadata.Streams = append([]string(nil), metadata.Streams...)
	result = append(result, metadata)
	return result
}
